// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io_petstore.ApiResponse in petstore.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package io_petstore

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ApiResponse(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val code: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val type: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val message: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ApiResponse, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ApiResponse) return false
    if (unknownFields != other.unknownFields) return false
    if (code != other.code) return false
    if (type != other.type) return false
    if (message != other.message) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + code.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + message.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """code=$code"""
    result += """type=${sanitize(type)}"""
    result += """message=${sanitize(message)}"""
    return result.joinToString(prefix = "ApiResponse{", separator = ", ", postfix = "}")
  }

  public fun copy(
    code: Int = this.code,
    type: String = this.type,
    message: String = this.message,
    unknownFields: ByteString = this.unknownFields,
  ): ApiResponse = ApiResponse(code, type, message, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ApiResponse> = object : ProtoAdapter<ApiResponse>(
      FieldEncoding.LENGTH_DELIMITED, 
      ApiResponse::class, 
      "type.googleapis.com/io_petstore.ApiResponse", 
      PROTO_3, 
      null, 
      "petstore.proto"
    ) {
      override fun encodedSize(`value`: ApiResponse): Int {
        var size = value.unknownFields.size
        if (value.code != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.code)
        }
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.type)
        }
        if (value.message != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.message)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ApiResponse) {
        if (value.code != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.code)
        }
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.type)
        }
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.message)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ApiResponse) {
        writer.writeBytes(value.unknownFields)
        if (value.message != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.message)
        }
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.type)
        }
        if (value.code != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.code)
        }
      }

      override fun decode(reader: ProtoReader): ApiResponse {
        var code: Int = 0
        var type: String = ""
        var message: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> code = ProtoAdapter.INT32.decode(reader)
            2 -> type = ProtoAdapter.STRING.decode(reader)
            3 -> message = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ApiResponse(
          code = code,
          type = type,
          message = message,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ApiResponse): ApiResponse = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
