// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io_petstore.PetstoreService in petstore.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package io_petstore

import com.squareup.wire.GrpcCall
import com.squareup.wire.GrpcClient
import com.squareup.wire.GrpcMethod
import com.squareup.wire.ProtoAdapter
import kotlin.Suppress
import kotlin.Unit

public class GrpcPetstoreServiceClient(
  private val client: GrpcClient,
) : PetstoreServiceClient {
  override fun UpdatePet(): GrpcCall<Pet, Pet> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/UpdatePet",
      requestAdapter = Pet.ADAPTER,
      responseAdapter = Pet.ADAPTER
  ))

  override fun AddPet(): GrpcCall<Pet, Pet> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/AddPet",
      requestAdapter = Pet.ADAPTER,
      responseAdapter = Pet.ADAPTER
  ))

  override fun FindPetsByStatus(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/FindPetsByStatus",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun FindPetsByTags(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/FindPetsByTags",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun GetPetById(): GrpcCall<Unit, Pet> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/GetPetById",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = Pet.ADAPTER
  ))

  override fun UpdatePetWithForm(): GrpcCall<Unit, Pet> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/UpdatePetWithForm",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = Pet.ADAPTER
  ))

  override fun DeletePet(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/DeletePet",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun UploadFile(): GrpcCall<Unit, ApiResponse> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/UploadFile",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ApiResponse.ADAPTER
  ))

  override fun GetInventory(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/GetInventory",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun PlaceOrder(): GrpcCall<Order, Order> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/PlaceOrder",
      requestAdapter = Order.ADAPTER,
      responseAdapter = Order.ADAPTER
  ))

  override fun GetOrderById(): GrpcCall<Unit, Order> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/GetOrderById",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = Order.ADAPTER
  ))

  override fun DeleteOrder(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/DeleteOrder",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun CreateUser(): GrpcCall<User, User> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/CreateUser",
      requestAdapter = User.ADAPTER,
      responseAdapter = User.ADAPTER
  ))

  override fun CreateUsersWithListInput(): GrpcCall<Unit, User> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/CreateUsersWithListInput",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = User.ADAPTER
  ))

  override fun LoginUser(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/LoginUser",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun LogoutUser(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/LogoutUser",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun GetUserByName(): GrpcCall<Unit, User> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/GetUserByName",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = User.ADAPTER
  ))

  override fun UpdateUser(): GrpcCall<User, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/UpdateUser",
      requestAdapter = User.ADAPTER,
      responseAdapter = ProtoAdapter.EMPTY
  ))

  override fun DeleteUser(): GrpcCall<Unit, Unit> = client.newCall(GrpcMethod(
      path = "/io_petstore.PetstoreService/DeleteUser",
      requestAdapter = ProtoAdapter.EMPTY,
      responseAdapter = ProtoAdapter.EMPTY
  ))
}
