// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io_petstore.Order in petstore.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package io_petstore

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class Order(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val petId: Long = 0L,
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val quantity: Int = 0,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val shipDate: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val status: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val complete: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Order, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Order) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (petId != other.petId) return false
    if (quantity != other.quantity) return false
    if (shipDate != other.shipDate) return false
    if (status != other.status) return false
    if (complete != other.complete) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + petId.hashCode()
      result = result * 37 + quantity.hashCode()
      result = result * 37 + shipDate.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + complete.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    result += """petId=$petId"""
    result += """quantity=$quantity"""
    result += """shipDate=${sanitize(shipDate)}"""
    result += """status=${sanitize(status)}"""
    result += """complete=$complete"""
    return result.joinToString(prefix = "Order{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: Long = this.id,
    petId: Long = this.petId,
    quantity: Int = this.quantity,
    shipDate: String = this.shipDate,
    status: String = this.status,
    complete: Boolean = this.complete,
    unknownFields: ByteString = this.unknownFields,
  ): Order = Order(id, petId, quantity, shipDate, status, complete, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Order> = object : ProtoAdapter<Order>(
      FieldEncoding.LENGTH_DELIMITED, 
      Order::class, 
      "type.googleapis.com/io_petstore.Order", 
      PROTO_3, 
      null, 
      "petstore.proto"
    ) {
      override fun encodedSize(`value`: Order): Int {
        var size = value.unknownFields.size
        if (value.id != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(1, value.id)
        }
        if (value.petId != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(2, value.petId)
        }
        if (value.quantity != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.quantity)
        }
        if (value.shipDate != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.shipDate)
        }
        if (value.status != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.status)
        }
        if (value.complete != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(6, value.complete)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Order) {
        if (value.id != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id)
        }
        if (value.petId != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.petId)
        }
        if (value.quantity != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.quantity)
        }
        if (value.shipDate != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.shipDate)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.status)
        }
        if (value.complete != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.complete)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Order) {
        writer.writeBytes(value.unknownFields)
        if (value.complete != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 6, value.complete)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.status)
        }
        if (value.shipDate != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.shipDate)
        }
        if (value.quantity != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.quantity)
        }
        if (value.petId != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.petId)
        }
        if (value.id != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): Order {
        var id: Long = 0L
        var petId: Long = 0L
        var quantity: Int = 0
        var shipDate: String = ""
        var status: String = ""
        var complete: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.INT64.decode(reader)
            2 -> petId = ProtoAdapter.INT64.decode(reader)
            3 -> quantity = ProtoAdapter.INT32.decode(reader)
            4 -> shipDate = ProtoAdapter.STRING.decode(reader)
            5 -> status = ProtoAdapter.STRING.decode(reader)
            6 -> complete = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Order(
          id = id,
          petId = petId,
          quantity = quantity,
          shipDate = shipDate,
          status = status,
          complete = complete,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Order): Order = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
