// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io_petstore.User in petstore.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package io_petstore

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class User(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: Long = 0L,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val username: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val firstName: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val lastName: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val email: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val password: String = "",
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val phone: String = "",
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val userStatus: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<User, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is User) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (username != other.username) return false
    if (firstName != other.firstName) return false
    if (lastName != other.lastName) return false
    if (email != other.email) return false
    if (password != other.password) return false
    if (phone != other.phone) return false
    if (userStatus != other.userStatus) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + username.hashCode()
      result = result * 37 + firstName.hashCode()
      result = result * 37 + lastName.hashCode()
      result = result * 37 + email.hashCode()
      result = result * 37 + password.hashCode()
      result = result * 37 + phone.hashCode()
      result = result * 37 + userStatus.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=$id"""
    result += """username=${sanitize(username)}"""
    result += """firstName=${sanitize(firstName)}"""
    result += """lastName=${sanitize(lastName)}"""
    result += """email=${sanitize(email)}"""
    result += """password=${sanitize(password)}"""
    result += """phone=${sanitize(phone)}"""
    result += """userStatus=$userStatus"""
    return result.joinToString(prefix = "User{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: Long = this.id,
    username: String = this.username,
    firstName: String = this.firstName,
    lastName: String = this.lastName,
    email: String = this.email,
    password: String = this.password,
    phone: String = this.phone,
    userStatus: Int = this.userStatus,
    unknownFields: ByteString = this.unknownFields,
  ): User = User(id, username, firstName, lastName, email, password, phone, userStatus, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<User> = object : ProtoAdapter<User>(
      FieldEncoding.LENGTH_DELIMITED, 
      User::class, 
      "type.googleapis.com/io_petstore.User", 
      PROTO_3, 
      null, 
      "petstore.proto"
    ) {
      override fun encodedSize(`value`: User): Int {
        var size = value.unknownFields.size
        if (value.id != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(1, value.id)
        }
        if (value.username != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.username)
        }
        if (value.firstName != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.firstName)
        }
        if (value.lastName != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.lastName)
        }
        if (value.email != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.email)
        }
        if (value.password != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.password)
        }
        if (value.phone != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.phone)
        }
        if (value.userStatus != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(8, value.userStatus)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: User) {
        if (value.id != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id)
        }
        if (value.username != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.username)
        }
        if (value.firstName != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.firstName)
        }
        if (value.lastName != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.lastName)
        }
        if (value.email != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.email)
        }
        if (value.password != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.password)
        }
        if (value.phone != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.phone)
        }
        if (value.userStatus != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 8, value.userStatus)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: User) {
        writer.writeBytes(value.unknownFields)
        if (value.userStatus != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 8, value.userStatus)
        }
        if (value.phone != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.phone)
        }
        if (value.password != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.password)
        }
        if (value.email != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.email)
        }
        if (value.lastName != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.lastName)
        }
        if (value.firstName != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.firstName)
        }
        if (value.username != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.username)
        }
        if (value.id != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): User {
        var id: Long = 0L
        var username: String = ""
        var firstName: String = ""
        var lastName: String = ""
        var email: String = ""
        var password: String = ""
        var phone: String = ""
        var userStatus: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.INT64.decode(reader)
            2 -> username = ProtoAdapter.STRING.decode(reader)
            3 -> firstName = ProtoAdapter.STRING.decode(reader)
            4 -> lastName = ProtoAdapter.STRING.decode(reader)
            5 -> email = ProtoAdapter.STRING.decode(reader)
            6 -> password = ProtoAdapter.STRING.decode(reader)
            7 -> phone = ProtoAdapter.STRING.decode(reader)
            8 -> userStatus = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return User(
          id = id,
          username = username,
          firstName = firstName,
          lastName = lastName,
          email = email,
          password = password,
          phone = phone,
          userStatus = userStatus,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: User): User = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
