// Code generated by Wire protocol buffer compiler, do not edit.
// Source: io_petstore.PetstoreService in petstore.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package io_petstore

import com.squareup.wire.GrpcCall
import com.squareup.wire.Service
import kotlin.Suppress
import kotlin.Unit

public interface PetstoreServiceClient : Service {
  public fun UpdatePet(): GrpcCall<Pet, Pet>

  public fun AddPet(): GrpcCall<Pet, Pet>

  public fun FindPetsByStatus(): GrpcCall<Unit, Unit>

  public fun FindPetsByTags(): GrpcCall<Unit, Unit>

  public fun GetPetById(): GrpcCall<Unit, Pet>

  public fun UpdatePetWithForm(): GrpcCall<Unit, Pet>

  public fun DeletePet(): GrpcCall<Unit, Unit>

  public fun UploadFile(): GrpcCall<Unit, ApiResponse>

  public fun GetInventory(): GrpcCall<Unit, Unit>

  public fun PlaceOrder(): GrpcCall<Order, Order>

  public fun GetOrderById(): GrpcCall<Unit, Order>

  public fun DeleteOrder(): GrpcCall<Unit, Unit>

  public fun CreateUser(): GrpcCall<User, User>

  public fun CreateUsersWithListInput(): GrpcCall<Unit, User>

  public fun LoginUser(): GrpcCall<Unit, Unit>

  public fun LogoutUser(): GrpcCall<Unit, Unit>

  public fun GetUserByName(): GrpcCall<Unit, User>

  public fun UpdateUser(): GrpcCall<User, Unit>

  public fun DeleteUser(): GrpcCall<Unit, Unit>
}
