// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.anthropic.core.GeoIp in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.anthropic.core

import com.google.type.LatLng
import com.google.type.Money
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * GeoIP — links IP → country → all localized formats
 */
public class GeoIp(
  /**
   * IpAddress (v4/v6)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val ip: String = "",
  /**
   * ISO 3166-1 alpha-2
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val country: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val city: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val region: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "postalCode",
    schemaIndex = 4,
  )
  public val postal_code: String = "",
  /**
   * IANA timezone ID
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val timezone: String = "",
  /**
   * BCP 47 locale tag
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val locale: String = "",
  /**
   * google.type.Money
   */
  @field:WireField(
    tag = 8,
    adapter = "com.google.type.Money#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "currencySample",
    schemaIndex = 7,
  )
  public val currency_sample: Money? = null,
  /**
   * ISO 4217
   */
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "currencyCode",
    schemaIndex = 8,
  )
  public val currency_code: String = "",
  /**
   * +1, +44, +81
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "phoneCode",
    schemaIndex = 9,
  )
  public val phone_code: String = "",
  /**
   * google.type.LatLng
   */
  @field:WireField(
    tag = 11,
    adapter = "com.google.type.LatLng#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val location: LatLng? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<GeoIp, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is GeoIp) return false
    if (unknownFields != other.unknownFields) return false
    if (ip != other.ip) return false
    if (country != other.country) return false
    if (city != other.city) return false
    if (region != other.region) return false
    if (postal_code != other.postal_code) return false
    if (timezone != other.timezone) return false
    if (locale != other.locale) return false
    if (currency_sample != other.currency_sample) return false
    if (currency_code != other.currency_code) return false
    if (phone_code != other.phone_code) return false
    if (location != other.location) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + ip.hashCode()
      result = result * 37 + country.hashCode()
      result = result * 37 + city.hashCode()
      result = result * 37 + region.hashCode()
      result = result * 37 + postal_code.hashCode()
      result = result * 37 + timezone.hashCode()
      result = result * 37 + locale.hashCode()
      result = result * 37 + (currency_sample?.hashCode() ?: 0)
      result = result * 37 + currency_code.hashCode()
      result = result * 37 + phone_code.hashCode()
      result = result * 37 + (location?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """ip=${sanitize(ip)}"""
    result += """country=${sanitize(country)}"""
    result += """city=${sanitize(city)}"""
    result += """region=${sanitize(region)}"""
    result += """postal_code=${sanitize(postal_code)}"""
    result += """timezone=${sanitize(timezone)}"""
    result += """locale=${sanitize(locale)}"""
    if (currency_sample != null) result += """currency_sample=$currency_sample"""
    result += """currency_code=${sanitize(currency_code)}"""
    result += """phone_code=${sanitize(phone_code)}"""
    if (location != null) result += """location=$location"""
    return result.joinToString(prefix = "GeoIp{", separator = ", ", postfix = "}")
  }

  public fun copy(
    ip: String = this.ip,
    country: String = this.country,
    city: String = this.city,
    region: String = this.region,
    postal_code: String = this.postal_code,
    timezone: String = this.timezone,
    locale: String = this.locale,
    currency_sample: Money? = this.currency_sample,
    currency_code: String = this.currency_code,
    phone_code: String = this.phone_code,
    location: LatLng? = this.location,
    unknownFields: ByteString = this.unknownFields,
  ): GeoIp = GeoIp(ip, country, city, region, postal_code, timezone, locale, currency_sample, currency_code, phone_code, location, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<GeoIp> = object : ProtoAdapter<GeoIp>(
      FieldEncoding.LENGTH_DELIMITED, 
      GeoIp::class, 
      "type.googleapis.com/com.anthropic.core.GeoIp", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: GeoIp): Int {
        var size = value.unknownFields.size
        if (value.ip != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.ip)
        }
        if (value.country != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.country)
        }
        if (value.city != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.city)
        }
        if (value.region != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.region)
        }
        if (value.postal_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.postal_code)
        }
        if (value.timezone != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.timezone)
        }
        if (value.locale != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.locale)
        }
        if (value.currency_sample != null) {
          size += Money.ADAPTER.encodedSizeWithTag(8, value.currency_sample)
        }
        if (value.currency_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(9, value.currency_code)
        }
        if (value.phone_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(10, value.phone_code)
        }
        if (value.location != null) {
          size += LatLng.ADAPTER.encodedSizeWithTag(11, value.location)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: GeoIp) {
        if (value.ip != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ip)
        }
        if (value.country != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.country)
        }
        if (value.city != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.city)
        }
        if (value.region != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.region)
        }
        if (value.postal_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.postal_code)
        }
        if (value.timezone != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.timezone)
        }
        if (value.locale != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.locale)
        }
        if (value.currency_sample != null) {
          Money.ADAPTER.encodeWithTag(writer, 8, value.currency_sample)
        }
        if (value.currency_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 9, value.currency_code)
        }
        if (value.phone_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.phone_code)
        }
        if (value.location != null) {
          LatLng.ADAPTER.encodeWithTag(writer, 11, value.location)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: GeoIp) {
        writer.writeBytes(value.unknownFields)
        if (value.location != null) {
          LatLng.ADAPTER.encodeWithTag(writer, 11, value.location)
        }
        if (value.phone_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.phone_code)
        }
        if (value.currency_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 9, value.currency_code)
        }
        if (value.currency_sample != null) {
          Money.ADAPTER.encodeWithTag(writer, 8, value.currency_sample)
        }
        if (value.locale != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.locale)
        }
        if (value.timezone != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.timezone)
        }
        if (value.postal_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.postal_code)
        }
        if (value.region != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.region)
        }
        if (value.city != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.city)
        }
        if (value.country != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.country)
        }
        if (value.ip != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.ip)
        }
      }

      override fun decode(reader: ProtoReader): GeoIp {
        var ip: String = ""
        var country: String = ""
        var city: String = ""
        var region: String = ""
        var postal_code: String = ""
        var timezone: String = ""
        var locale: String = ""
        var currency_sample: Money? = null
        var currency_code: String = ""
        var phone_code: String = ""
        var location: LatLng? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> ip = ProtoAdapter.STRING.decode(reader)
            2 -> country = ProtoAdapter.STRING.decode(reader)
            3 -> city = ProtoAdapter.STRING.decode(reader)
            4 -> region = ProtoAdapter.STRING.decode(reader)
            5 -> postal_code = ProtoAdapter.STRING.decode(reader)
            6 -> timezone = ProtoAdapter.STRING.decode(reader)
            7 -> locale = ProtoAdapter.STRING.decode(reader)
            8 -> currency_sample = Money.ADAPTER.decode(reader)
            9 -> currency_code = ProtoAdapter.STRING.decode(reader)
            10 -> phone_code = ProtoAdapter.STRING.decode(reader)
            11 -> location = LatLng.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return GeoIp(
          ip = ip,
          country = country,
          city = city,
          region = region,
          postal_code = postal_code,
          timezone = timezone,
          locale = locale,
          currency_sample = currency_sample,
          currency_code = currency_code,
          phone_code = phone_code,
          location = location,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: GeoIp): GeoIp = value.copy(
        currency_sample = value.currency_sample?.let(Money.ADAPTER::redact),
        location = value.location?.let(LatLng.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
