// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.anthropic.core.Measure in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.anthropic.core

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Measure — ICU CLDR + PostGIS + GeoJSON compatible quantity.
 *
 * Unit follows CLDR unit identifier format: "length-meter", "mass-kilogram",
 * "speed-kilometer-per-hour", "digital-megabyte", "duration-second".
 * See: https://unicode.org/reports/tr35/tr35-general.html#Unit_Identifiers
 *
 * Interop:
 * - ICU: com.ibm.icu.util.Measure(Number, MeasureUnit) via MeasureUnit.forIdentifier()
 * - PostGIS: M-coordinate in geometry (ST_MakePointM, ST_M)
 * - GeoJSON: position array \[lon, lat, alt, m\] — the 4th element
 * - UCUM: parseable via ucum-java for medical/scientific units
 */
public class Measure(
  /**
   * numeric value
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "value",
    schemaIndex = 0,
  )
  public val value_: Double = 0.0,
  /**
   * CLDR unit identifier: "length-meter"
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val unit: String = "",
  /**
   * "metric" | "ussystem" | "uksystem" | "ucum"
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val system: String = "",
  /**
   * localized name (optional, e.g., "kilometers")
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "displayName",
    schemaIndex = 3,
  )
  public val display_name: String = "",
  /**
   * ± range (for scientific measurements)
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val uncertainty: Double = 0.0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Measure, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Measure) return false
    if (unknownFields != other.unknownFields) return false
    if (value_ != other.value_) return false
    if (unit != other.unit) return false
    if (system != other.system) return false
    if (display_name != other.display_name) return false
    if (uncertainty != other.uncertainty) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + value_.hashCode()
      result = result * 37 + unit.hashCode()
      result = result * 37 + system.hashCode()
      result = result * 37 + display_name.hashCode()
      result = result * 37 + uncertainty.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """value_=$value_"""
    result += """unit=${sanitize(unit)}"""
    result += """system=${sanitize(system)}"""
    result += """display_name=${sanitize(display_name)}"""
    result += """uncertainty=$uncertainty"""
    return result.joinToString(prefix = "Measure{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value_: Double = this.value_,
    unit: String = this.unit,
    system: String = this.system,
    display_name: String = this.display_name,
    uncertainty: Double = this.uncertainty,
    unknownFields: ByteString = this.unknownFields,
  ): Measure = Measure(value_, unit, system, display_name, uncertainty, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Measure> = object : ProtoAdapter<Measure>(
      FieldEncoding.LENGTH_DELIMITED, 
      Measure::class, 
      "type.googleapis.com/com.anthropic.core.Measure", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: Measure): Int {
        var size = value.unknownFields.size
        if (!value.value_.equals(0.0)) {
          size += ProtoAdapter.DOUBLE.encodedSizeWithTag(1, value.value_)
        }
        if (value.unit != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.unit)
        }
        if (value.system != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.system)
        }
        if (value.display_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.display_name)
        }
        if (!value.uncertainty.equals(0.0)) {
          size += ProtoAdapter.DOUBLE.encodedSizeWithTag(5, value.uncertainty)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Measure) {
        if (!value.value_.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.value_)
        }
        if (value.unit != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.unit)
        }
        if (value.system != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.system)
        }
        if (value.display_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.display_name)
        }
        if (!value.uncertainty.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 5, value.uncertainty)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Measure) {
        writer.writeBytes(value.unknownFields)
        if (!value.uncertainty.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 5, value.uncertainty)
        }
        if (value.display_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.display_name)
        }
        if (value.system != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.system)
        }
        if (value.unit != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.unit)
        }
        if (!value.value_.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.value_)
        }
      }

      override fun decode(reader: ProtoReader): Measure {
        var value_: Double = 0.0
        var unit: String = ""
        var system: String = ""
        var display_name: String = ""
        var uncertainty: Double = 0.0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_ = ProtoAdapter.DOUBLE.decode(reader)
            2 -> unit = ProtoAdapter.STRING.decode(reader)
            3 -> system = ProtoAdapter.STRING.decode(reader)
            4 -> display_name = ProtoAdapter.STRING.decode(reader)
            5 -> uncertainty = ProtoAdapter.DOUBLE.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Measure(
          value_ = value_,
          unit = unit,
          system = system,
          display_name = display_name,
          uncertainty = uncertainty,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Measure): Measure = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
