// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.anthropic.core.Measure in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.anthropic.core

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Measure — value + unit (UCUM/CLDR compatible)
 */
public class Measure(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "value",
    schemaIndex = 0,
  )
  public val value_: Double = 0.0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val unit: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Measure, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Measure) return false
    if (unknownFields != other.unknownFields) return false
    if (value_ != other.value_) return false
    if (unit != other.unit) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + value_.hashCode()
      result = result * 37 + unit.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """value_=$value_"""
    result += """unit=${sanitize(unit)}"""
    return result.joinToString(prefix = "Measure{", separator = ", ", postfix = "}")
  }

  public fun copy(
    value_: Double = this.value_,
    unit: String = this.unit,
    unknownFields: ByteString = this.unknownFields,
  ): Measure = Measure(value_, unit, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Measure> = object : ProtoAdapter<Measure>(
      FieldEncoding.LENGTH_DELIMITED, 
      Measure::class, 
      "type.googleapis.com/com.anthropic.core.Measure", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: Measure): Int {
        var size = value.unknownFields.size
        if (!value.value_.equals(0.0)) {
          size += ProtoAdapter.DOUBLE.encodedSizeWithTag(1, value.value_)
        }
        if (value.unit != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.unit)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Measure) {
        if (!value.value_.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.value_)
        }
        if (value.unit != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.unit)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Measure) {
        writer.writeBytes(value.unknownFields)
        if (value.unit != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.unit)
        }
        if (!value.value_.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.value_)
        }
      }

      override fun decode(reader: ProtoReader): Measure {
        var value_: Double = 0.0
        var unit: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> value_ = ProtoAdapter.DOUBLE.decode(reader)
            2 -> unit = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Measure(
          value_ = value_,
          unit = unit,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Measure): Measure = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
