// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.anthropic.core.PatchEvent in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.anthropic.core

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Instant
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * PatchEvent — universal mutation event (SSE + WebSocket sync)
 */
public class PatchEvent(
  /**
   * add/replace/remove/patch
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val op: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "entityId",
    schemaIndex = 1,
  )
  public val entity_id: String = "",
  /**
   * serialized entity
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val before: ByteString = ByteString.EMPTY,
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val after: ByteString = ByteString.EMPTY,
  patch: List<PatchOperation> = emptyList(),
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val timestamp: Instant? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PatchEvent, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 5,
    adapter = "com.anthropic.core.PatchOperation#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val patch: List<PatchOperation> = immutableCopyOf("patch", patch)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PatchEvent) return false
    if (unknownFields != other.unknownFields) return false
    if (op != other.op) return false
    if (entity_id != other.entity_id) return false
    if (before != other.before) return false
    if (after != other.after) return false
    if (patch != other.patch) return false
    if (timestamp != other.timestamp) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + op.hashCode()
      result = result * 37 + entity_id.hashCode()
      result = result * 37 + before.hashCode()
      result = result * 37 + after.hashCode()
      result = result * 37 + patch.hashCode()
      result = result * 37 + (timestamp?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """op=${sanitize(op)}"""
    result += """entity_id=${sanitize(entity_id)}"""
    result += """before=$before"""
    result += """after=$after"""
    if (patch.isNotEmpty()) result += """patch=$patch"""
    if (timestamp != null) result += """timestamp=$timestamp"""
    return result.joinToString(prefix = "PatchEvent{", separator = ", ", postfix = "}")
  }

  public fun copy(
    op: String = this.op,
    entity_id: String = this.entity_id,
    before: ByteString = this.before,
    after: ByteString = this.after,
    patch: List<PatchOperation> = this.patch,
    timestamp: Instant? = this.timestamp,
    unknownFields: ByteString = this.unknownFields,
  ): PatchEvent = PatchEvent(op, entity_id, before, after, patch, timestamp, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PatchEvent> = object : ProtoAdapter<PatchEvent>(
      FieldEncoding.LENGTH_DELIMITED, 
      PatchEvent::class, 
      "type.googleapis.com/com.anthropic.core.PatchEvent", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: PatchEvent): Int {
        var size = value.unknownFields.size
        if (value.op != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.op)
        }
        if (value.entity_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.entity_id)
        }
        if (value.before != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(3, value.before)
        }
        if (value.after != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(4, value.after)
        }
        size += PatchOperation.ADAPTER.asRepeated().encodedSizeWithTag(5, value.patch)
        if (value.timestamp != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(6, value.timestamp)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PatchEvent) {
        if (value.op != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.op)
        }
        if (value.entity_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.entity_id)
        }
        if (value.before != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.before)
        }
        if (value.after != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 4, value.after)
        }
        PatchOperation.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.patch)
        if (value.timestamp != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 6, value.timestamp)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PatchEvent) {
        writer.writeBytes(value.unknownFields)
        if (value.timestamp != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 6, value.timestamp)
        }
        PatchOperation.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.patch)
        if (value.after != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 4, value.after)
        }
        if (value.before != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.before)
        }
        if (value.entity_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.entity_id)
        }
        if (value.op != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.op)
        }
      }

      override fun decode(reader: ProtoReader): PatchEvent {
        var op: String = ""
        var entity_id: String = ""
        var before: ByteString = ByteString.EMPTY
        var after: ByteString = ByteString.EMPTY
        val patch = mutableListOf<PatchOperation>()
        var timestamp: Instant? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> op = ProtoAdapter.STRING.decode(reader)
            2 -> entity_id = ProtoAdapter.STRING.decode(reader)
            3 -> before = ProtoAdapter.BYTES.decode(reader)
            4 -> after = ProtoAdapter.BYTES.decode(reader)
            5 -> patch.add(PatchOperation.ADAPTER.decode(reader))
            6 -> timestamp = ProtoAdapter.INSTANT.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PatchEvent(
          op = op,
          entity_id = entity_id,
          before = before,
          after = after,
          patch = patch,
          timestamp = timestamp,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PatchEvent): PatchEvent = value.copy(
        patch = value.patch.redactElements(PatchOperation.ADAPTER),
        timestamp = value.timestamp?.let(ProtoAdapter.INSTANT::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
