// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.anthropic.core.PersonName in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.anthropic.core

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * === Value Types — Wire KMP data classes using Google standard protos ===
 * Structured person name (ICU PersonName, Google People API compatible)
 */
public class PersonName(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val given: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val family: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val prefix: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val suffix: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val middle: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PersonName, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PersonName) return false
    if (unknownFields != other.unknownFields) return false
    if (given != other.given) return false
    if (family != other.family) return false
    if (prefix != other.prefix) return false
    if (suffix != other.suffix) return false
    if (middle != other.middle) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + given.hashCode()
      result = result * 37 + family.hashCode()
      result = result * 37 + prefix.hashCode()
      result = result * 37 + suffix.hashCode()
      result = result * 37 + middle.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """given=${sanitize(given)}"""
    result += """family=${sanitize(family)}"""
    result += """prefix=${sanitize(prefix)}"""
    result += """suffix=${sanitize(suffix)}"""
    result += """middle=${sanitize(middle)}"""
    return result.joinToString(prefix = "PersonName{", separator = ", ", postfix = "}")
  }

  public fun copy(
    given: String = this.given,
    family: String = this.family,
    prefix: String = this.prefix,
    suffix: String = this.suffix,
    middle: String = this.middle,
    unknownFields: ByteString = this.unknownFields,
  ): PersonName = PersonName(given, family, prefix, suffix, middle, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PersonName> = object : ProtoAdapter<PersonName>(
      FieldEncoding.LENGTH_DELIMITED, 
      PersonName::class, 
      "type.googleapis.com/com.anthropic.core.PersonName", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: PersonName): Int {
        var size = value.unknownFields.size
        if (value.given != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.given)
        }
        if (value.family != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.family)
        }
        if (value.prefix != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.prefix)
        }
        if (value.suffix != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.suffix)
        }
        if (value.middle != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.middle)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PersonName) {
        if (value.given != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.given)
        }
        if (value.family != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.family)
        }
        if (value.prefix != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.prefix)
        }
        if (value.suffix != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.suffix)
        }
        if (value.middle != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.middle)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PersonName) {
        writer.writeBytes(value.unknownFields)
        if (value.middle != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.middle)
        }
        if (value.suffix != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.suffix)
        }
        if (value.prefix != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.prefix)
        }
        if (value.family != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.family)
        }
        if (value.given != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.given)
        }
      }

      override fun decode(reader: ProtoReader): PersonName {
        var given: String = ""
        var family: String = ""
        var prefix: String = ""
        var suffix: String = ""
        var middle: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> given = ProtoAdapter.STRING.decode(reader)
            2 -> family = ProtoAdapter.STRING.decode(reader)
            3 -> prefix = ProtoAdapter.STRING.decode(reader)
            4 -> suffix = ProtoAdapter.STRING.decode(reader)
            5 -> middle = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PersonName(
          given = given,
          family = family,
          prefix = prefix,
          suffix = suffix,
          middle = middle,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PersonName): PersonName = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
