// Code generated by Wire protocol buffer compiler, do not edit.
// Source: com.anthropic.core.VCardContact in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.anthropic.core

import com.google.type.Date
import com.google.type.PhoneNumber
import com.google.type.PostalAddress
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * RFC 6350 vCard Contact — uses google.type where available
 */
public class VCardContact(
  @field:WireField(
    tag = 1,
    adapter = "com.anthropic.core.PersonName#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val name: PersonName? = null,
  emails: List<String> = emptyList(),
  phones: List<PhoneNumber> = emptyList(),
  addresses: List<PostalAddress> = emptyList(),
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val organization: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val title: String = "",
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val role: String = "",
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val url: String = "",
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 8,
  )
  public val photo: String = "",
  /**
   * google.type.Date
   */
  @field:WireField(
    tag = 10,
    adapter = "com.google.type.Date#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 9,
  )
  public val birthday: Date? = null,
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val note: String = "",
  categories: List<String> = emptyList(),
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 12,
  )
  public val uid: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<VCardContact, Nothing>(ADAPTER, unknownFields) {
  /**
   * RFC 5321 email
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val emails: List<String> = immutableCopyOf("emails", emails)

  /**
   * google.type.PhoneNumber
   */
  @field:WireField(
    tag = 3,
    adapter = "com.google.type.PhoneNumber#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val phones: List<PhoneNumber> = immutableCopyOf("phones", phones)

  /**
   * google.type.PostalAddress (CLDR)
   */
  @field:WireField(
    tag = 4,
    adapter = "com.google.type.PostalAddress#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 3,
  )
  public val addresses: List<PostalAddress> = immutableCopyOf("addresses", addresses)

  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 11,
  )
  public val categories: List<String> = immutableCopyOf("categories", categories)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is VCardContact) return false
    if (unknownFields != other.unknownFields) return false
    if (name != other.name) return false
    if (emails != other.emails) return false
    if (phones != other.phones) return false
    if (addresses != other.addresses) return false
    if (organization != other.organization) return false
    if (title != other.title) return false
    if (role != other.role) return false
    if (url != other.url) return false
    if (photo != other.photo) return false
    if (birthday != other.birthday) return false
    if (note != other.note) return false
    if (categories != other.categories) return false
    if (uid != other.uid) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (name?.hashCode() ?: 0)
      result = result * 37 + emails.hashCode()
      result = result * 37 + phones.hashCode()
      result = result * 37 + addresses.hashCode()
      result = result * 37 + organization.hashCode()
      result = result * 37 + title.hashCode()
      result = result * 37 + role.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + photo.hashCode()
      result = result * 37 + (birthday?.hashCode() ?: 0)
      result = result * 37 + note.hashCode()
      result = result * 37 + categories.hashCode()
      result = result * 37 + uid.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (name != null) result += """name=$name"""
    if (emails.isNotEmpty()) result += """emails=${sanitize(emails)}"""
    if (phones.isNotEmpty()) result += """phones=$phones"""
    if (addresses.isNotEmpty()) result += """addresses=$addresses"""
    result += """organization=${sanitize(organization)}"""
    result += """title=${sanitize(title)}"""
    result += """role=${sanitize(role)}"""
    result += """url=${sanitize(url)}"""
    result += """photo=${sanitize(photo)}"""
    if (birthday != null) result += """birthday=$birthday"""
    result += """note=${sanitize(note)}"""
    if (categories.isNotEmpty()) result += """categories=${sanitize(categories)}"""
    result += """uid=${sanitize(uid)}"""
    return result.joinToString(prefix = "VCardContact{", separator = ", ", postfix = "}")
  }

  public fun copy(
    name: PersonName? = this.name,
    emails: List<String> = this.emails,
    phones: List<PhoneNumber> = this.phones,
    addresses: List<PostalAddress> = this.addresses,
    organization: String = this.organization,
    title: String = this.title,
    role: String = this.role,
    url: String = this.url,
    photo: String = this.photo,
    birthday: Date? = this.birthday,
    note: String = this.note,
    categories: List<String> = this.categories,
    uid: String = this.uid,
    unknownFields: ByteString = this.unknownFields,
  ): VCardContact = VCardContact(name, emails, phones, addresses, organization, title, role, url, photo, birthday, note, categories, uid, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<VCardContact> = object : ProtoAdapter<VCardContact>(
      FieldEncoding.LENGTH_DELIMITED, 
      VCardContact::class, 
      "type.googleapis.com/com.anthropic.core.VCardContact", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: VCardContact): Int {
        var size = value.unknownFields.size
        if (value.name != null) {
          size += PersonName.ADAPTER.encodedSizeWithTag(1, value.name)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(2, value.emails)
        size += PhoneNumber.ADAPTER.asRepeated().encodedSizeWithTag(3, value.phones)
        size += PostalAddress.ADAPTER.asRepeated().encodedSizeWithTag(4, value.addresses)
        if (value.organization != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.organization)
        }
        if (value.title != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.title)
        }
        if (value.role != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.role)
        }
        if (value.url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(8, value.url)
        }
        if (value.photo != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(9, value.photo)
        }
        if (value.birthday != null) {
          size += Date.ADAPTER.encodedSizeWithTag(10, value.birthday)
        }
        if (value.note != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(11, value.note)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(12, value.categories)
        if (value.uid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(13, value.uid)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: VCardContact) {
        if (value.name != null) {
          PersonName.ADAPTER.encodeWithTag(writer, 1, value.name)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.emails)
        PhoneNumber.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.phones)
        PostalAddress.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.addresses)
        if (value.organization != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.organization)
        }
        if (value.title != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.title)
        }
        if (value.role != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.role)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.url)
        }
        if (value.photo != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 9, value.photo)
        }
        if (value.birthday != null) {
          Date.ADAPTER.encodeWithTag(writer, 10, value.birthday)
        }
        if (value.note != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.note)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 12, value.categories)
        if (value.uid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 13, value.uid)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: VCardContact) {
        writer.writeBytes(value.unknownFields)
        if (value.uid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 13, value.uid)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 12, value.categories)
        if (value.note != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.note)
        }
        if (value.birthday != null) {
          Date.ADAPTER.encodeWithTag(writer, 10, value.birthday)
        }
        if (value.photo != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 9, value.photo)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.url)
        }
        if (value.role != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.role)
        }
        if (value.title != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.title)
        }
        if (value.organization != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.organization)
        }
        PostalAddress.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.addresses)
        PhoneNumber.ADAPTER.asRepeated().encodeWithTag(writer, 3, value.phones)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 2, value.emails)
        if (value.name != null) {
          PersonName.ADAPTER.encodeWithTag(writer, 1, value.name)
        }
      }

      override fun decode(reader: ProtoReader): VCardContact {
        var name: PersonName? = null
        val emails = mutableListOf<String>()
        val phones = mutableListOf<PhoneNumber>()
        val addresses = mutableListOf<PostalAddress>()
        var organization: String = ""
        var title: String = ""
        var role: String = ""
        var url: String = ""
        var photo: String = ""
        var birthday: Date? = null
        var note: String = ""
        val categories = mutableListOf<String>()
        var uid: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> name = PersonName.ADAPTER.decode(reader)
            2 -> emails.add(ProtoAdapter.STRING.decode(reader))
            3 -> phones.add(PhoneNumber.ADAPTER.decode(reader))
            4 -> addresses.add(PostalAddress.ADAPTER.decode(reader))
            5 -> organization = ProtoAdapter.STRING.decode(reader)
            6 -> title = ProtoAdapter.STRING.decode(reader)
            7 -> role = ProtoAdapter.STRING.decode(reader)
            8 -> url = ProtoAdapter.STRING.decode(reader)
            9 -> photo = ProtoAdapter.STRING.decode(reader)
            10 -> birthday = Date.ADAPTER.decode(reader)
            11 -> note = ProtoAdapter.STRING.decode(reader)
            12 -> categories.add(ProtoAdapter.STRING.decode(reader))
            13 -> uid = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return VCardContact(
          name = name,
          emails = emails,
          phones = phones,
          addresses = addresses,
          organization = organization,
          title = title,
          role = role,
          url = url,
          photo = photo,
          birthday = birthday,
          note = note,
          categories = categories,
          uid = uid,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: VCardContact): VCardContact = value.copy(
        name = value.name?.let(PersonName.ADAPTER::redact),
        phones = value.phones.redactElements(PhoneNumber.ADAPTER),
        addresses = value.addresses.redactElements(PostalAddress.ADAPTER),
        birthday = value.birthday?.let(Date.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
