package kotlinx.kmp.util.core.json

import kotlinx.kmp.util.core.ApiJsonBackend
import kotlinx.serialization.KSerializer
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement
import kotlinx.serialization.serializer

/**
 * [ApiJsonBackend] implementation backed by kotlinx.serialization.
 *
 * This is the multiplatform-native JSON backend. It works on JVM, JS, and
 * Native — anywhere kotlinx.serialization runs. Model classes must be
 * annotated with `@Serializable` for this backend to handle them.
 *
 * On JVM the default backend is still Jackson ([JacksonApiJsonBackend]) for
 * backward compatibility with existing model classes that use Jackson
 * annotations. This kotlinx backend is available as an explicit opt-in:
 *
 * ```kotlin
 * val backend = KotlinxApiJsonBackend()
 * val json: String = backend.encodeToString(myModel, MyModel.serializer())
 * val model: MyModel = backend.decodeFromString(json, MyModel.serializer())
 * ```
 *
 * For model classes generated by api-gen with `@Serializable`, this backend
 * is the preferred path on all platforms.
 */
class KotlinxApiJsonBackend(
    private val json: Json = Json {
        ignoreUnknownKeys = true
        isLenient = true
        encodeDefaults = false
        prettyPrint = false
        coerceInputValues = true
    }
) : ApiJsonBackend() {

    private val prettyJson: Json = Json(json) { prettyPrint = true }

    /**
     * Encode [value] to JSON using its [KSerializer].
     *
     * The [value] must be accompanied by a serializer in [typeDescriptor]:
     * ```kotlin
     * backend.encodeToString(myModel, MyModel.serializer())
     * ```
     */
    @Suppress("UNCHECKED_CAST")
    override fun encodeToString(value: Any?): String {
        if (value == null) return "null"
        // Try to find the serializer via the runtime class
        val serializer = json.serializersModule.serializer(value::class, emptyList(), false)
        return json.encodeToString(serializer as KSerializer<Any>, value)
    }

    /**
     * Encode using an explicit serializer (type-safe path).
     */
    fun <T> encodeToString(value: T, serializer: KSerializer<T>): String =
        json.encodeToString(serializer, value)

    /**
     * Decode JSON using the [typeDescriptor] which must be a [KSerializer].
     */
    @Suppress("UNCHECKED_CAST")
    override fun <T> decodeFromString(jsonString: String, typeDescriptor: Any): T =
        when (typeDescriptor) {
            is KSerializer<*> -> json.decodeFromString(typeDescriptor as KSerializer<T>, jsonString)
            else -> throw IllegalArgumentException(
                "KotlinxApiJsonBackend requires KSerializer<T>, got ${typeDescriptor::class.simpleName}"
            )
        }

    /**
     * Decode using an explicit serializer (type-safe path).
     */
    fun <T> decodeFromString(jsonString: String, serializer: KSerializer<T>): T =
        json.decodeFromString(serializer, jsonString)

    override fun encodePretty(value: Any?): String {
        if (value == null) return "null"
        @Suppress("UNCHECKED_CAST")
        val serializer = prettyJson.serializersModule.serializer(value::class, emptyList(), false)
        return prettyJson.encodeToString(serializer as KSerializer<Any>, value)
    }

    /**
     * Parse raw JSON string into a kotlinx.serialization [JsonElement] tree.
     * Useful for schema validation, union-type discrimination, etc.
     */
    fun parseToJsonElement(jsonString: String): JsonElement =
        json.parseToJsonElement(jsonString)

    /** Access the underlying [Json] instance for advanced use cases. */
    fun json(): Json = json
}
