// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ChatMessage in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * === Generic LLM types — vendor-agnostic across Anthropic/OpenAI/Gemini/etc. ===
 *
 * These cover the shape common to all chat-completion APIs. Concrete vendor
 * adapters (LangChain4j, direct ktor) translate these to/from their native
 * request types. Proto is the single source of truth so every KMP target —
 * JVM, JS, Native, Wasm — has identical structures via Wire generation.
 * A single message in a chat conversation. Mirrors Anthropic Messages + OpenAI
 * Chat Completion + Gemini Content. `role` is one of: system, user, assistant,
 * tool. `content` is a list of mixed-type blocks (text, image, tool call, etc.).
 */
public class ChatMessage(
  /**
   * system|user|assistant|tool
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val role: String = "",
  content: List<ContentBlock> = emptyList(),
  /**
   * optional author/tool name (OpenAI)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val name: String = "",
  /**
   * when role=tool, the id we're responding to
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "toolCallId",
    schemaIndex = 3,
  )
  public val tool_call_id: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ChatMessage, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "kotlinx.kmp.util.ContentBlock#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val content: List<ContentBlock> = immutableCopyOf("content", content)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ChatMessage) return false
    if (unknownFields != other.unknownFields) return false
    if (role != other.role) return false
    if (content != other.content) return false
    if (name != other.name) return false
    if (tool_call_id != other.tool_call_id) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + role.hashCode()
      result = result * 37 + content.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + tool_call_id.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """role=${sanitize(role)}"""
    if (content.isNotEmpty()) result += """content=$content"""
    result += """name=${sanitize(name)}"""
    result += """tool_call_id=${sanitize(tool_call_id)}"""
    return result.joinToString(prefix = "ChatMessage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    role: String = this.role,
    content: List<ContentBlock> = this.content,
    name: String = this.name,
    tool_call_id: String = this.tool_call_id,
    unknownFields: ByteString = this.unknownFields,
  ): ChatMessage = ChatMessage(role, content, name, tool_call_id, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ChatMessage> = object : ProtoAdapter<ChatMessage>(
      FieldEncoding.LENGTH_DELIMITED, 
      ChatMessage::class, 
      "type.googleapis.com/kotlinx.kmp.util.ChatMessage", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ChatMessage): Int {
        var size = value.unknownFields.size
        if (value.role != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.role)
        }
        size += ContentBlock.ADAPTER.asRepeated().encodedSizeWithTag(2, value.content)
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.name)
        }
        if (value.tool_call_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.tool_call_id)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ChatMessage) {
        if (value.role != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.role)
        }
        ContentBlock.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.content)
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.name)
        }
        if (value.tool_call_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.tool_call_id)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ChatMessage) {
        writer.writeBytes(value.unknownFields)
        if (value.tool_call_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.tool_call_id)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.name)
        }
        ContentBlock.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.content)
        if (value.role != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.role)
        }
      }

      override fun decode(reader: ProtoReader): ChatMessage {
        var role: String = ""
        val content = mutableListOf<ContentBlock>()
        var name: String = ""
        var tool_call_id: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> role = ProtoAdapter.STRING.decode(reader)
            2 -> content.add(ContentBlock.ADAPTER.decode(reader))
            3 -> name = ProtoAdapter.STRING.decode(reader)
            4 -> tool_call_id = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ChatMessage(
          role = role,
          content = content,
          name = name,
          tool_call_id = tool_call_id,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ChatMessage): ChatMessage = value.copy(
        content = value.content.redactElements(ContentBlock.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
