// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ContentBlockStart in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ContentBlockStart(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val index: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "kotlinx.kmp.util.ContentBlock#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "contentBlock",
    schemaIndex = 1,
  )
  public val content_block: ContentBlock? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ContentBlockStart, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ContentBlockStart) return false
    if (unknownFields != other.unknownFields) return false
    if (index != other.index) return false
    if (content_block != other.content_block) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + index.hashCode()
      result = result * 37 + (content_block?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """index=$index"""
    if (content_block != null) result += """content_block=$content_block"""
    return result.joinToString(prefix = "ContentBlockStart{", separator = ", ", postfix = "}")
  }

  public fun copy(
    index: Int = this.index,
    content_block: ContentBlock? = this.content_block,
    unknownFields: ByteString = this.unknownFields,
  ): ContentBlockStart = ContentBlockStart(index, content_block, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ContentBlockStart> = object : ProtoAdapter<ContentBlockStart>(
      FieldEncoding.LENGTH_DELIMITED, 
      ContentBlockStart::class, 
      "type.googleapis.com/kotlinx.kmp.util.ContentBlockStart", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ContentBlockStart): Int {
        var size = value.unknownFields.size
        if (value.index != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.index)
        }
        if (value.content_block != null) {
          size += ContentBlock.ADAPTER.encodedSizeWithTag(2, value.content_block)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ContentBlockStart) {
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.index)
        }
        if (value.content_block != null) {
          ContentBlock.ADAPTER.encodeWithTag(writer, 2, value.content_block)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ContentBlockStart) {
        writer.writeBytes(value.unknownFields)
        if (value.content_block != null) {
          ContentBlock.ADAPTER.encodeWithTag(writer, 2, value.content_block)
        }
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.index)
        }
      }

      override fun decode(reader: ProtoReader): ContentBlockStart {
        var index: Int = 0
        var content_block: ContentBlock? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> index = ProtoAdapter.INT32.decode(reader)
            2 -> content_block = ContentBlock.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ContentBlockStart(
          index = index,
          content_block = content_block,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ContentBlockStart): ContentBlockStart = value.copy(
        content_block = value.content_block?.let(ContentBlock.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
