// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ContentBlockDelta in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ContentBlockDelta(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val index: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val text: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "partialJson",
    schemaIndex = 2,
  )
  public val partial_json: ByteString = ByteString.EMPTY,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ContentBlockDelta, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ContentBlockDelta) return false
    if (unknownFields != other.unknownFields) return false
    if (index != other.index) return false
    if (text != other.text) return false
    if (partial_json != other.partial_json) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + index.hashCode()
      result = result * 37 + text.hashCode()
      result = result * 37 + partial_json.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """index=$index"""
    result += """text=${sanitize(text)}"""
    result += """partial_json=$partial_json"""
    return result.joinToString(prefix = "ContentBlockDelta{", separator = ", ", postfix = "}")
  }

  public fun copy(
    index: Int = this.index,
    text: String = this.text,
    partial_json: ByteString = this.partial_json,
    unknownFields: ByteString = this.unknownFields,
  ): ContentBlockDelta = ContentBlockDelta(index, text, partial_json, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ContentBlockDelta> = object : ProtoAdapter<ContentBlockDelta>(
      FieldEncoding.LENGTH_DELIMITED, 
      ContentBlockDelta::class, 
      "type.googleapis.com/kotlinx.kmp.util.ContentBlockDelta", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ContentBlockDelta): Int {
        var size = value.unknownFields.size
        if (value.index != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.index)
        }
        if (value.text != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.text)
        }
        if (value.partial_json != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(3, value.partial_json)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ContentBlockDelta) {
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.index)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.text)
        }
        if (value.partial_json != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.partial_json)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ContentBlockDelta) {
        writer.writeBytes(value.unknownFields)
        if (value.partial_json != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.partial_json)
        }
        if (value.text != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.text)
        }
        if (value.index != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.index)
        }
      }

      override fun decode(reader: ProtoReader): ContentBlockDelta {
        var index: Int = 0
        var text: String = ""
        var partial_json: ByteString = ByteString.EMPTY
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> index = ProtoAdapter.INT32.decode(reader)
            2 -> text = ProtoAdapter.STRING.decode(reader)
            3 -> partial_json = ProtoAdapter.BYTES.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ContentBlockDelta(
          index = index,
          text = text,
          partial_json = partial_json,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ContentBlockDelta): ContentBlockDelta = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
