// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ContentBlock in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * A content block inside a ChatMessage — oneof the supported types.
 * Follows Anthropic's content-block model which supersets OpenAI/Gemini.
 */
public class ContentBlock(
  @field:WireField(
    tag = 1,
    adapter = "kotlinx.kmp.util.TextBlock#ADAPTER",
    oneofName = "block",
    schemaIndex = 0,
  )
  public val text: TextBlock? = null,
  @field:WireField(
    tag = 2,
    adapter = "kotlinx.kmp.util.ImageBlock#ADAPTER",
    oneofName = "block",
    schemaIndex = 1,
  )
  public val image: ImageBlock? = null,
  @field:WireField(
    tag = 3,
    adapter = "kotlinx.kmp.util.ToolUseBlock#ADAPTER",
    jsonName = "toolUse",
    oneofName = "block",
    schemaIndex = 2,
  )
  public val tool_use: ToolUseBlock? = null,
  @field:WireField(
    tag = 4,
    adapter = "kotlinx.kmp.util.ToolResultBlock#ADAPTER",
    jsonName = "toolResult",
    oneofName = "block",
    schemaIndex = 3,
  )
  public val tool_result: ToolResultBlock? = null,
  /**
   * PDF, text file, etc.
   */
  @field:WireField(
    tag = 5,
    adapter = "kotlinx.kmp.util.DocumentBlock#ADAPTER",
    oneofName = "block",
    schemaIndex = 4,
  )
  public val document: DocumentBlock? = null,
  /**
   * Extended thinking (Claude 4+)
   */
  @field:WireField(
    tag = 6,
    adapter = "kotlinx.kmp.util.ThinkingBlock#ADAPTER",
    oneofName = "block",
    schemaIndex = 5,
  )
  public val thinking: ThinkingBlock? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ContentBlock, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(text, image, tool_use, tool_result, document, thinking) <= 1) {
      "At most one of text, image, tool_use, tool_result, document, thinking may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ContentBlock) return false
    if (unknownFields != other.unknownFields) return false
    if (text != other.text) return false
    if (image != other.image) return false
    if (tool_use != other.tool_use) return false
    if (tool_result != other.tool_result) return false
    if (document != other.document) return false
    if (thinking != other.thinking) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (text?.hashCode() ?: 0)
      result = result * 37 + (image?.hashCode() ?: 0)
      result = result * 37 + (tool_use?.hashCode() ?: 0)
      result = result * 37 + (tool_result?.hashCode() ?: 0)
      result = result * 37 + (document?.hashCode() ?: 0)
      result = result * 37 + (thinking?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (text != null) result += """text=$text"""
    if (image != null) result += """image=$image"""
    if (tool_use != null) result += """tool_use=$tool_use"""
    if (tool_result != null) result += """tool_result=$tool_result"""
    if (document != null) result += """document=$document"""
    if (thinking != null) result += """thinking=$thinking"""
    return result.joinToString(prefix = "ContentBlock{", separator = ", ", postfix = "}")
  }

  public fun copy(
    text: TextBlock? = this.text,
    image: ImageBlock? = this.image,
    tool_use: ToolUseBlock? = this.tool_use,
    tool_result: ToolResultBlock? = this.tool_result,
    document: DocumentBlock? = this.document,
    thinking: ThinkingBlock? = this.thinking,
    unknownFields: ByteString = this.unknownFields,
  ): ContentBlock = ContentBlock(text, image, tool_use, tool_result, document, thinking, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ContentBlock> = object : ProtoAdapter<ContentBlock>(
      FieldEncoding.LENGTH_DELIMITED, 
      ContentBlock::class, 
      "type.googleapis.com/kotlinx.kmp.util.ContentBlock", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ContentBlock): Int {
        var size = value.unknownFields.size
        size += TextBlock.ADAPTER.encodedSizeWithTag(1, value.text)
        size += ImageBlock.ADAPTER.encodedSizeWithTag(2, value.image)
        size += ToolUseBlock.ADAPTER.encodedSizeWithTag(3, value.tool_use)
        size += ToolResultBlock.ADAPTER.encodedSizeWithTag(4, value.tool_result)
        size += DocumentBlock.ADAPTER.encodedSizeWithTag(5, value.document)
        size += ThinkingBlock.ADAPTER.encodedSizeWithTag(6, value.thinking)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ContentBlock) {
        TextBlock.ADAPTER.encodeWithTag(writer, 1, value.text)
        ImageBlock.ADAPTER.encodeWithTag(writer, 2, value.image)
        ToolUseBlock.ADAPTER.encodeWithTag(writer, 3, value.tool_use)
        ToolResultBlock.ADAPTER.encodeWithTag(writer, 4, value.tool_result)
        DocumentBlock.ADAPTER.encodeWithTag(writer, 5, value.document)
        ThinkingBlock.ADAPTER.encodeWithTag(writer, 6, value.thinking)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ContentBlock) {
        writer.writeBytes(value.unknownFields)
        ThinkingBlock.ADAPTER.encodeWithTag(writer, 6, value.thinking)
        DocumentBlock.ADAPTER.encodeWithTag(writer, 5, value.document)
        ToolResultBlock.ADAPTER.encodeWithTag(writer, 4, value.tool_result)
        ToolUseBlock.ADAPTER.encodeWithTag(writer, 3, value.tool_use)
        ImageBlock.ADAPTER.encodeWithTag(writer, 2, value.image)
        TextBlock.ADAPTER.encodeWithTag(writer, 1, value.text)
      }

      override fun decode(reader: ProtoReader): ContentBlock {
        var text: TextBlock? = null
        var image: ImageBlock? = null
        var tool_use: ToolUseBlock? = null
        var tool_result: ToolResultBlock? = null
        var document: DocumentBlock? = null
        var thinking: ThinkingBlock? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> text = TextBlock.ADAPTER.decode(reader)
            2 -> image = ImageBlock.ADAPTER.decode(reader)
            3 -> tool_use = ToolUseBlock.ADAPTER.decode(reader)
            4 -> tool_result = ToolResultBlock.ADAPTER.decode(reader)
            5 -> document = DocumentBlock.ADAPTER.decode(reader)
            6 -> thinking = ThinkingBlock.ADAPTER.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ContentBlock(
          text = text,
          image = image,
          tool_use = tool_use,
          tool_result = tool_result,
          document = document,
          thinking = thinking,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ContentBlock): ContentBlock = value.copy(
        text = value.text?.let(TextBlock.ADAPTER::redact),
        image = value.image?.let(ImageBlock.ADAPTER::redact),
        tool_use = value.tool_use?.let(ToolUseBlock.ADAPTER::redact),
        tool_result = value.tool_result?.let(ToolResultBlock.ADAPTER::redact),
        document = value.document?.let(DocumentBlock.ADAPTER::redact),
        thinking = value.thinking?.let(ThinkingBlock.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
