// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ICalJournal in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Instant
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * RFC 5545 §3.6.3 VJOURNAL — journal entry / note.
 */
public class ICalJournal(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val uid: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val summary: String = "",
  description: List<String> = emptyList(),
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "dtStart",
    schemaIndex = 3,
  )
  public val dt_start: Instant? = null,
  /**
   * DRAFT/FINAL/CANCELLED
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val status: String = "",
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val url: String = "",
  categories: List<String> = emptyList(),
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val organizer: String = "",
  attendees: List<ICalAttendee> = emptyList(),
  related_to: List<String> = emptyList(),
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "class",
    schemaIndex = 10,
  )
  public val class_: String = "",
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 11,
  )
  public val created: Instant? = null,
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastModified",
    schemaIndex = 12,
  )
  public val last_modified: Instant? = null,
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 13,
  )
  public val sequence: Int = 0,
  @field:WireField(
    tag = 15,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 14,
  )
  public val rrule: String = "",
  contact: List<String> = emptyList(),
  attach: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ICalJournal, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 2,
  )
  public val description: List<String> = immutableCopyOf("description", description)

  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 6,
  )
  public val categories: List<String> = immutableCopyOf("categories", categories)

  @field:WireField(
    tag = 9,
    adapter = "kotlinx.kmp.util.ICalAttendee#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 8,
  )
  public val attendees: List<ICalAttendee> = immutableCopyOf("attendees", attendees)

  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "relatedTo",
    schemaIndex = 9,
  )
  public val related_to: List<String> = immutableCopyOf("related_to", related_to)

  @field:WireField(
    tag = 16,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 15,
  )
  public val contact: List<String> = immutableCopyOf("contact", contact)

  @field:WireField(
    tag = 17,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 16,
  )
  public val attach: List<String> = immutableCopyOf("attach", attach)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ICalJournal) return false
    if (unknownFields != other.unknownFields) return false
    if (uid != other.uid) return false
    if (summary != other.summary) return false
    if (description != other.description) return false
    if (dt_start != other.dt_start) return false
    if (status != other.status) return false
    if (url != other.url) return false
    if (categories != other.categories) return false
    if (organizer != other.organizer) return false
    if (attendees != other.attendees) return false
    if (related_to != other.related_to) return false
    if (class_ != other.class_) return false
    if (created != other.created) return false
    if (last_modified != other.last_modified) return false
    if (sequence != other.sequence) return false
    if (rrule != other.rrule) return false
    if (contact != other.contact) return false
    if (attach != other.attach) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + uid.hashCode()
      result = result * 37 + summary.hashCode()
      result = result * 37 + description.hashCode()
      result = result * 37 + (dt_start?.hashCode() ?: 0)
      result = result * 37 + status.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + categories.hashCode()
      result = result * 37 + organizer.hashCode()
      result = result * 37 + attendees.hashCode()
      result = result * 37 + related_to.hashCode()
      result = result * 37 + class_.hashCode()
      result = result * 37 + (created?.hashCode() ?: 0)
      result = result * 37 + (last_modified?.hashCode() ?: 0)
      result = result * 37 + sequence.hashCode()
      result = result * 37 + rrule.hashCode()
      result = result * 37 + contact.hashCode()
      result = result * 37 + attach.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """uid=${sanitize(uid)}"""
    result += """summary=${sanitize(summary)}"""
    if (description.isNotEmpty()) result += """description=${sanitize(description)}"""
    if (dt_start != null) result += """dt_start=$dt_start"""
    result += """status=${sanitize(status)}"""
    result += """url=${sanitize(url)}"""
    if (categories.isNotEmpty()) result += """categories=${sanitize(categories)}"""
    result += """organizer=${sanitize(organizer)}"""
    if (attendees.isNotEmpty()) result += """attendees=$attendees"""
    if (related_to.isNotEmpty()) result += """related_to=${sanitize(related_to)}"""
    result += """class_=${sanitize(class_)}"""
    if (created != null) result += """created=$created"""
    if (last_modified != null) result += """last_modified=$last_modified"""
    result += """sequence=$sequence"""
    result += """rrule=${sanitize(rrule)}"""
    if (contact.isNotEmpty()) result += """contact=${sanitize(contact)}"""
    if (attach.isNotEmpty()) result += """attach=${sanitize(attach)}"""
    return result.joinToString(prefix = "ICalJournal{", separator = ", ", postfix = "}")
  }

  public fun copy(
    uid: String = this.uid,
    summary: String = this.summary,
    description: List<String> = this.description,
    dt_start: Instant? = this.dt_start,
    status: String = this.status,
    url: String = this.url,
    categories: List<String> = this.categories,
    organizer: String = this.organizer,
    attendees: List<ICalAttendee> = this.attendees,
    related_to: List<String> = this.related_to,
    class_: String = this.class_,
    created: Instant? = this.created,
    last_modified: Instant? = this.last_modified,
    sequence: Int = this.sequence,
    rrule: String = this.rrule,
    contact: List<String> = this.contact,
    attach: List<String> = this.attach,
    unknownFields: ByteString = this.unknownFields,
  ): ICalJournal = ICalJournal(uid, summary, description, dt_start, status, url, categories, organizer, attendees, related_to, class_, created, last_modified, sequence, rrule, contact, attach, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ICalJournal> = object : ProtoAdapter<ICalJournal>(
      FieldEncoding.LENGTH_DELIMITED, 
      ICalJournal::class, 
      "type.googleapis.com/kotlinx.kmp.util.ICalJournal", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ICalJournal): Int {
        var size = value.unknownFields.size
        if (value.uid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.uid)
        }
        if (value.summary != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.summary)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(3, value.description)
        if (value.dt_start != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(4, value.dt_start)
        }
        if (value.status != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.status)
        }
        if (value.url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.url)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(7, value.categories)
        if (value.organizer != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(8, value.organizer)
        }
        size += ICalAttendee.ADAPTER.asRepeated().encodedSizeWithTag(9, value.attendees)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(10, value.related_to)
        if (value.class_ != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(11, value.class_)
        }
        if (value.created != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(12, value.created)
        }
        if (value.last_modified != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(13, value.last_modified)
        }
        if (value.sequence != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(14, value.sequence)
        }
        if (value.rrule != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(15, value.rrule)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(16, value.contact)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(17, value.attach)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ICalJournal) {
        if (value.uid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uid)
        }
        if (value.summary != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.summary)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.description)
        if (value.dt_start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 4, value.dt_start)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.status)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.url)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 7, value.categories)
        if (value.organizer != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.organizer)
        }
        ICalAttendee.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.attendees)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 10, value.related_to)
        if (value.class_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.class_)
        }
        if (value.created != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 12, value.created)
        }
        if (value.last_modified != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 13, value.last_modified)
        }
        if (value.sequence != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 14, value.sequence)
        }
        if (value.rrule != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 15, value.rrule)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 16, value.contact)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 17, value.attach)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ICalJournal) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 17, value.attach)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 16, value.contact)
        if (value.rrule != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 15, value.rrule)
        }
        if (value.sequence != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 14, value.sequence)
        }
        if (value.last_modified != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 13, value.last_modified)
        }
        if (value.created != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 12, value.created)
        }
        if (value.class_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.class_)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 10, value.related_to)
        ICalAttendee.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.attendees)
        if (value.organizer != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.organizer)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 7, value.categories)
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.url)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.status)
        }
        if (value.dt_start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 4, value.dt_start)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 3, value.description)
        if (value.summary != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.summary)
        }
        if (value.uid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uid)
        }
      }

      override fun decode(reader: ProtoReader): ICalJournal {
        var uid: String = ""
        var summary: String = ""
        val description = mutableListOf<String>()
        var dt_start: Instant? = null
        var status: String = ""
        var url: String = ""
        val categories = mutableListOf<String>()
        var organizer: String = ""
        val attendees = mutableListOf<ICalAttendee>()
        val related_to = mutableListOf<String>()
        var class_: String = ""
        var created: Instant? = null
        var last_modified: Instant? = null
        var sequence: Int = 0
        var rrule: String = ""
        val contact = mutableListOf<String>()
        val attach = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> uid = ProtoAdapter.STRING.decode(reader)
            2 -> summary = ProtoAdapter.STRING.decode(reader)
            3 -> description.add(ProtoAdapter.STRING.decode(reader))
            4 -> dt_start = ProtoAdapter.INSTANT.decode(reader)
            5 -> status = ProtoAdapter.STRING.decode(reader)
            6 -> url = ProtoAdapter.STRING.decode(reader)
            7 -> categories.add(ProtoAdapter.STRING.decode(reader))
            8 -> organizer = ProtoAdapter.STRING.decode(reader)
            9 -> attendees.add(ICalAttendee.ADAPTER.decode(reader))
            10 -> related_to.add(ProtoAdapter.STRING.decode(reader))
            11 -> class_ = ProtoAdapter.STRING.decode(reader)
            12 -> created = ProtoAdapter.INSTANT.decode(reader)
            13 -> last_modified = ProtoAdapter.INSTANT.decode(reader)
            14 -> sequence = ProtoAdapter.INT32.decode(reader)
            15 -> rrule = ProtoAdapter.STRING.decode(reader)
            16 -> contact.add(ProtoAdapter.STRING.decode(reader))
            17 -> attach.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ICalJournal(
          uid = uid,
          summary = summary,
          description = description,
          dt_start = dt_start,
          status = status,
          url = url,
          categories = categories,
          organizer = organizer,
          attendees = attendees,
          related_to = related_to,
          class_ = class_,
          created = created,
          last_modified = last_modified,
          sequence = sequence,
          rrule = rrule,
          contact = contact,
          attach = attach,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ICalJournal): ICalJournal = value.copy(
        dt_start = value.dt_start?.let(ProtoAdapter.INSTANT::redact),
        attendees = value.attendees.redactElements(ICalAttendee.ADAPTER),
        created = value.created?.let(ProtoAdapter.INSTANT::redact),
        last_modified = value.last_modified?.let(ProtoAdapter.INSTANT::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
