// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ICalFreeBusyPeriod in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.Duration
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Instant
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * RFC 5545 §3.8.2.6 FREEBUSY property entry.
 */
public class ICalFreeBusyPeriod(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val start: Instant? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DURATION",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val duration: Duration? = null,
  /**
   * FREE/BUSY/BUSY-UNAVAILABLE/BUSY-TENTATIVE
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "fbType",
    schemaIndex = 2,
  )
  public val fb_type: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ICalFreeBusyPeriod, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ICalFreeBusyPeriod) return false
    if (unknownFields != other.unknownFields) return false
    if (start != other.start) return false
    if (duration != other.duration) return false
    if (fb_type != other.fb_type) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (start?.hashCode() ?: 0)
      result = result * 37 + (duration?.hashCode() ?: 0)
      result = result * 37 + fb_type.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (start != null) result += """start=$start"""
    if (duration != null) result += """duration=$duration"""
    result += """fb_type=${sanitize(fb_type)}"""
    return result.joinToString(prefix = "ICalFreeBusyPeriod{", separator = ", ", postfix = "}")
  }

  public fun copy(
    start: Instant? = this.start,
    duration: Duration? = this.duration,
    fb_type: String = this.fb_type,
    unknownFields: ByteString = this.unknownFields,
  ): ICalFreeBusyPeriod = ICalFreeBusyPeriod(start, duration, fb_type, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ICalFreeBusyPeriod> =
        object : ProtoAdapter<ICalFreeBusyPeriod>(
      FieldEncoding.LENGTH_DELIMITED, 
      ICalFreeBusyPeriod::class, 
      "type.googleapis.com/kotlinx.kmp.util.ICalFreeBusyPeriod", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ICalFreeBusyPeriod): Int {
        var size = value.unknownFields.size
        if (value.start != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(1, value.start)
        }
        if (value.duration != null) {
          size += ProtoAdapter.DURATION.encodedSizeWithTag(2, value.duration)
        }
        if (value.fb_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.fb_type)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ICalFreeBusyPeriod) {
        if (value.start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 1, value.start)
        }
        if (value.duration != null) {
          ProtoAdapter.DURATION.encodeWithTag(writer, 2, value.duration)
        }
        if (value.fb_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.fb_type)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ICalFreeBusyPeriod) {
        writer.writeBytes(value.unknownFields)
        if (value.fb_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.fb_type)
        }
        if (value.duration != null) {
          ProtoAdapter.DURATION.encodeWithTag(writer, 2, value.duration)
        }
        if (value.start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 1, value.start)
        }
      }

      override fun decode(reader: ProtoReader): ICalFreeBusyPeriod {
        var start: Instant? = null
        var duration: Duration? = null
        var fb_type: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> start = ProtoAdapter.INSTANT.decode(reader)
            2 -> duration = ProtoAdapter.DURATION.decode(reader)
            3 -> fb_type = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ICalFreeBusyPeriod(
          start = start,
          duration = duration,
          fb_type = fb_type,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ICalFreeBusyPeriod): ICalFreeBusyPeriod = value.copy(
        start = value.start?.let(ProtoAdapter.INSTANT::redact),
        duration = value.duration?.let(ProtoAdapter.DURATION::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
