// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ICalTodo in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.google.type.LatLng
import com.squareup.wire.Duration
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Instant
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * RFC 5545 §3.6.2 VTODO — task / to-do item.
 */
public class ICalTodo(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val uid: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val summary: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val description: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val location: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "dtStart",
    schemaIndex = 4,
  )
  public val dt_start: Instant? = null,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 5,
  )
  public val due: Instant? = null,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val completed: Instant? = null,
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#DURATION",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val duration: Duration? = null,
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 8,
  )
  public val rrule: String = "",
  /**
   * NEEDS-ACTION/COMPLETED/IN-PROCESS/CANCELLED
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 9,
  )
  public val status: String = "",
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val priority: Int = 0,
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "percentComplete",
    schemaIndex = 11,
  )
  public val percent_complete: Int = 0,
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 12,
  )
  public val url: String = "",
  @field:WireField(
    tag = 14,
    adapter = "com.google.type.LatLng#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 13,
  )
  public val geo: LatLng? = null,
  categories: List<String> = emptyList(),
  @field:WireField(
    tag = 16,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 15,
  )
  public val organizer: String = "",
  attendees: List<ICalAttendee> = emptyList(),
  alarms: List<ICalAlarm> = emptyList(),
  /**
   * PUBLIC/PRIVATE/CONFIDENTIAL
   */
  @field:WireField(
    tag = 19,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "class",
    schemaIndex = 18,
  )
  public val class_: String = "",
  @field:WireField(
    tag = 20,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 19,
  )
  public val created: Instant? = null,
  @field:WireField(
    tag = 21,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastModified",
    schemaIndex = 20,
  )
  public val last_modified: Instant? = null,
  @field:WireField(
    tag = 22,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 21,
  )
  public val sequence: Int = 0,
  resources: List<String> = emptyList(),
  related_to: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ICalTodo, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 15,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 14,
  )
  public val categories: List<String> = immutableCopyOf("categories", categories)

  @field:WireField(
    tag = 17,
    adapter = "kotlinx.kmp.util.ICalAttendee#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 16,
  )
  public val attendees: List<ICalAttendee> = immutableCopyOf("attendees", attendees)

  @field:WireField(
    tag = 18,
    adapter = "kotlinx.kmp.util.ICalAlarm#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 17,
  )
  public val alarms: List<ICalAlarm> = immutableCopyOf("alarms", alarms)

  @field:WireField(
    tag = 23,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 22,
  )
  public val resources: List<String> = immutableCopyOf("resources", resources)

  @field:WireField(
    tag = 24,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "relatedTo",
    schemaIndex = 23,
  )
  public val related_to: List<String> = immutableCopyOf("related_to", related_to)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ICalTodo) return false
    if (unknownFields != other.unknownFields) return false
    if (uid != other.uid) return false
    if (summary != other.summary) return false
    if (description != other.description) return false
    if (location != other.location) return false
    if (dt_start != other.dt_start) return false
    if (due != other.due) return false
    if (completed != other.completed) return false
    if (duration != other.duration) return false
    if (rrule != other.rrule) return false
    if (status != other.status) return false
    if (priority != other.priority) return false
    if (percent_complete != other.percent_complete) return false
    if (url != other.url) return false
    if (geo != other.geo) return false
    if (categories != other.categories) return false
    if (organizer != other.organizer) return false
    if (attendees != other.attendees) return false
    if (alarms != other.alarms) return false
    if (class_ != other.class_) return false
    if (created != other.created) return false
    if (last_modified != other.last_modified) return false
    if (sequence != other.sequence) return false
    if (resources != other.resources) return false
    if (related_to != other.related_to) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + uid.hashCode()
      result = result * 37 + summary.hashCode()
      result = result * 37 + description.hashCode()
      result = result * 37 + location.hashCode()
      result = result * 37 + (dt_start?.hashCode() ?: 0)
      result = result * 37 + (due?.hashCode() ?: 0)
      result = result * 37 + (completed?.hashCode() ?: 0)
      result = result * 37 + (duration?.hashCode() ?: 0)
      result = result * 37 + rrule.hashCode()
      result = result * 37 + status.hashCode()
      result = result * 37 + priority.hashCode()
      result = result * 37 + percent_complete.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + (geo?.hashCode() ?: 0)
      result = result * 37 + categories.hashCode()
      result = result * 37 + organizer.hashCode()
      result = result * 37 + attendees.hashCode()
      result = result * 37 + alarms.hashCode()
      result = result * 37 + class_.hashCode()
      result = result * 37 + (created?.hashCode() ?: 0)
      result = result * 37 + (last_modified?.hashCode() ?: 0)
      result = result * 37 + sequence.hashCode()
      result = result * 37 + resources.hashCode()
      result = result * 37 + related_to.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """uid=${sanitize(uid)}"""
    result += """summary=${sanitize(summary)}"""
    result += """description=${sanitize(description)}"""
    result += """location=${sanitize(location)}"""
    if (dt_start != null) result += """dt_start=$dt_start"""
    if (due != null) result += """due=$due"""
    if (completed != null) result += """completed=$completed"""
    if (duration != null) result += """duration=$duration"""
    result += """rrule=${sanitize(rrule)}"""
    result += """status=${sanitize(status)}"""
    result += """priority=$priority"""
    result += """percent_complete=$percent_complete"""
    result += """url=${sanitize(url)}"""
    if (geo != null) result += """geo=$geo"""
    if (categories.isNotEmpty()) result += """categories=${sanitize(categories)}"""
    result += """organizer=${sanitize(organizer)}"""
    if (attendees.isNotEmpty()) result += """attendees=$attendees"""
    if (alarms.isNotEmpty()) result += """alarms=$alarms"""
    result += """class_=${sanitize(class_)}"""
    if (created != null) result += """created=$created"""
    if (last_modified != null) result += """last_modified=$last_modified"""
    result += """sequence=$sequence"""
    if (resources.isNotEmpty()) result += """resources=${sanitize(resources)}"""
    if (related_to.isNotEmpty()) result += """related_to=${sanitize(related_to)}"""
    return result.joinToString(prefix = "ICalTodo{", separator = ", ", postfix = "}")
  }

  public fun copy(
    uid: String = this.uid,
    summary: String = this.summary,
    description: String = this.description,
    location: String = this.location,
    dt_start: Instant? = this.dt_start,
    due: Instant? = this.due,
    completed: Instant? = this.completed,
    duration: Duration? = this.duration,
    rrule: String = this.rrule,
    status: String = this.status,
    priority: Int = this.priority,
    percent_complete: Int = this.percent_complete,
    url: String = this.url,
    geo: LatLng? = this.geo,
    categories: List<String> = this.categories,
    organizer: String = this.organizer,
    attendees: List<ICalAttendee> = this.attendees,
    alarms: List<ICalAlarm> = this.alarms,
    class_: String = this.class_,
    created: Instant? = this.created,
    last_modified: Instant? = this.last_modified,
    sequence: Int = this.sequence,
    resources: List<String> = this.resources,
    related_to: List<String> = this.related_to,
    unknownFields: ByteString = this.unknownFields,
  ): ICalTodo = ICalTodo(uid, summary, description, location, dt_start, due, completed, duration, rrule, status, priority, percent_complete, url, geo, categories, organizer, attendees, alarms, class_, created, last_modified, sequence, resources, related_to, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ICalTodo> = object : ProtoAdapter<ICalTodo>(
      FieldEncoding.LENGTH_DELIMITED, 
      ICalTodo::class, 
      "type.googleapis.com/kotlinx.kmp.util.ICalTodo", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ICalTodo): Int {
        var size = value.unknownFields.size
        if (value.uid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.uid)
        }
        if (value.summary != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.summary)
        }
        if (value.description != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.description)
        }
        if (value.location != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.location)
        }
        if (value.dt_start != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(5, value.dt_start)
        }
        if (value.due != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(6, value.due)
        }
        if (value.completed != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(7, value.completed)
        }
        if (value.duration != null) {
          size += ProtoAdapter.DURATION.encodedSizeWithTag(8, value.duration)
        }
        if (value.rrule != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(9, value.rrule)
        }
        if (value.status != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(10, value.status)
        }
        if (value.priority != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(11, value.priority)
        }
        if (value.percent_complete != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(12, value.percent_complete)
        }
        if (value.url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(13, value.url)
        }
        if (value.geo != null) {
          size += LatLng.ADAPTER.encodedSizeWithTag(14, value.geo)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(15, value.categories)
        if (value.organizer != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(16, value.organizer)
        }
        size += ICalAttendee.ADAPTER.asRepeated().encodedSizeWithTag(17, value.attendees)
        size += ICalAlarm.ADAPTER.asRepeated().encodedSizeWithTag(18, value.alarms)
        if (value.class_ != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(19, value.class_)
        }
        if (value.created != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(20, value.created)
        }
        if (value.last_modified != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(21, value.last_modified)
        }
        if (value.sequence != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(22, value.sequence)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(23, value.resources)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(24, value.related_to)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ICalTodo) {
        if (value.uid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uid)
        }
        if (value.summary != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.summary)
        }
        if (value.description != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.description)
        }
        if (value.location != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.location)
        }
        if (value.dt_start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 5, value.dt_start)
        }
        if (value.due != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 6, value.due)
        }
        if (value.completed != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 7, value.completed)
        }
        if (value.duration != null) {
          ProtoAdapter.DURATION.encodeWithTag(writer, 8, value.duration)
        }
        if (value.rrule != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 9, value.rrule)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.status)
        }
        if (value.priority != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 11, value.priority)
        }
        if (value.percent_complete != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.percent_complete)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 13, value.url)
        }
        if (value.geo != null) {
          LatLng.ADAPTER.encodeWithTag(writer, 14, value.geo)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 15, value.categories)
        if (value.organizer != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 16, value.organizer)
        }
        ICalAttendee.ADAPTER.asRepeated().encodeWithTag(writer, 17, value.attendees)
        ICalAlarm.ADAPTER.asRepeated().encodeWithTag(writer, 18, value.alarms)
        if (value.class_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 19, value.class_)
        }
        if (value.created != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 20, value.created)
        }
        if (value.last_modified != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 21, value.last_modified)
        }
        if (value.sequence != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 22, value.sequence)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 23, value.resources)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 24, value.related_to)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ICalTodo) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 24, value.related_to)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 23, value.resources)
        if (value.sequence != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 22, value.sequence)
        }
        if (value.last_modified != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 21, value.last_modified)
        }
        if (value.created != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 20, value.created)
        }
        if (value.class_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 19, value.class_)
        }
        ICalAlarm.ADAPTER.asRepeated().encodeWithTag(writer, 18, value.alarms)
        ICalAttendee.ADAPTER.asRepeated().encodeWithTag(writer, 17, value.attendees)
        if (value.organizer != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 16, value.organizer)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 15, value.categories)
        if (value.geo != null) {
          LatLng.ADAPTER.encodeWithTag(writer, 14, value.geo)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 13, value.url)
        }
        if (value.percent_complete != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 12, value.percent_complete)
        }
        if (value.priority != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 11, value.priority)
        }
        if (value.status != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.status)
        }
        if (value.rrule != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 9, value.rrule)
        }
        if (value.duration != null) {
          ProtoAdapter.DURATION.encodeWithTag(writer, 8, value.duration)
        }
        if (value.completed != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 7, value.completed)
        }
        if (value.due != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 6, value.due)
        }
        if (value.dt_start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 5, value.dt_start)
        }
        if (value.location != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.location)
        }
        if (value.description != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.description)
        }
        if (value.summary != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.summary)
        }
        if (value.uid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uid)
        }
      }

      override fun decode(reader: ProtoReader): ICalTodo {
        var uid: String = ""
        var summary: String = ""
        var description: String = ""
        var location: String = ""
        var dt_start: Instant? = null
        var due: Instant? = null
        var completed: Instant? = null
        var duration: Duration? = null
        var rrule: String = ""
        var status: String = ""
        var priority: Int = 0
        var percent_complete: Int = 0
        var url: String = ""
        var geo: LatLng? = null
        val categories = mutableListOf<String>()
        var organizer: String = ""
        val attendees = mutableListOf<ICalAttendee>()
        val alarms = mutableListOf<ICalAlarm>()
        var class_: String = ""
        var created: Instant? = null
        var last_modified: Instant? = null
        var sequence: Int = 0
        val resources = mutableListOf<String>()
        val related_to = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> uid = ProtoAdapter.STRING.decode(reader)
            2 -> summary = ProtoAdapter.STRING.decode(reader)
            3 -> description = ProtoAdapter.STRING.decode(reader)
            4 -> location = ProtoAdapter.STRING.decode(reader)
            5 -> dt_start = ProtoAdapter.INSTANT.decode(reader)
            6 -> due = ProtoAdapter.INSTANT.decode(reader)
            7 -> completed = ProtoAdapter.INSTANT.decode(reader)
            8 -> duration = ProtoAdapter.DURATION.decode(reader)
            9 -> rrule = ProtoAdapter.STRING.decode(reader)
            10 -> status = ProtoAdapter.STRING.decode(reader)
            11 -> priority = ProtoAdapter.INT32.decode(reader)
            12 -> percent_complete = ProtoAdapter.INT32.decode(reader)
            13 -> url = ProtoAdapter.STRING.decode(reader)
            14 -> geo = LatLng.ADAPTER.decode(reader)
            15 -> categories.add(ProtoAdapter.STRING.decode(reader))
            16 -> organizer = ProtoAdapter.STRING.decode(reader)
            17 -> attendees.add(ICalAttendee.ADAPTER.decode(reader))
            18 -> alarms.add(ICalAlarm.ADAPTER.decode(reader))
            19 -> class_ = ProtoAdapter.STRING.decode(reader)
            20 -> created = ProtoAdapter.INSTANT.decode(reader)
            21 -> last_modified = ProtoAdapter.INSTANT.decode(reader)
            22 -> sequence = ProtoAdapter.INT32.decode(reader)
            23 -> resources.add(ProtoAdapter.STRING.decode(reader))
            24 -> related_to.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ICalTodo(
          uid = uid,
          summary = summary,
          description = description,
          location = location,
          dt_start = dt_start,
          due = due,
          completed = completed,
          duration = duration,
          rrule = rrule,
          status = status,
          priority = priority,
          percent_complete = percent_complete,
          url = url,
          geo = geo,
          categories = categories,
          organizer = organizer,
          attendees = attendees,
          alarms = alarms,
          class_ = class_,
          created = created,
          last_modified = last_modified,
          sequence = sequence,
          resources = resources,
          related_to = related_to,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ICalTodo): ICalTodo = value.copy(
        dt_start = value.dt_start?.let(ProtoAdapter.INSTANT::redact),
        due = value.due?.let(ProtoAdapter.INSTANT::redact),
        completed = value.completed?.let(ProtoAdapter.INSTANT::redact),
        duration = value.duration?.let(ProtoAdapter.DURATION::redact),
        geo = value.geo?.let(LatLng.ADAPTER::redact),
        attendees = value.attendees.redactElements(ICalAttendee.ADAPTER),
        alarms = value.alarms.redactElements(ICalAlarm.ADAPTER),
        created = value.created?.let(ProtoAdapter.INSTANT::redact),
        last_modified = value.last_modified?.let(ProtoAdapter.INSTANT::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
