// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ICalTimezone in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Instant
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * RFC 5545 §3.6.5 VTIMEZONE — timezone definition with STANDARD/DAYLIGHT.
 */
public class ICalTimezone(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val tzid: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val tzurl: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "lastModified",
    schemaIndex = 2,
  )
  public val last_modified: Instant? = null,
  standard: List<ICalTimezoneObservance> = emptyList(),
  daylight: List<ICalTimezoneObservance> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ICalTimezone, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 4,
    adapter = "kotlinx.kmp.util.ICalTimezoneObservance#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 3,
  )
  public val standard: List<ICalTimezoneObservance> = immutableCopyOf("standard", standard)

  @field:WireField(
    tag = 5,
    adapter = "kotlinx.kmp.util.ICalTimezoneObservance#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val daylight: List<ICalTimezoneObservance> = immutableCopyOf("daylight", daylight)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ICalTimezone) return false
    if (unknownFields != other.unknownFields) return false
    if (tzid != other.tzid) return false
    if (tzurl != other.tzurl) return false
    if (last_modified != other.last_modified) return false
    if (standard != other.standard) return false
    if (daylight != other.daylight) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + tzid.hashCode()
      result = result * 37 + tzurl.hashCode()
      result = result * 37 + (last_modified?.hashCode() ?: 0)
      result = result * 37 + standard.hashCode()
      result = result * 37 + daylight.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """tzid=${sanitize(tzid)}"""
    result += """tzurl=${sanitize(tzurl)}"""
    if (last_modified != null) result += """last_modified=$last_modified"""
    if (standard.isNotEmpty()) result += """standard=$standard"""
    if (daylight.isNotEmpty()) result += """daylight=$daylight"""
    return result.joinToString(prefix = "ICalTimezone{", separator = ", ", postfix = "}")
  }

  public fun copy(
    tzid: String = this.tzid,
    tzurl: String = this.tzurl,
    last_modified: Instant? = this.last_modified,
    standard: List<ICalTimezoneObservance> = this.standard,
    daylight: List<ICalTimezoneObservance> = this.daylight,
    unknownFields: ByteString = this.unknownFields,
  ): ICalTimezone = ICalTimezone(tzid, tzurl, last_modified, standard, daylight, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ICalTimezone> = object : ProtoAdapter<ICalTimezone>(
      FieldEncoding.LENGTH_DELIMITED, 
      ICalTimezone::class, 
      "type.googleapis.com/kotlinx.kmp.util.ICalTimezone", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ICalTimezone): Int {
        var size = value.unknownFields.size
        if (value.tzid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.tzid)
        }
        if (value.tzurl != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.tzurl)
        }
        if (value.last_modified != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(3, value.last_modified)
        }
        size += ICalTimezoneObservance.ADAPTER.asRepeated().encodedSizeWithTag(4, value.standard)
        size += ICalTimezoneObservance.ADAPTER.asRepeated().encodedSizeWithTag(5, value.daylight)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ICalTimezone) {
        if (value.tzid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.tzid)
        }
        if (value.tzurl != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tzurl)
        }
        if (value.last_modified != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 3, value.last_modified)
        }
        ICalTimezoneObservance.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.standard)
        ICalTimezoneObservance.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.daylight)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ICalTimezone) {
        writer.writeBytes(value.unknownFields)
        ICalTimezoneObservance.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.daylight)
        ICalTimezoneObservance.ADAPTER.asRepeated().encodeWithTag(writer, 4, value.standard)
        if (value.last_modified != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 3, value.last_modified)
        }
        if (value.tzurl != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tzurl)
        }
        if (value.tzid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.tzid)
        }
      }

      override fun decode(reader: ProtoReader): ICalTimezone {
        var tzid: String = ""
        var tzurl: String = ""
        var last_modified: Instant? = null
        val standard = mutableListOf<ICalTimezoneObservance>()
        val daylight = mutableListOf<ICalTimezoneObservance>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> tzid = ProtoAdapter.STRING.decode(reader)
            2 -> tzurl = ProtoAdapter.STRING.decode(reader)
            3 -> last_modified = ProtoAdapter.INSTANT.decode(reader)
            4 -> standard.add(ICalTimezoneObservance.ADAPTER.decode(reader))
            5 -> daylight.add(ICalTimezoneObservance.ADAPTER.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ICalTimezone(
          tzid = tzid,
          tzurl = tzurl,
          last_modified = last_modified,
          standard = standard,
          daylight = daylight,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ICalTimezone): ICalTimezone = value.copy(
        last_modified = value.last_modified?.let(ProtoAdapter.INSTANT::redact),
        standard = value.standard.redactElements(ICalTimezoneObservance.ADAPTER),
        daylight = value.daylight.redactElements(ICalTimezoneObservance.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
