// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ICalAlarm in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.Duration
import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * iCal VALARM (RFC 5545)
 */
public class ICalAlarm(
  /**
   * AUDIO/DISPLAY/EMAIL
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val action: String = "",
  /**
   * structured trigger
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DURATION",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "triggerDuration",
    schemaIndex = 1,
  )
  public val trigger_duration: Duration? = null,
  /**
   * raw RFC 5545 (-PT15M)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val trigger: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ICalAlarm, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ICalAlarm) return false
    if (unknownFields != other.unknownFields) return false
    if (action != other.action) return false
    if (trigger_duration != other.trigger_duration) return false
    if (trigger != other.trigger) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + action.hashCode()
      result = result * 37 + (trigger_duration?.hashCode() ?: 0)
      result = result * 37 + trigger.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """action=${sanitize(action)}"""
    if (trigger_duration != null) result += """trigger_duration=$trigger_duration"""
    result += """trigger=${sanitize(trigger)}"""
    return result.joinToString(prefix = "ICalAlarm{", separator = ", ", postfix = "}")
  }

  public fun copy(
    action: String = this.action,
    trigger_duration: Duration? = this.trigger_duration,
    trigger: String = this.trigger,
    unknownFields: ByteString = this.unknownFields,
  ): ICalAlarm = ICalAlarm(action, trigger_duration, trigger, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ICalAlarm> = object : ProtoAdapter<ICalAlarm>(
      FieldEncoding.LENGTH_DELIMITED, 
      ICalAlarm::class, 
      "type.googleapis.com/kotlinx.kmp.util.ICalAlarm", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ICalAlarm): Int {
        var size = value.unknownFields.size
        if (value.action != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.action)
        }
        if (value.trigger_duration != null) {
          size += ProtoAdapter.DURATION.encodedSizeWithTag(2, value.trigger_duration)
        }
        if (value.trigger != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.trigger)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ICalAlarm) {
        if (value.action != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.action)
        }
        if (value.trigger_duration != null) {
          ProtoAdapter.DURATION.encodeWithTag(writer, 2, value.trigger_duration)
        }
        if (value.trigger != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.trigger)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ICalAlarm) {
        writer.writeBytes(value.unknownFields)
        if (value.trigger != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.trigger)
        }
        if (value.trigger_duration != null) {
          ProtoAdapter.DURATION.encodeWithTag(writer, 2, value.trigger_duration)
        }
        if (value.action != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.action)
        }
      }

      override fun decode(reader: ProtoReader): ICalAlarm {
        var action: String = ""
        var trigger_duration: Duration? = null
        var trigger: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> action = ProtoAdapter.STRING.decode(reader)
            2 -> trigger_duration = ProtoAdapter.DURATION.decode(reader)
            3 -> trigger = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ICalAlarm(
          action = action,
          trigger_duration = trigger_duration,
          trigger = trigger,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ICalAlarm): ICalAlarm = value.copy(
        trigger_duration = value.trigger_duration?.let(ProtoAdapter.DURATION::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
