// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ICalTimezoneObservance in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Instant
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * RFC 5545 §3.6.5 STANDARD / DAYLIGHT observance.
 */
public class ICalTimezoneObservance(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "dtStart",
    schemaIndex = 0,
  )
  public val dt_start: Instant? = null,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "tzOffsetFrom",
    schemaIndex = 1,
  )
  public val tz_offset_from: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "tzOffsetTo",
    schemaIndex = 2,
  )
  public val tz_offset_to: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "tzName",
    schemaIndex = 3,
  )
  public val tz_name: String = "",
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val rrule: String = "",
  rdate: List<Instant> = emptyList(),
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val comment: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ICalTimezoneObservance, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#INSTANT",
    label = WireField.Label.REPEATED,
    schemaIndex = 5,
  )
  public val rdate: List<Instant> = immutableCopyOf("rdate", rdate)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ICalTimezoneObservance) return false
    if (unknownFields != other.unknownFields) return false
    if (dt_start != other.dt_start) return false
    if (tz_offset_from != other.tz_offset_from) return false
    if (tz_offset_to != other.tz_offset_to) return false
    if (tz_name != other.tz_name) return false
    if (rrule != other.rrule) return false
    if (rdate != other.rdate) return false
    if (comment != other.comment) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (dt_start?.hashCode() ?: 0)
      result = result * 37 + tz_offset_from.hashCode()
      result = result * 37 + tz_offset_to.hashCode()
      result = result * 37 + tz_name.hashCode()
      result = result * 37 + rrule.hashCode()
      result = result * 37 + rdate.hashCode()
      result = result * 37 + comment.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (dt_start != null) result += """dt_start=$dt_start"""
    result += """tz_offset_from=${sanitize(tz_offset_from)}"""
    result += """tz_offset_to=${sanitize(tz_offset_to)}"""
    result += """tz_name=${sanitize(tz_name)}"""
    result += """rrule=${sanitize(rrule)}"""
    if (rdate.isNotEmpty()) result += """rdate=$rdate"""
    result += """comment=${sanitize(comment)}"""
    return result.joinToString(prefix = "ICalTimezoneObservance{", separator = ", ", postfix = "}")
  }

  public fun copy(
    dt_start: Instant? = this.dt_start,
    tz_offset_from: String = this.tz_offset_from,
    tz_offset_to: String = this.tz_offset_to,
    tz_name: String = this.tz_name,
    rrule: String = this.rrule,
    rdate: List<Instant> = this.rdate,
    comment: String = this.comment,
    unknownFields: ByteString = this.unknownFields,
  ): ICalTimezoneObservance = ICalTimezoneObservance(dt_start, tz_offset_from, tz_offset_to, tz_name, rrule, rdate, comment, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ICalTimezoneObservance> =
        object : ProtoAdapter<ICalTimezoneObservance>(
      FieldEncoding.LENGTH_DELIMITED, 
      ICalTimezoneObservance::class, 
      "type.googleapis.com/kotlinx.kmp.util.ICalTimezoneObservance", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ICalTimezoneObservance): Int {
        var size = value.unknownFields.size
        if (value.dt_start != null) {
          size += ProtoAdapter.INSTANT.encodedSizeWithTag(1, value.dt_start)
        }
        if (value.tz_offset_from != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.tz_offset_from)
        }
        if (value.tz_offset_to != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.tz_offset_to)
        }
        if (value.tz_name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.tz_name)
        }
        if (value.rrule != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.rrule)
        }
        size += ProtoAdapter.INSTANT.asRepeated().encodedSizeWithTag(6, value.rdate)
        if (value.comment != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.comment)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ICalTimezoneObservance) {
        if (value.dt_start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 1, value.dt_start)
        }
        if (value.tz_offset_from != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tz_offset_from)
        }
        if (value.tz_offset_to != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.tz_offset_to)
        }
        if (value.tz_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.tz_name)
        }
        if (value.rrule != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.rrule)
        }
        ProtoAdapter.INSTANT.asRepeated().encodeWithTag(writer, 6, value.rdate)
        if (value.comment != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.comment)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ICalTimezoneObservance) {
        writer.writeBytes(value.unknownFields)
        if (value.comment != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.comment)
        }
        ProtoAdapter.INSTANT.asRepeated().encodeWithTag(writer, 6, value.rdate)
        if (value.rrule != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.rrule)
        }
        if (value.tz_name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.tz_name)
        }
        if (value.tz_offset_to != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.tz_offset_to)
        }
        if (value.tz_offset_from != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.tz_offset_from)
        }
        if (value.dt_start != null) {
          ProtoAdapter.INSTANT.encodeWithTag(writer, 1, value.dt_start)
        }
      }

      override fun decode(reader: ProtoReader): ICalTimezoneObservance {
        var dt_start: Instant? = null
        var tz_offset_from: String = ""
        var tz_offset_to: String = ""
        var tz_name: String = ""
        var rrule: String = ""
        val rdate = mutableListOf<Instant>()
        var comment: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> dt_start = ProtoAdapter.INSTANT.decode(reader)
            2 -> tz_offset_from = ProtoAdapter.STRING.decode(reader)
            3 -> tz_offset_to = ProtoAdapter.STRING.decode(reader)
            4 -> tz_name = ProtoAdapter.STRING.decode(reader)
            5 -> rrule = ProtoAdapter.STRING.decode(reader)
            6 -> rdate.add(ProtoAdapter.INSTANT.decode(reader))
            7 -> comment = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ICalTimezoneObservance(
          dt_start = dt_start,
          tz_offset_from = tz_offset_from,
          tz_offset_to = tz_offset_to,
          tz_name = tz_name,
          rrule = rrule,
          rdate = rdate,
          comment = comment,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ICalTimezoneObservance): ICalTimezoneObservance = value.copy(
        dt_start = value.dt_start?.let(ProtoAdapter.INSTANT::redact),
        rdate = value.rdate.redactElements(ProtoAdapter.INSTANT),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
