// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ICalendar in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * RFC 5545 §3.4 VCALENDAR — top-level wrapper (equivalent to a .ics file).
 */
public class ICalendar(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val prodid: String = "",
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val version: String = "",
  /**
   * GREGORIAN
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val calscale: String = "",
  /**
   * PUBLISH/REQUEST/REPLY/CANCEL/...
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val method: String = "",
  events: List<ICalEvent> = emptyList(),
  todos: List<ICalTodo> = emptyList(),
  journals: List<ICalJournal> = emptyList(),
  free_busy: List<ICalFreeBusy> = emptyList(),
  timezones: List<ICalTimezone> = emptyList(),
  /**
   * NAME (RFC 7986)
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 9,
  )
  public val name: String = "",
  /**
   * DESCRIPTION (RFC 7986)
   */
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val description: String = "",
  @field:WireField(
    tag = 12,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 11,
  )
  public val url: String = "",
  @field:WireField(
    tag = 13,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 12,
  )
  public val color: String = "",
  @field:WireField(
    tag = 14,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 13,
  )
  public val image: String = "",
  @field:WireField(
    tag = 15,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "refreshInterval",
    schemaIndex = 14,
  )
  public val refresh_interval: String = "",
  @field:WireField(
    tag = 16,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 15,
  )
  public val source: String = "",
  categories: List<String> = emptyList(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ICalendar, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 5,
    adapter = "kotlinx.kmp.util.ICalEvent#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 4,
  )
  public val events: List<ICalEvent> = immutableCopyOf("events", events)

  @field:WireField(
    tag = 6,
    adapter = "kotlinx.kmp.util.ICalTodo#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 5,
  )
  public val todos: List<ICalTodo> = immutableCopyOf("todos", todos)

  @field:WireField(
    tag = 7,
    adapter = "kotlinx.kmp.util.ICalJournal#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 6,
  )
  public val journals: List<ICalJournal> = immutableCopyOf("journals", journals)

  @field:WireField(
    tag = 8,
    adapter = "kotlinx.kmp.util.ICalFreeBusy#ADAPTER",
    label = WireField.Label.REPEATED,
    jsonName = "freeBusy",
    schemaIndex = 7,
  )
  public val free_busy: List<ICalFreeBusy> = immutableCopyOf("free_busy", free_busy)

  @field:WireField(
    tag = 9,
    adapter = "kotlinx.kmp.util.ICalTimezone#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 8,
  )
  public val timezones: List<ICalTimezone> = immutableCopyOf("timezones", timezones)

  @field:WireField(
    tag = 17,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 16,
  )
  public val categories: List<String> = immutableCopyOf("categories", categories)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ICalendar) return false
    if (unknownFields != other.unknownFields) return false
    if (prodid != other.prodid) return false
    if (version != other.version) return false
    if (calscale != other.calscale) return false
    if (method != other.method) return false
    if (events != other.events) return false
    if (todos != other.todos) return false
    if (journals != other.journals) return false
    if (free_busy != other.free_busy) return false
    if (timezones != other.timezones) return false
    if (name != other.name) return false
    if (description != other.description) return false
    if (url != other.url) return false
    if (color != other.color) return false
    if (image != other.image) return false
    if (refresh_interval != other.refresh_interval) return false
    if (source != other.source) return false
    if (categories != other.categories) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + prodid.hashCode()
      result = result * 37 + version.hashCode()
      result = result * 37 + calscale.hashCode()
      result = result * 37 + method.hashCode()
      result = result * 37 + events.hashCode()
      result = result * 37 + todos.hashCode()
      result = result * 37 + journals.hashCode()
      result = result * 37 + free_busy.hashCode()
      result = result * 37 + timezones.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + description.hashCode()
      result = result * 37 + url.hashCode()
      result = result * 37 + color.hashCode()
      result = result * 37 + image.hashCode()
      result = result * 37 + refresh_interval.hashCode()
      result = result * 37 + source.hashCode()
      result = result * 37 + categories.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """prodid=${sanitize(prodid)}"""
    result += """version=${sanitize(version)}"""
    result += """calscale=${sanitize(calscale)}"""
    result += """method=${sanitize(method)}"""
    if (events.isNotEmpty()) result += """events=$events"""
    if (todos.isNotEmpty()) result += """todos=$todos"""
    if (journals.isNotEmpty()) result += """journals=$journals"""
    if (free_busy.isNotEmpty()) result += """free_busy=$free_busy"""
    if (timezones.isNotEmpty()) result += """timezones=$timezones"""
    result += """name=${sanitize(name)}"""
    result += """description=${sanitize(description)}"""
    result += """url=${sanitize(url)}"""
    result += """color=${sanitize(color)}"""
    result += """image=${sanitize(image)}"""
    result += """refresh_interval=${sanitize(refresh_interval)}"""
    result += """source=${sanitize(source)}"""
    if (categories.isNotEmpty()) result += """categories=${sanitize(categories)}"""
    return result.joinToString(prefix = "ICalendar{", separator = ", ", postfix = "}")
  }

  public fun copy(
    prodid: String = this.prodid,
    version: String = this.version,
    calscale: String = this.calscale,
    method: String = this.method,
    events: List<ICalEvent> = this.events,
    todos: List<ICalTodo> = this.todos,
    journals: List<ICalJournal> = this.journals,
    free_busy: List<ICalFreeBusy> = this.free_busy,
    timezones: List<ICalTimezone> = this.timezones,
    name: String = this.name,
    description: String = this.description,
    url: String = this.url,
    color: String = this.color,
    image: String = this.image,
    refresh_interval: String = this.refresh_interval,
    source: String = this.source,
    categories: List<String> = this.categories,
    unknownFields: ByteString = this.unknownFields,
  ): ICalendar = ICalendar(prodid, version, calscale, method, events, todos, journals, free_busy, timezones, name, description, url, color, image, refresh_interval, source, categories, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ICalendar> = object : ProtoAdapter<ICalendar>(
      FieldEncoding.LENGTH_DELIMITED, 
      ICalendar::class, 
      "type.googleapis.com/kotlinx.kmp.util.ICalendar", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ICalendar): Int {
        var size = value.unknownFields.size
        if (value.prodid != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.prodid)
        }
        if (value.version != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.version)
        }
        if (value.calscale != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.calscale)
        }
        if (value.method != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.method)
        }
        size += ICalEvent.ADAPTER.asRepeated().encodedSizeWithTag(5, value.events)
        size += ICalTodo.ADAPTER.asRepeated().encodedSizeWithTag(6, value.todos)
        size += ICalJournal.ADAPTER.asRepeated().encodedSizeWithTag(7, value.journals)
        size += ICalFreeBusy.ADAPTER.asRepeated().encodedSizeWithTag(8, value.free_busy)
        size += ICalTimezone.ADAPTER.asRepeated().encodedSizeWithTag(9, value.timezones)
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(10, value.name)
        }
        if (value.description != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(11, value.description)
        }
        if (value.url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(12, value.url)
        }
        if (value.color != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(13, value.color)
        }
        if (value.image != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(14, value.image)
        }
        if (value.refresh_interval != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(15, value.refresh_interval)
        }
        if (value.source != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(16, value.source)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(17, value.categories)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ICalendar) {
        if (value.prodid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.prodid)
        }
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version)
        }
        if (value.calscale != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.calscale)
        }
        if (value.method != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.method)
        }
        ICalEvent.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.events)
        ICalTodo.ADAPTER.asRepeated().encodeWithTag(writer, 6, value.todos)
        ICalJournal.ADAPTER.asRepeated().encodeWithTag(writer, 7, value.journals)
        ICalFreeBusy.ADAPTER.asRepeated().encodeWithTag(writer, 8, value.free_busy)
        ICalTimezone.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.timezones)
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.name)
        }
        if (value.description != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.description)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 12, value.url)
        }
        if (value.color != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 13, value.color)
        }
        if (value.image != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 14, value.image)
        }
        if (value.refresh_interval != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 15, value.refresh_interval)
        }
        if (value.source != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 16, value.source)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 17, value.categories)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ICalendar) {
        writer.writeBytes(value.unknownFields)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 17, value.categories)
        if (value.source != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 16, value.source)
        }
        if (value.refresh_interval != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 15, value.refresh_interval)
        }
        if (value.image != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 14, value.image)
        }
        if (value.color != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 13, value.color)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 12, value.url)
        }
        if (value.description != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.description)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 10, value.name)
        }
        ICalTimezone.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.timezones)
        ICalFreeBusy.ADAPTER.asRepeated().encodeWithTag(writer, 8, value.free_busy)
        ICalJournal.ADAPTER.asRepeated().encodeWithTag(writer, 7, value.journals)
        ICalTodo.ADAPTER.asRepeated().encodeWithTag(writer, 6, value.todos)
        ICalEvent.ADAPTER.asRepeated().encodeWithTag(writer, 5, value.events)
        if (value.method != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.method)
        }
        if (value.calscale != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.calscale)
        }
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version)
        }
        if (value.prodid != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.prodid)
        }
      }

      override fun decode(reader: ProtoReader): ICalendar {
        var prodid: String = ""
        var version: String = ""
        var calscale: String = ""
        var method: String = ""
        val events = mutableListOf<ICalEvent>()
        val todos = mutableListOf<ICalTodo>()
        val journals = mutableListOf<ICalJournal>()
        val free_busy = mutableListOf<ICalFreeBusy>()
        val timezones = mutableListOf<ICalTimezone>()
        var name: String = ""
        var description: String = ""
        var url: String = ""
        var color: String = ""
        var image: String = ""
        var refresh_interval: String = ""
        var source: String = ""
        val categories = mutableListOf<String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> prodid = ProtoAdapter.STRING.decode(reader)
            2 -> version = ProtoAdapter.STRING.decode(reader)
            3 -> calscale = ProtoAdapter.STRING.decode(reader)
            4 -> method = ProtoAdapter.STRING.decode(reader)
            5 -> events.add(ICalEvent.ADAPTER.decode(reader))
            6 -> todos.add(ICalTodo.ADAPTER.decode(reader))
            7 -> journals.add(ICalJournal.ADAPTER.decode(reader))
            8 -> free_busy.add(ICalFreeBusy.ADAPTER.decode(reader))
            9 -> timezones.add(ICalTimezone.ADAPTER.decode(reader))
            10 -> name = ProtoAdapter.STRING.decode(reader)
            11 -> description = ProtoAdapter.STRING.decode(reader)
            12 -> url = ProtoAdapter.STRING.decode(reader)
            13 -> color = ProtoAdapter.STRING.decode(reader)
            14 -> image = ProtoAdapter.STRING.decode(reader)
            15 -> refresh_interval = ProtoAdapter.STRING.decode(reader)
            16 -> source = ProtoAdapter.STRING.decode(reader)
            17 -> categories.add(ProtoAdapter.STRING.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return ICalendar(
          prodid = prodid,
          version = version,
          calscale = calscale,
          method = method,
          events = events,
          todos = todos,
          journals = journals,
          free_busy = free_busy,
          timezones = timezones,
          name = name,
          description = description,
          url = url,
          color = color,
          image = image,
          refresh_interval = refresh_interval,
          source = source,
          categories = categories,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ICalendar): ICalendar = value.copy(
        events = value.events.redactElements(ICalEvent.ADAPTER),
        todos = value.todos.redactElements(ICalTodo.ADAPTER),
        journals = value.journals.redactElements(ICalJournal.ADAPTER),
        free_busy = value.free_busy.redactElements(ICalFreeBusy.ADAPTER),
        timezones = value.timezones.redactElements(ICalTimezone.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
