// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ImageBlock in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ImageBlock(
  /**
   * Either inline base64 or a URL reference
   * image/jpeg|image/png|image/gif|image/webp
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "mediaType",
    schemaIndex = 0,
  )
  public val media_type: String = "",
  /**
   * raw bytes or base64-decoded
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "data",
    schemaIndex = 1,
  )
  public val data_: ByteString = ByteString.EMPTY,
  /**
   * alternative to data
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val url: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ImageBlock, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ImageBlock) return false
    if (unknownFields != other.unknownFields) return false
    if (media_type != other.media_type) return false
    if (data_ != other.data_) return false
    if (url != other.url) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + media_type.hashCode()
      result = result * 37 + data_.hashCode()
      result = result * 37 + url.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """media_type=${sanitize(media_type)}"""
    result += """data_=$data_"""
    result += """url=${sanitize(url)}"""
    return result.joinToString(prefix = "ImageBlock{", separator = ", ", postfix = "}")
  }

  public fun copy(
    media_type: String = this.media_type,
    data_: ByteString = this.data_,
    url: String = this.url,
    unknownFields: ByteString = this.unknownFields,
  ): ImageBlock = ImageBlock(media_type, data_, url, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ImageBlock> = object : ProtoAdapter<ImageBlock>(
      FieldEncoding.LENGTH_DELIMITED, 
      ImageBlock::class, 
      "type.googleapis.com/kotlinx.kmp.util.ImageBlock", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ImageBlock): Int {
        var size = value.unknownFields.size
        if (value.media_type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.media_type)
        }
        if (value.data_ != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(2, value.data_)
        }
        if (value.url != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.url)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ImageBlock) {
        if (value.media_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_type)
        }
        if (value.data_ != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.data_)
        }
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.url)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ImageBlock) {
        writer.writeBytes(value.unknownFields)
        if (value.url != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.url)
        }
        if (value.data_ != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 2, value.data_)
        }
        if (value.media_type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.media_type)
        }
      }

      override fun decode(reader: ProtoReader): ImageBlock {
        var media_type: String = ""
        var data_: ByteString = ByteString.EMPTY
        var url: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> media_type = ProtoAdapter.STRING.decode(reader)
            2 -> data_ = ProtoAdapter.BYTES.decode(reader)
            3 -> url = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ImageBlock(
          media_type = media_type,
          data_ = data_,
          url = url,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ImageBlock): ImageBlock = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
