// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.LlmRequest in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import kotlin.collections.Map
import kotlin.lazy
import okio.ByteString

/**
 * LLM request envelope — provider-agnostic.
 */
public class LlmRequest(
  /**
   * claude-sonnet-4-6|gemini-2.0-flash|gpt-4o|...
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val model: String = "",
  messages: List<ChatMessage> = emptyList(),
  /**
   * system prompt (optional)
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val system: String = "",
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "maxTokens",
    schemaIndex = 3,
  )
  public val max_tokens: Int = 0,
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 4,
  )
  public val temperature: Double = 0.0,
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "topP",
    schemaIndex = 5,
  )
  public val top_p: Double = 0.0,
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "topK",
    schemaIndex = 6,
  )
  public val top_k: Int = 0,
  stop_sequences: List<String> = emptyList(),
  tools: List<Tool> = emptyList(),
  @field:WireField(
    tag = 10,
    adapter = "kotlinx.kmp.util.ToolChoice#ADAPTER",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "toolChoice",
    schemaIndex = 9,
  )
  public val tool_choice: ToolChoice? = null,
  /**
   * SSE streaming
   */
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val stream: Boolean = false,
  metadata: Map<String, String> = emptyMap(),
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LlmRequest, Nothing>(ADAPTER, unknownFields) {
  @field:WireField(
    tag = 2,
    adapter = "kotlinx.kmp.util.ChatMessage#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val messages: List<ChatMessage> = immutableCopyOf("messages", messages)

  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "stopSequences",
    schemaIndex = 7,
  )
  public val stop_sequences: List<String> = immutableCopyOf("stop_sequences", stop_sequences)

  /**
   * available tools
   */
  @field:WireField(
    tag = 9,
    adapter = "kotlinx.kmp.util.Tool#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 8,
  )
  public val tools: List<Tool> = immutableCopyOf("tools", tools)

  /**
   * provider-specific extras (user_id, etc.)
   */
  @field:WireField(
    tag = 12,
    keyAdapter = "com.squareup.wire.ProtoAdapter#STRING",
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    schemaIndex = 11,
  )
  public val metadata: Map<String, String> = immutableCopyOf("metadata", metadata)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LlmRequest) return false
    if (unknownFields != other.unknownFields) return false
    if (model != other.model) return false
    if (messages != other.messages) return false
    if (system != other.system) return false
    if (max_tokens != other.max_tokens) return false
    if (temperature != other.temperature) return false
    if (top_p != other.top_p) return false
    if (top_k != other.top_k) return false
    if (stop_sequences != other.stop_sequences) return false
    if (tools != other.tools) return false
    if (tool_choice != other.tool_choice) return false
    if (stream != other.stream) return false
    if (metadata != other.metadata) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + model.hashCode()
      result = result * 37 + messages.hashCode()
      result = result * 37 + system.hashCode()
      result = result * 37 + max_tokens.hashCode()
      result = result * 37 + temperature.hashCode()
      result = result * 37 + top_p.hashCode()
      result = result * 37 + top_k.hashCode()
      result = result * 37 + stop_sequences.hashCode()
      result = result * 37 + tools.hashCode()
      result = result * 37 + (tool_choice?.hashCode() ?: 0)
      result = result * 37 + stream.hashCode()
      result = result * 37 + metadata.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """model=${sanitize(model)}"""
    if (messages.isNotEmpty()) result += """messages=$messages"""
    result += """system=${sanitize(system)}"""
    result += """max_tokens=$max_tokens"""
    result += """temperature=$temperature"""
    result += """top_p=$top_p"""
    result += """top_k=$top_k"""
    if (stop_sequences.isNotEmpty()) result += """stop_sequences=${sanitize(stop_sequences)}"""
    if (tools.isNotEmpty()) result += """tools=$tools"""
    if (tool_choice != null) result += """tool_choice=$tool_choice"""
    result += """stream=$stream"""
    if (metadata.isNotEmpty()) result += """metadata=$metadata"""
    return result.joinToString(prefix = "LlmRequest{", separator = ", ", postfix = "}")
  }

  public fun copy(
    model: String = this.model,
    messages: List<ChatMessage> = this.messages,
    system: String = this.system,
    max_tokens: Int = this.max_tokens,
    temperature: Double = this.temperature,
    top_p: Double = this.top_p,
    top_k: Int = this.top_k,
    stop_sequences: List<String> = this.stop_sequences,
    tools: List<Tool> = this.tools,
    tool_choice: ToolChoice? = this.tool_choice,
    stream: Boolean = this.stream,
    metadata: Map<String, String> = this.metadata,
    unknownFields: ByteString = this.unknownFields,
  ): LlmRequest = LlmRequest(model, messages, system, max_tokens, temperature, top_p, top_k, stop_sequences, tools, tool_choice, stream, metadata, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LlmRequest> = object : ProtoAdapter<LlmRequest>(
      FieldEncoding.LENGTH_DELIMITED, 
      LlmRequest::class, 
      "type.googleapis.com/kotlinx.kmp.util.LlmRequest", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      private val metadataAdapter: ProtoAdapter<Map<String, String>> by
          lazy { ProtoAdapter.newMapAdapter(ProtoAdapter.STRING, ProtoAdapter.STRING) }

      override fun encodedSize(`value`: LlmRequest): Int {
        var size = value.unknownFields.size
        if (value.model != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.model)
        }
        size += ChatMessage.ADAPTER.asRepeated().encodedSizeWithTag(2, value.messages)
        if (value.system != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.system)
        }
        if (value.max_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.max_tokens)
        }
        if (!value.temperature.equals(0.0)) {
          size += ProtoAdapter.DOUBLE.encodedSizeWithTag(5, value.temperature)
        }
        if (!value.top_p.equals(0.0)) {
          size += ProtoAdapter.DOUBLE.encodedSizeWithTag(6, value.top_p)
        }
        if (value.top_k != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(7, value.top_k)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(8, value.stop_sequences)
        size += Tool.ADAPTER.asRepeated().encodedSizeWithTag(9, value.tools)
        if (value.tool_choice != null) {
          size += ToolChoice.ADAPTER.encodedSizeWithTag(10, value.tool_choice)
        }
        if (value.stream != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(11, value.stream)
        }
        size += metadataAdapter.encodedSizeWithTag(12, value.metadata)
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LlmRequest) {
        if (value.model != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.model)
        }
        ChatMessage.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.messages)
        if (value.system != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.system)
        }
        if (value.max_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.max_tokens)
        }
        if (!value.temperature.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 5, value.temperature)
        }
        if (!value.top_p.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 6, value.top_p)
        }
        if (value.top_k != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 7, value.top_k)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 8, value.stop_sequences)
        Tool.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.tools)
        if (value.tool_choice != null) {
          ToolChoice.ADAPTER.encodeWithTag(writer, 10, value.tool_choice)
        }
        if (value.stream != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 11, value.stream)
        }
        metadataAdapter.encodeWithTag(writer, 12, value.metadata)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LlmRequest) {
        writer.writeBytes(value.unknownFields)
        metadataAdapter.encodeWithTag(writer, 12, value.metadata)
        if (value.stream != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 11, value.stream)
        }
        if (value.tool_choice != null) {
          ToolChoice.ADAPTER.encodeWithTag(writer, 10, value.tool_choice)
        }
        Tool.ADAPTER.asRepeated().encodeWithTag(writer, 9, value.tools)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 8, value.stop_sequences)
        if (value.top_k != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 7, value.top_k)
        }
        if (!value.top_p.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 6, value.top_p)
        }
        if (!value.temperature.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 5, value.temperature)
        }
        if (value.max_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.max_tokens)
        }
        if (value.system != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.system)
        }
        ChatMessage.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.messages)
        if (value.model != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.model)
        }
      }

      override fun decode(reader: ProtoReader): LlmRequest {
        var model: String = ""
        val messages = mutableListOf<ChatMessage>()
        var system: String = ""
        var max_tokens: Int = 0
        var temperature: Double = 0.0
        var top_p: Double = 0.0
        var top_k: Int = 0
        val stop_sequences = mutableListOf<String>()
        val tools = mutableListOf<Tool>()
        var tool_choice: ToolChoice? = null
        var stream: Boolean = false
        val metadata = mutableMapOf<String, String>()
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> model = ProtoAdapter.STRING.decode(reader)
            2 -> messages.add(ChatMessage.ADAPTER.decode(reader))
            3 -> system = ProtoAdapter.STRING.decode(reader)
            4 -> max_tokens = ProtoAdapter.INT32.decode(reader)
            5 -> temperature = ProtoAdapter.DOUBLE.decode(reader)
            6 -> top_p = ProtoAdapter.DOUBLE.decode(reader)
            7 -> top_k = ProtoAdapter.INT32.decode(reader)
            8 -> stop_sequences.add(ProtoAdapter.STRING.decode(reader))
            9 -> tools.add(Tool.ADAPTER.decode(reader))
            10 -> tool_choice = ToolChoice.ADAPTER.decode(reader)
            11 -> stream = ProtoAdapter.BOOL.decode(reader)
            12 -> metadata.putAll(metadataAdapter.decode(reader))
            else -> reader.readUnknownField(tag)
          }
        }
        return LlmRequest(
          model = model,
          messages = messages,
          system = system,
          max_tokens = max_tokens,
          temperature = temperature,
          top_p = top_p,
          top_k = top_k,
          stop_sequences = stop_sequences,
          tools = tools,
          tool_choice = tool_choice,
          stream = stream,
          metadata = metadata,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LlmRequest): LlmRequest = value.copy(
        messages = value.messages.redactElements(ChatMessage.ADAPTER),
        tools = value.tools.redactElements(Tool.ADAPTER),
        tool_choice = value.tool_choice?.let(ToolChoice.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
