// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.PatchOperation in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * JSON Patch operation (RFC 6902)
 */
public class PatchOperation(
  /**
   * add/remove/replace/move/copy/test
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val op: String = "",
  /**
   * JSON Pointer (RFC 6901)
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val path: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    declaredName = "value",
    schemaIndex = 2,
  )
  public val value_: String = "",
  /**
   * for move/copy
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val from: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PatchOperation, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PatchOperation) return false
    if (unknownFields != other.unknownFields) return false
    if (op != other.op) return false
    if (path != other.path) return false
    if (value_ != other.value_) return false
    if (from != other.from) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + op.hashCode()
      result = result * 37 + path.hashCode()
      result = result * 37 + value_.hashCode()
      result = result * 37 + from.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """op=${sanitize(op)}"""
    result += """path=${sanitize(path)}"""
    result += """value_=${sanitize(value_)}"""
    result += """from=${sanitize(from)}"""
    return result.joinToString(prefix = "PatchOperation{", separator = ", ", postfix = "}")
  }

  public fun copy(
    op: String = this.op,
    path: String = this.path,
    value_: String = this.value_,
    from: String = this.from,
    unknownFields: ByteString = this.unknownFields,
  ): PatchOperation = PatchOperation(op, path, value_, from, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PatchOperation> = object : ProtoAdapter<PatchOperation>(
      FieldEncoding.LENGTH_DELIMITED, 
      PatchOperation::class, 
      "type.googleapis.com/kotlinx.kmp.util.PatchOperation", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: PatchOperation): Int {
        var size = value.unknownFields.size
        if (value.op != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.op)
        }
        if (value.path != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.path)
        }
        if (value.value_ != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.value_)
        }
        if (value.from != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.from)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PatchOperation) {
        if (value.op != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.op)
        }
        if (value.path != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.path)
        }
        if (value.value_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.value_)
        }
        if (value.from != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.from)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PatchOperation) {
        writer.writeBytes(value.unknownFields)
        if (value.from != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.from)
        }
        if (value.value_ != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.value_)
        }
        if (value.path != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.path)
        }
        if (value.op != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.op)
        }
      }

      override fun decode(reader: ProtoReader): PatchOperation {
        var op: String = ""
        var path: String = ""
        var value_: String = ""
        var from: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> op = ProtoAdapter.STRING.decode(reader)
            2 -> path = ProtoAdapter.STRING.decode(reader)
            3 -> value_ = ProtoAdapter.STRING.decode(reader)
            4 -> from = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PatchOperation(
          op = op,
          path = path,
          value_ = value_,
          from = from,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PatchOperation): PatchOperation = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
