// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.PingEvent in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class PingEvent(
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PingEvent, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PingEvent) return false
    if (unknownFields != other.unknownFields) return false
    return true
  }

  override fun hashCode(): Int = unknownFields.hashCode()

  override fun toString(): String = "PingEvent{}"

  public fun copy(unknownFields: ByteString = this.unknownFields): PingEvent = PingEvent(unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PingEvent> = object : ProtoAdapter<PingEvent>(
      FieldEncoding.LENGTH_DELIMITED, 
      PingEvent::class, 
      "type.googleapis.com/kotlinx.kmp.util.PingEvent", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: PingEvent): Int {
        var size = value.unknownFields.size
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PingEvent) {
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PingEvent) {
        writer.writeBytes(value.unknownFields)
      }

      override fun decode(reader: ProtoReader): PingEvent {
        val unknownFields = reader.forEachTag(reader::readUnknownField)
        return PingEvent(
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PingEvent): PingEvent = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
