// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ThinkingBlock in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ThinkingBlock(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val thinking: String = "",
  /**
   * for verification (Claude)
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val signature: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ThinkingBlock, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ThinkingBlock) return false
    if (unknownFields != other.unknownFields) return false
    if (thinking != other.thinking) return false
    if (signature != other.signature) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + thinking.hashCode()
      result = result * 37 + signature.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """thinking=${sanitize(thinking)}"""
    result += """signature=${sanitize(signature)}"""
    return result.joinToString(prefix = "ThinkingBlock{", separator = ", ", postfix = "}")
  }

  public fun copy(
    thinking: String = this.thinking,
    signature: String = this.signature,
    unknownFields: ByteString = this.unknownFields,
  ): ThinkingBlock = ThinkingBlock(thinking, signature, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ThinkingBlock> = object : ProtoAdapter<ThinkingBlock>(
      FieldEncoding.LENGTH_DELIMITED, 
      ThinkingBlock::class, 
      "type.googleapis.com/kotlinx.kmp.util.ThinkingBlock", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ThinkingBlock): Int {
        var size = value.unknownFields.size
        if (value.thinking != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.thinking)
        }
        if (value.signature != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.signature)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ThinkingBlock) {
        if (value.thinking != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.thinking)
        }
        if (value.signature != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.signature)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ThinkingBlock) {
        writer.writeBytes(value.unknownFields)
        if (value.signature != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.signature)
        }
        if (value.thinking != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.thinking)
        }
      }

      override fun decode(reader: ProtoReader): ThinkingBlock {
        var thinking: String = ""
        var signature: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> thinking = ProtoAdapter.STRING.decode(reader)
            2 -> signature = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ThinkingBlock(
          thinking = thinking,
          signature = signature,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ThinkingBlock): ThinkingBlock = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
