// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ToolResultBlock in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.redactElements
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

public class ToolResultBlock(
  /**
   * matches ToolUseBlock.id
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "toolUseId",
    schemaIndex = 0,
  )
  public val tool_use_id: String = "",
  content: List<ContentBlock> = emptyList(),
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "isError",
    schemaIndex = 2,
  )
  public val is_error: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ToolResultBlock, Nothing>(ADAPTER, unknownFields) {
  /**
   * result (text or structured)
   */
  @field:WireField(
    tag = 2,
    adapter = "kotlinx.kmp.util.ContentBlock#ADAPTER",
    label = WireField.Label.REPEATED,
    schemaIndex = 1,
  )
  public val content: List<ContentBlock> = immutableCopyOf("content", content)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ToolResultBlock) return false
    if (unknownFields != other.unknownFields) return false
    if (tool_use_id != other.tool_use_id) return false
    if (content != other.content) return false
    if (is_error != other.is_error) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + tool_use_id.hashCode()
      result = result * 37 + content.hashCode()
      result = result * 37 + is_error.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """tool_use_id=${sanitize(tool_use_id)}"""
    if (content.isNotEmpty()) result += """content=$content"""
    result += """is_error=$is_error"""
    return result.joinToString(prefix = "ToolResultBlock{", separator = ", ", postfix = "}")
  }

  public fun copy(
    tool_use_id: String = this.tool_use_id,
    content: List<ContentBlock> = this.content,
    is_error: Boolean = this.is_error,
    unknownFields: ByteString = this.unknownFields,
  ): ToolResultBlock = ToolResultBlock(tool_use_id, content, is_error, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ToolResultBlock> = object : ProtoAdapter<ToolResultBlock>(
      FieldEncoding.LENGTH_DELIMITED, 
      ToolResultBlock::class, 
      "type.googleapis.com/kotlinx.kmp.util.ToolResultBlock", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ToolResultBlock): Int {
        var size = value.unknownFields.size
        if (value.tool_use_id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.tool_use_id)
        }
        size += ContentBlock.ADAPTER.asRepeated().encodedSizeWithTag(2, value.content)
        if (value.is_error != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.is_error)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ToolResultBlock) {
        if (value.tool_use_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.tool_use_id)
        }
        ContentBlock.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.content)
        if (value.is_error != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.is_error)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ToolResultBlock) {
        writer.writeBytes(value.unknownFields)
        if (value.is_error != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.is_error)
        }
        ContentBlock.ADAPTER.asRepeated().encodeWithTag(writer, 2, value.content)
        if (value.tool_use_id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.tool_use_id)
        }
      }

      override fun decode(reader: ProtoReader): ToolResultBlock {
        var tool_use_id: String = ""
        val content = mutableListOf<ContentBlock>()
        var is_error: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> tool_use_id = ProtoAdapter.STRING.decode(reader)
            2 -> content.add(ContentBlock.ADAPTER.decode(reader))
            3 -> is_error = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ToolResultBlock(
          tool_use_id = tool_use_id,
          content = content,
          is_error = is_error,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ToolResultBlock): ToolResultBlock = value.copy(
        content = value.content.redactElements(ContentBlock.ADAPTER),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
