// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ToolUseBlock in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ToolUseBlock(
  /**
   * unique per message
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  /**
   * tool name
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val name: String = "",
  /**
   * JSON-encoded tool input
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BYTES",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val input: ByteString = ByteString.EMPTY,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ToolUseBlock, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ToolUseBlock) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (name != other.name) return false
    if (input != other.input) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + input.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    result += """name=${sanitize(name)}"""
    result += """input=$input"""
    return result.joinToString(prefix = "ToolUseBlock{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    name: String = this.name,
    input: ByteString = this.input,
    unknownFields: ByteString = this.unknownFields,
  ): ToolUseBlock = ToolUseBlock(id, name, input, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ToolUseBlock> = object : ProtoAdapter<ToolUseBlock>(
      FieldEncoding.LENGTH_DELIMITED, 
      ToolUseBlock::class, 
      "type.googleapis.com/kotlinx.kmp.util.ToolUseBlock", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ToolUseBlock): Int {
        var size = value.unknownFields.size
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name)
        }
        if (value.input != okio.ByteString.EMPTY) {
          size += ProtoAdapter.BYTES.encodedSizeWithTag(3, value.input)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ToolUseBlock) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        if (value.input != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.input)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ToolUseBlock) {
        writer.writeBytes(value.unknownFields)
        if (value.input != okio.ByteString.EMPTY) {
          ProtoAdapter.BYTES.encodeWithTag(writer, 3, value.input)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): ToolUseBlock {
        var id: String = ""
        var name: String = ""
        var input: ByteString = ByteString.EMPTY
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> name = ProtoAdapter.STRING.decode(reader)
            3 -> input = ProtoAdapter.BYTES.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ToolUseBlock(
          id = id,
          name = name,
          input = input,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ToolUseBlock): ToolUseBlock = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
