// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.ToolChoice in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

public class ToolChoice(
  /**
   * any|auto|none|tool (with specific name)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val type: String = "",
  /**
   * when type=tool
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val name: String = "",
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#BOOL",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "disableParallelToolUse",
    schemaIndex = 2,
  )
  public val disable_parallel_tool_use: Boolean = false,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<ToolChoice, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is ToolChoice) return false
    if (unknownFields != other.unknownFields) return false
    if (type != other.type) return false
    if (name != other.name) return false
    if (disable_parallel_tool_use != other.disable_parallel_tool_use) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + type.hashCode()
      result = result * 37 + name.hashCode()
      result = result * 37 + disable_parallel_tool_use.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """type=${sanitize(type)}"""
    result += """name=${sanitize(name)}"""
    result += """disable_parallel_tool_use=$disable_parallel_tool_use"""
    return result.joinToString(prefix = "ToolChoice{", separator = ", ", postfix = "}")
  }

  public fun copy(
    type: String = this.type,
    name: String = this.name,
    disable_parallel_tool_use: Boolean = this.disable_parallel_tool_use,
    unknownFields: ByteString = this.unknownFields,
  ): ToolChoice = ToolChoice(type, name, disable_parallel_tool_use, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<ToolChoice> = object : ProtoAdapter<ToolChoice>(
      FieldEncoding.LENGTH_DELIMITED, 
      ToolChoice::class, 
      "type.googleapis.com/kotlinx.kmp.util.ToolChoice", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: ToolChoice): Int {
        var size = value.unknownFields.size
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.type)
        }
        if (value.name != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.name)
        }
        if (value.disable_parallel_tool_use != false) {
          size += ProtoAdapter.BOOL.encodedSizeWithTag(3, value.disable_parallel_tool_use)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: ToolChoice) {
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        if (value.disable_parallel_tool_use != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.disable_parallel_tool_use)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: ToolChoice) {
        writer.writeBytes(value.unknownFields)
        if (value.disable_parallel_tool_use != false) {
          ProtoAdapter.BOOL.encodeWithTag(writer, 3, value.disable_parallel_tool_use)
        }
        if (value.name != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.name)
        }
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.type)
        }
      }

      override fun decode(reader: ProtoReader): ToolChoice {
        var type: String = ""
        var name: String = ""
        var disable_parallel_tool_use: Boolean = false
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> type = ProtoAdapter.STRING.decode(reader)
            2 -> name = ProtoAdapter.STRING.decode(reader)
            3 -> disable_parallel_tool_use = ProtoAdapter.BOOL.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return ToolChoice(
          type = type,
          name = name,
          disable_parallel_tool_use = disable_parallel_tool_use,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: ToolChoice): ToolChoice = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
