// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.Usage in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Token usage — all vendors report input/output counts, some report cache hits.
 */
public class Usage(
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "inputTokens",
    schemaIndex = 0,
  )
  public val input_tokens: Int = 0,
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "outputTokens",
    schemaIndex = 1,
  )
  public val output_tokens: Int = 0,
  /**
   * Anthropic cache
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "cacheCreationInputTokens",
    schemaIndex = 2,
  )
  public val cache_creation_input_tokens: Int = 0,
  /**
   * Anthropic cache
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "cacheReadInputTokens",
    schemaIndex = 3,
  )
  public val cache_read_input_tokens: Int = 0,
  /**
   * OpenAI o1 reasoning
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "reasoningTokens",
    schemaIndex = 4,
  )
  public val reasoning_tokens: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Usage, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Usage) return false
    if (unknownFields != other.unknownFields) return false
    if (input_tokens != other.input_tokens) return false
    if (output_tokens != other.output_tokens) return false
    if (cache_creation_input_tokens != other.cache_creation_input_tokens) return false
    if (cache_read_input_tokens != other.cache_read_input_tokens) return false
    if (reasoning_tokens != other.reasoning_tokens) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + input_tokens.hashCode()
      result = result * 37 + output_tokens.hashCode()
      result = result * 37 + cache_creation_input_tokens.hashCode()
      result = result * 37 + cache_read_input_tokens.hashCode()
      result = result * 37 + reasoning_tokens.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """input_tokens=$input_tokens"""
    result += """output_tokens=$output_tokens"""
    result += """cache_creation_input_tokens=$cache_creation_input_tokens"""
    result += """cache_read_input_tokens=$cache_read_input_tokens"""
    result += """reasoning_tokens=$reasoning_tokens"""
    return result.joinToString(prefix = "Usage{", separator = ", ", postfix = "}")
  }

  public fun copy(
    input_tokens: Int = this.input_tokens,
    output_tokens: Int = this.output_tokens,
    cache_creation_input_tokens: Int = this.cache_creation_input_tokens,
    cache_read_input_tokens: Int = this.cache_read_input_tokens,
    reasoning_tokens: Int = this.reasoning_tokens,
    unknownFields: ByteString = this.unknownFields,
  ): Usage = Usage(input_tokens, output_tokens, cache_creation_input_tokens, cache_read_input_tokens, reasoning_tokens, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Usage> = object : ProtoAdapter<Usage>(
      FieldEncoding.LENGTH_DELIMITED, 
      Usage::class, 
      "type.googleapis.com/kotlinx.kmp.util.Usage", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: Usage): Int {
        var size = value.unknownFields.size
        if (value.input_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.input_tokens)
        }
        if (value.output_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.output_tokens)
        }
        if (value.cache_creation_input_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.cache_creation_input_tokens)
        }
        if (value.cache_read_input_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.cache_read_input_tokens)
        }
        if (value.reasoning_tokens != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(5, value.reasoning_tokens)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Usage) {
        if (value.input_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.input_tokens)
        }
        if (value.output_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.output_tokens)
        }
        if (value.cache_creation_input_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.cache_creation_input_tokens)
        }
        if (value.cache_read_input_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.cache_read_input_tokens)
        }
        if (value.reasoning_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.reasoning_tokens)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Usage) {
        writer.writeBytes(value.unknownFields)
        if (value.reasoning_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 5, value.reasoning_tokens)
        }
        if (value.cache_read_input_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.cache_read_input_tokens)
        }
        if (value.cache_creation_input_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.cache_creation_input_tokens)
        }
        if (value.output_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.output_tokens)
        }
        if (value.input_tokens != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.input_tokens)
        }
      }

      override fun decode(reader: ProtoReader): Usage {
        var input_tokens: Int = 0
        var output_tokens: Int = 0
        var cache_creation_input_tokens: Int = 0
        var cache_read_input_tokens: Int = 0
        var reasoning_tokens: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> input_tokens = ProtoAdapter.INT32.decode(reader)
            2 -> output_tokens = ProtoAdapter.INT32.decode(reader)
            3 -> cache_creation_input_tokens = ProtoAdapter.INT32.decode(reader)
            4 -> cache_read_input_tokens = ProtoAdapter.INT32.decode(reader)
            5 -> reasoning_tokens = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Usage(
          input_tokens = input_tokens,
          output_tokens = output_tokens,
          cache_creation_input_tokens = cache_creation_input_tokens,
          cache_read_input_tokens = cache_read_input_tokens,
          reasoning_tokens = reasoning_tokens,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Usage): Usage = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
