// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.VCardRelated in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * RFC 6350 §6.6.6 RELATED property
 */
public class VCardRelated(
  /**
   * URI or text (other vCard UID)
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val uri: String = "",
  /**
   * contact/acquaintance/friend/met/
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val type: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<VCardRelated, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is VCardRelated) return false
    if (unknownFields != other.unknownFields) return false
    if (uri != other.uri) return false
    if (type != other.type) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + uri.hashCode()
      result = result * 37 + type.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """uri=${sanitize(uri)}"""
    result += """type=${sanitize(type)}"""
    return result.joinToString(prefix = "VCardRelated{", separator = ", ", postfix = "}")
  }

  public fun copy(
    uri: String = this.uri,
    type: String = this.type,
    unknownFields: ByteString = this.unknownFields,
  ): VCardRelated = VCardRelated(uri, type, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<VCardRelated> = object : ProtoAdapter<VCardRelated>(
      FieldEncoding.LENGTH_DELIMITED, 
      VCardRelated::class, 
      "type.googleapis.com/kotlinx.kmp.util.VCardRelated", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: VCardRelated): Int {
        var size = value.unknownFields.size
        if (value.uri != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.uri)
        }
        if (value.type != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.type)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: VCardRelated) {
        if (value.uri != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uri)
        }
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.type)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: VCardRelated) {
        writer.writeBytes(value.unknownFields)
        if (value.type != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.type)
        }
        if (value.uri != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.uri)
        }
      }

      override fun decode(reader: ProtoReader): VCardRelated {
        var uri: String = ""
        var type: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> uri = ProtoAdapter.STRING.decode(reader)
            2 -> type = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return VCardRelated(
          uri = uri,
          type = type,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: VCardRelated): VCardRelated = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
