// Code generated by Wire protocol buffer compiler, do not edit.
// Source: kotlinx.kmp.util.VCardClientPidMap in types.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package kotlinx.kmp.util

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * RFC 6350 §6.7.7 CLIENTPIDMAP property
 */
public class VCardClientPidMap(
  /**
   * source identifier
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val pid: Int = 0,
  /**
   * globally unique URI
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val uri: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<VCardClientPidMap, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is VCardClientPidMap) return false
    if (unknownFields != other.unknownFields) return false
    if (pid != other.pid) return false
    if (uri != other.uri) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + pid.hashCode()
      result = result * 37 + uri.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """pid=$pid"""
    result += """uri=${sanitize(uri)}"""
    return result.joinToString(prefix = "VCardClientPidMap{", separator = ", ", postfix = "}")
  }

  public fun copy(
    pid: Int = this.pid,
    uri: String = this.uri,
    unknownFields: ByteString = this.unknownFields,
  ): VCardClientPidMap = VCardClientPidMap(pid, uri, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<VCardClientPidMap> = object : ProtoAdapter<VCardClientPidMap>(
      FieldEncoding.LENGTH_DELIMITED, 
      VCardClientPidMap::class, 
      "type.googleapis.com/kotlinx.kmp.util.VCardClientPidMap", 
      PROTO_3, 
      null, 
      "types.proto"
    ) {
      override fun encodedSize(`value`: VCardClientPidMap): Int {
        var size = value.unknownFields.size
        if (value.pid != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.pid)
        }
        if (value.uri != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.uri)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: VCardClientPidMap) {
        if (value.pid != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.pid)
        }
        if (value.uri != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.uri)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: VCardClientPidMap) {
        writer.writeBytes(value.unknownFields)
        if (value.uri != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.uri)
        }
        if (value.pid != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.pid)
        }
      }

      override fun decode(reader: ProtoReader): VCardClientPidMap {
        var pid: Int = 0
        var uri: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> pid = ProtoAdapter.INT32.decode(reader)
            2 -> uri = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return VCardClientPidMap(
          pid = pid,
          uri = uri,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: VCardClientPidMap): VCardClientPidMap = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
