// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.CalendarPeriod in google/type/calendar_period.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.EnumAdapter
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireEnum
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.JvmStatic
import kotlin.Int
import kotlin.Suppress

/**
 * A `CalendarPeriod` represents the abstract concept of a time period that has
 * a canonical start. Grammatically, "the start of the current
 * `CalendarPeriod`." All calendar times begin at midnight UTC.
 */
public enum class CalendarPeriod(
  override val `value`: Int,
) : WireEnum {
  /**
   * Undefined period, raises an error.
   */
  CALENDAR_PERIOD_UNSPECIFIED(0),
  /**
   * A day.
   */
  DAY(1),
  /**
   * A week. Weeks begin on Monday, following
   * \[ISO 8601\](https://en.wikipedia.org/wiki/ISO_week_date).
   */
  WEEK(2),
  /**
   * A fortnight. The first calendar fortnight of the year begins at the start
   * of week 1 according to
   * \[ISO 8601\](https://en.wikipedia.org/wiki/ISO_week_date).
   */
  FORTNIGHT(3),
  /**
   * A month.
   */
  MONTH(4),
  /**
   * A quarter. Quarters start on dates 1-Jan, 1-Apr, 1-Jul, and 1-Oct of each
   * year.
   */
  QUARTER(5),
  /**
   * A half-year. Half-years start on dates 1-Jan and 1-Jul.
   */
  HALF(6),
  /**
   * A year.
   */
  YEAR(7),
  ;

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<CalendarPeriod> = object : EnumAdapter<CalendarPeriod>(
      CalendarPeriod::class, 
      PROTO_3, 
      CalendarPeriod.CALENDAR_PERIOD_UNSPECIFIED
    ) {
      override fun fromValue(`value`: Int): CalendarPeriod? = CalendarPeriod.fromValue(`value`)
    }

    @JvmStatic
    public fun fromValue(`value`: Int): CalendarPeriod? = when (`value`) {
      0 -> CALENDAR_PERIOD_UNSPECIFIED
      1 -> DAY
      2 -> WEEK
      3 -> FORTNIGHT
      4 -> MONTH
      5 -> QUARTER
      6 -> HALF
      7 -> YEAR
      else -> null
    }
  }
}
