// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.Color in google/type/color.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Float
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Represents a color in the RGBA color space. This representation is designed
 * for simplicity of conversion to and from color representations in various
 * languages over compactness. For example, the fields of this representation
 * can be trivially provided to the constructor of `java.awt.Color` in Java; it
 * can also be trivially provided to UIColor's `+colorWithRed:green:blue:alpha`
 * method in iOS; and, with just a little work, it can be easily formatted into
 * a CSS `rgba()` string in JavaScript.
 *
 * This reference page doesn't have information about the absolute color
 * space that should be used to interpret the RGB value—for example, sRGB,
 * Adobe RGB,
 * DCI-P3, and BT.2020. By default, applications should assume the sRGB color
 * space.
 *
 * When color equality needs to be decided, implementations, unless documented
 * otherwise, treat two colors as equal if all their red, green, blue, and alpha
 * values each differ by at most `1e-5`.
 *
 * Example (Java):
 *
 *      import com.google.type.Color;
 *
 *      // ...
 *      public static java.awt.Color fromProto(Color protocolor) {
 *        float alpha = protocolor.hasAlpha()
 *            ? protocolor.getAlpha().getValue()
 *            : 1.0;
 *
 *        return new java.awt.Color(
 *            protocolor.getRed(),
 *            protocolor.getGreen(),
 *            protocolor.getBlue(),
 *            alpha);
 *      }
 *
 *      public static Color toProto(java.awt.Color color) {
 *        float red = (float) color.getRed();
 *        float green = (float) color.getGreen();
 *        float blue = (float) color.getBlue();
 *        float denominator = 255.0;
 *        Color.Builder resultBuilder =
 *            Color
 *                .newBuilder()
 *                .setRed(red / denominator)
 *                .setGreen(green / denominator)
 *                .setBlue(blue / denominator);
 *        int alpha = color.getAlpha();
 *        if (alpha != 255) {
 *          result.setAlpha(
 *              FloatValue
 *                  .newBuilder()
 *                  .setValue(((float) alpha) / denominator)
 *                  .build());
 *        }
 *        return resultBuilder.build();
 *      }
 *      // ...
 *
 * Example (iOS / Obj-C):
 *
 *      // ...
 *      static UIColor* fromProto(Color* protocolor) {
 *         float red = \[protocolor red\];
 *         float green = \[protocolor green\];
 *         float blue = \[protocolor blue\];
 *         FloatValue* alpha_wrapper = \[protocolor alpha\];
 *         float alpha = 1.0;
 *         if (alpha_wrapper != nil) {
 *           alpha = \[alpha_wrapper value\];
 *         }
 *         return \[UIColor colorWithRed:red green:green blue:blue alpha:alpha\];
 *      }
 *
 *      static Color* toProto(UIColor* color) {
 *          CGFloat red, green, blue, alpha;
 *          if (!\[color getRed:&red green:&green blue:&blue alpha:&alpha\]) {
 *            return nil;
 *          }
 *          Color* result = \[\[Color alloc\] init\];
 *          \[result setRed:red\];
 *          \[result setGreen:green\];
 *          \[result setBlue:blue\];
 *          if (alpha <= 0.9999) {
 *            \[result setAlpha:floatWrapperWithValue(alpha)\];
 *          }
 *          \[result autorelease\];
 *          return result;
 *     }
 *     // ...
 *
 *  Example (JavaScript):
 *
 *     // ...
 *
 *     var protoToCssColor = function(rgb_color) {
 *        var redFrac = rgb_color.red || 0.0;
 *        var greenFrac = rgb_color.green || 0.0;
 *        var blueFrac = rgb_color.blue || 0.0;
 *        var red = Math.floor(redFrac * 255);
 *        var green = Math.floor(greenFrac * 255);
 *        var blue = Math.floor(blueFrac * 255);
 *
 *        if (!('alpha' in rgb_color)) {
 *           return rgbToCssColor(red, green, blue);
 *        }
 *
 *        var alphaFrac = rgb_color.alpha.value || 0.0;
 *        var rgbParams = \[red, green, blue\].join(',');
 *        return \['rgba(', rgbParams, ',', alphaFrac, ')'\].join('');
 *     };
 *
 *     var rgbToCssColor = function(red, green, blue) {
 *       var rgbNumber = new Number((red << 16) | (green << 8) | blue);
 *       var hexString = rgbNumber.toString(16);
 *       var missingZeros = 6 - hexString.length;
 *       var resultBuilder = \['#'\];
 *       for (var i = 0; i < missingZeros; i++) {
 *          resultBuilder.push('0');
 *       }
 *       resultBuilder.push(hexString);
 *       return resultBuilder.join('');
 *     };
 *
 *     // ...
 */
public class Color(
  /**
   * The amount of red in the color as a value in the interval \[0, 1\].
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val red: Float = 0f,
  /**
   * The amount of green in the color as a value in the interval \[0, 1\].
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val green: Float = 0f,
  /**
   * The amount of blue in the color as a value in the interval \[0, 1\].
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val blue: Float = 0f,
  /**
   * The fraction of this color that should be applied to the pixel. That is,
   * the final pixel color is defined by the equation:
   *
   *   `pixel color = alpha * (this color) + (1.0 - alpha) * (background color)`
   *
   * This means that a value of 1.0 corresponds to a solid color, whereas
   * a value of 0.0 corresponds to a completely transparent color. This
   * uses a wrapper message rather than a simple float scalar so that it is
   * possible to distinguish between a default value and the value being unset.
   * If omitted, this color object is rendered as a solid color
   * (as if the alpha value had been explicitly given a value of 1.0).
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#FLOAT_VALUE",
    schemaIndex = 3,
  )
  public val alpha: Float? = null,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Color, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Color) return false
    if (unknownFields != other.unknownFields) return false
    if (red != other.red) return false
    if (green != other.green) return false
    if (blue != other.blue) return false
    if (alpha != other.alpha) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + red.hashCode()
      result = result * 37 + green.hashCode()
      result = result * 37 + blue.hashCode()
      result = result * 37 + (alpha?.hashCode() ?: 0)
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """red=$red"""
    result += """green=$green"""
    result += """blue=$blue"""
    if (alpha != null) result += """alpha=$alpha"""
    return result.joinToString(prefix = "Color{", separator = ", ", postfix = "}")
  }

  public fun copy(
    red: Float = this.red,
    green: Float = this.green,
    blue: Float = this.blue,
    alpha: Float? = this.alpha,
    unknownFields: ByteString = this.unknownFields,
  ): Color = Color(red, green, blue, alpha, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Color> = object : ProtoAdapter<Color>(
      FieldEncoding.LENGTH_DELIMITED, 
      Color::class, 
      "type.googleapis.com/google.type.Color", 
      PROTO_3, 
      null, 
      "google/type/color.proto"
    ) {
      override fun encodedSize(`value`: Color): Int {
        var size = value.unknownFields.size
        if (!value.red.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(1, value.red)
        }
        if (!value.green.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(2, value.green)
        }
        if (!value.blue.equals(0f)) {
          size += ProtoAdapter.FLOAT.encodedSizeWithTag(3, value.blue)
        }
        if (value.alpha != null) {
          size += ProtoAdapter.FLOAT_VALUE.encodedSizeWithTag(4, value.alpha)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Color) {
        if (!value.red.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 1, value.red)
        }
        if (!value.green.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.green)
        }
        if (!value.blue.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.blue)
        }
        if (value.alpha != null) {
          ProtoAdapter.FLOAT_VALUE.encodeWithTag(writer, 4, value.alpha)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Color) {
        writer.writeBytes(value.unknownFields)
        if (value.alpha != null) {
          ProtoAdapter.FLOAT_VALUE.encodeWithTag(writer, 4, value.alpha)
        }
        if (!value.blue.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 3, value.blue)
        }
        if (!value.green.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 2, value.green)
        }
        if (!value.red.equals(0f)) {
          ProtoAdapter.FLOAT.encodeWithTag(writer, 1, value.red)
        }
      }

      override fun decode(reader: ProtoReader): Color {
        var red: Float = 0f
        var green: Float = 0f
        var blue: Float = 0f
        var alpha: Float? = null
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> red = ProtoAdapter.FLOAT.decode(reader)
            2 -> green = ProtoAdapter.FLOAT.decode(reader)
            3 -> blue = ProtoAdapter.FLOAT.decode(reader)
            4 -> alpha = ProtoAdapter.FLOAT_VALUE.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Color(
          red = red,
          green = green,
          blue = blue,
          alpha = alpha,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Color): Color = value.copy(
        alpha = value.alpha?.let(ProtoAdapter.FLOAT_VALUE::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
