// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.LatLng in google/type/latlng.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Double
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * An object that represents a latitude/longitude pair. This is expressed as a
 * pair of doubles to represent degrees latitude and degrees longitude. Unless
 * specified otherwise, this object must conform to the
 * <a href="https://en.wikipedia.org/wiki/World_Geodetic_System#1984_version">
 * WGS84 standard</a>. Values must be within normalized ranges.
 */
public class LatLng(
  /**
   * The latitude in degrees. It must be in the range \[-90.0, +90.0\].
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val latitude: Double = 0.0,
  /**
   * The longitude in degrees. It must be in the range \[-180.0, +180.0\].
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#DOUBLE",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val longitude: Double = 0.0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<LatLng, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is LatLng) return false
    if (unknownFields != other.unknownFields) return false
    if (latitude != other.latitude) return false
    if (longitude != other.longitude) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + latitude.hashCode()
      result = result * 37 + longitude.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """latitude=$latitude"""
    result += """longitude=$longitude"""
    return result.joinToString(prefix = "LatLng{", separator = ", ", postfix = "}")
  }

  public fun copy(
    latitude: Double = this.latitude,
    longitude: Double = this.longitude,
    unknownFields: ByteString = this.unknownFields,
  ): LatLng = LatLng(latitude, longitude, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<LatLng> = object : ProtoAdapter<LatLng>(
      FieldEncoding.LENGTH_DELIMITED, 
      LatLng::class, 
      "type.googleapis.com/google.type.LatLng", 
      PROTO_3, 
      null, 
      "google/type/latlng.proto"
    ) {
      override fun encodedSize(`value`: LatLng): Int {
        var size = value.unknownFields.size
        if (!value.latitude.equals(0.0)) {
          size += ProtoAdapter.DOUBLE.encodedSizeWithTag(1, value.latitude)
        }
        if (!value.longitude.equals(0.0)) {
          size += ProtoAdapter.DOUBLE.encodedSizeWithTag(2, value.longitude)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: LatLng) {
        if (!value.latitude.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.latitude)
        }
        if (!value.longitude.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 2, value.longitude)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: LatLng) {
        writer.writeBytes(value.unknownFields)
        if (!value.longitude.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 2, value.longitude)
        }
        if (!value.latitude.equals(0.0)) {
          ProtoAdapter.DOUBLE.encodeWithTag(writer, 1, value.latitude)
        }
      }

      override fun decode(reader: ProtoReader): LatLng {
        var latitude: Double = 0.0
        var longitude: Double = 0.0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> latitude = ProtoAdapter.DOUBLE.decode(reader)
            2 -> longitude = ProtoAdapter.DOUBLE.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return LatLng(
          latitude = latitude,
          longitude = longitude,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: LatLng): LatLng = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
