// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.Money in google/type/money.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Represents an amount of money with its currency type.
 */
public class Money(
  /**
   * The three-letter currency code defined in ISO 4217.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "currencyCode",
    schemaIndex = 0,
  )
  public val currency_code: String = "",
  /**
   * The whole units of the amount.
   * For example if `currencyCode` is `"USD"`, then 1 unit is one US dollar.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT64",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val units: Long = 0L,
  /**
   * Number of nano (10^-9) units of the amount.
   * The value must be between -999,999,999 and +999,999,999 inclusive.
   * If `units` is positive, `nanos` must be positive or zero.
   * If `units` is zero, `nanos` can be positive, zero, or negative.
   * If `units` is negative, `nanos` must be negative or zero.
   * For example $-1.75 is represented as `units`=-1 and `nanos`=-750,000,000.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val nanos: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<Money, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is Money) return false
    if (unknownFields != other.unknownFields) return false
    if (currency_code != other.currency_code) return false
    if (units != other.units) return false
    if (nanos != other.nanos) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + currency_code.hashCode()
      result = result * 37 + units.hashCode()
      result = result * 37 + nanos.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """currency_code=${sanitize(currency_code)}"""
    result += """units=$units"""
    result += """nanos=$nanos"""
    return result.joinToString(prefix = "Money{", separator = ", ", postfix = "}")
  }

  public fun copy(
    currency_code: String = this.currency_code,
    units: Long = this.units,
    nanos: Int = this.nanos,
    unknownFields: ByteString = this.unknownFields,
  ): Money = Money(currency_code, units, nanos, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<Money> = object : ProtoAdapter<Money>(
      FieldEncoding.LENGTH_DELIMITED, 
      Money::class, 
      "type.googleapis.com/google.type.Money", 
      PROTO_3, 
      null, 
      "google/type/money.proto"
    ) {
      override fun encodedSize(`value`: Money): Int {
        var size = value.unknownFields.size
        if (value.currency_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.currency_code)
        }
        if (value.units != 0L) {
          size += ProtoAdapter.INT64.encodedSizeWithTag(2, value.units)
        }
        if (value.nanos != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.nanos)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: Money) {
        if (value.currency_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.currency_code)
        }
        if (value.units != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.units)
        }
        if (value.nanos != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.nanos)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: Money) {
        writer.writeBytes(value.unknownFields)
        if (value.nanos != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.nanos)
        }
        if (value.units != 0L) {
          ProtoAdapter.INT64.encodeWithTag(writer, 2, value.units)
        }
        if (value.currency_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.currency_code)
        }
      }

      override fun decode(reader: ProtoReader): Money {
        var currency_code: String = ""
        var units: Long = 0L
        var nanos: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> currency_code = ProtoAdapter.STRING.decode(reader)
            2 -> units = ProtoAdapter.INT64.decode(reader)
            3 -> nanos = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return Money(
          currency_code = currency_code,
          units = units,
          nanos = nanos,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: Money): Money = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
