// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.PhoneNumber in google/type/phone_number.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.countNonNull
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * An object representing a phone number, suitable as an API wire format.
 *
 * This representation:
 *
 *  - should not be used for locale-specific formatting of a phone number, such
 *    as "+1 (650) 253-0000 ext. 123"
 *
 *  - is not designed for efficient storage
 *  - may not be suitable for dialing - specialized libraries (see references)
 *    should be used to parse the number for that purpose
 *
 * To do something meaningful with this number, such as format it for various
 * use-cases, convert it to an `i18n.phonenumbers.PhoneNumber` object first.
 *
 * For instance, in Java this would be:
 *
 *     com.google.type.PhoneNumber wireProto =
 *         com.google.type.PhoneNumber.newBuilder().build();
 *     com.google.i18n.phonenumbers.Phonenumber.PhoneNumber phoneNumber =
 *         PhoneNumberUtil.getInstance().parse(wireProto.getE164Number(), "ZZ");
 *     if (!wireProto.getExtension().isEmpty()) {
 *       phoneNumber.setExtension(wireProto.getExtension());
 *     }
 *
 *  Reference(s):
 *   - https://github.com/google/libphonenumber
 */
public class PhoneNumber(
  /**
   * The phone number, represented as a leading plus sign ('+'), followed by a
   * phone number that uses a relaxed ITU E.164 format consisting of the
   * country calling code (1 to 3 digits) and the subscriber number, with no
   * additional spaces or formatting. For example:
   *
   *  - correct: "+15552220123"
   *
   *  - incorrect: "+1 (555) 222-01234 x123"
   *
   * The ITU E.164 format limits the latter to 12 digits, but in practice not
   * all countries respect that, so we relax that restriction here.
   * National-only numbers are not allowed.
   *
   * References:
   *
   *  - https://www.itu.int/rec/T-REC-E.164-201011-I
   *
   *  - https://en.wikipedia.org/wiki/E.164.
   *
   *  - https://en.wikipedia.org/wiki/List_of_country_calling_codes
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    jsonName = "e164Number",
    oneofName = "kind",
    schemaIndex = 0,
  )
  public val e164_number: String? = null,
  /**
   * A short code.
   *
   * Reference(s):
   *  - https://wikipedia.org/wiki/Short_code
   */
  @field:WireField(
    tag = 2,
    adapter = "com.google.type.PhoneNumber${'$'}ShortCode#ADAPTER",
    jsonName = "shortCode",
    oneofName = "kind",
    schemaIndex = 1,
  )
  public val short_code: ShortCode? = null,
  /**
   * The phone number's extension. The extension is not standardized in ITU
   * recommendations, except for being defined as a series of numbers with a
   * maximum length of 40 digits. Other than digits, some other dialing
   * characters such as ',' (indicating a wait) or '#' may be stored here.
   *
   * Note that no regions currently use extensions with short codes, so this
   * field is normally only set in conjunction with an E.164 number. It is held
   * separately from the E.164 number to allow for short code extensions in the
   * future.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val extension: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PhoneNumber, Nothing>(ADAPTER, unknownFields) {
  init {
    require(countNonNull(e164_number, short_code) <= 1) {
      "At most one of e164_number, short_code may be non-null"
    }
  }

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PhoneNumber) return false
    if (unknownFields != other.unknownFields) return false
    if (e164_number != other.e164_number) return false
    if (short_code != other.short_code) return false
    if (extension != other.extension) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + (e164_number?.hashCode() ?: 0)
      result = result * 37 + (short_code?.hashCode() ?: 0)
      result = result * 37 + extension.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    if (e164_number != null) result += """e164_number=${sanitize(e164_number)}"""
    if (short_code != null) result += """short_code=$short_code"""
    result += """extension=${sanitize(extension)}"""
    return result.joinToString(prefix = "PhoneNumber{", separator = ", ", postfix = "}")
  }

  public fun copy(
    e164_number: String? = this.e164_number,
    short_code: ShortCode? = this.short_code,
    extension: String = this.extension,
    unknownFields: ByteString = this.unknownFields,
  ): PhoneNumber = PhoneNumber(e164_number, short_code, extension, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PhoneNumber> = object : ProtoAdapter<PhoneNumber>(
      FieldEncoding.LENGTH_DELIMITED, 
      PhoneNumber::class, 
      "type.googleapis.com/google.type.PhoneNumber", 
      PROTO_3, 
      null, 
      "google/type/phone_number.proto"
    ) {
      override fun encodedSize(`value`: PhoneNumber): Int {
        var size = value.unknownFields.size
        size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.e164_number)
        size += ShortCode.ADAPTER.encodedSizeWithTag(2, value.short_code)
        if (value.extension != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.extension)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PhoneNumber) {
        if (value.extension != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.extension)
        }
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.e164_number)
        ShortCode.ADAPTER.encodeWithTag(writer, 2, value.short_code)
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PhoneNumber) {
        writer.writeBytes(value.unknownFields)
        ShortCode.ADAPTER.encodeWithTag(writer, 2, value.short_code)
        ProtoAdapter.STRING.encodeWithTag(writer, 1, value.e164_number)
        if (value.extension != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.extension)
        }
      }

      override fun decode(reader: ProtoReader): PhoneNumber {
        var e164_number: String? = null
        var short_code: ShortCode? = null
        var extension: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> e164_number = ProtoAdapter.STRING.decode(reader)
            2 -> short_code = ShortCode.ADAPTER.decode(reader)
            3 -> extension = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PhoneNumber(
          e164_number = e164_number,
          short_code = short_code,
          extension = extension,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PhoneNumber): PhoneNumber = value.copy(
        short_code = value.short_code?.let(ShortCode.ADAPTER::redact),
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }

  /**
   * An object representing a short code, which is a phone number that is
   * typically much shorter than regular phone numbers and can be used to
   * address messages in MMS and SMS systems, as well as for abbreviated dialing
   * (For example "Text 611 to see how many minutes you have remaining on your
   * plan.").
   *
   * Short codes are restricted to a region and are not internationally
   * dialable, which means the same short code can exist in different regions,
   * with different usage and pricing, even if those regions share the same
   * country calling code (For example: US and CA).
   */
  public class ShortCode(
    /**
     * Required. The BCP-47 region code of the location where calls to this
     * short code can be made, such as "US" and "BB".
     *
     * Reference(s):
     *  - http://www.unicode.org/reports/tr35/#unicode_region_subtag
     */
    @field:WireField(
      tag = 1,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY,
      jsonName = "regionCode",
      schemaIndex = 0,
    )
    public val region_code: String = "",
    /**
     * Required. The short code digits, without a leading plus ('+') or country
     * calling code. For example "611".
     */
    @field:WireField(
      tag = 2,
      adapter = "com.squareup.wire.ProtoAdapter#STRING",
      label = WireField.Label.OMIT_IDENTITY,
      schemaIndex = 1,
    )
    public val number: String = "",
    unknownFields: ByteString = ByteString.EMPTY,
  ) : Message<ShortCode, Nothing>(ADAPTER, unknownFields) {
    @Deprecated(
      message = "Shouldn't be used in Kotlin",
      level = DeprecationLevel.HIDDEN,
    )
    override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

    override fun equals(other: Any?): Boolean {
      if (other === this) return true
      if (other !is ShortCode) return false
      if (unknownFields != other.unknownFields) return false
      if (region_code != other.region_code) return false
      if (number != other.number) return false
      return true
    }

    override fun hashCode(): Int {
      var result = super.hashCode
      if (result == 0) {
        result = unknownFields.hashCode()
        result = result * 37 + region_code.hashCode()
        result = result * 37 + number.hashCode()
        super.hashCode = result
      }
      return result
    }

    override fun toString(): String {
      val result = mutableListOf<String>()
      result += """region_code=${sanitize(region_code)}"""
      result += """number=${sanitize(number)}"""
      return result.joinToString(prefix = "ShortCode{", separator = ", ", postfix = "}")
    }

    public fun copy(
      region_code: String = this.region_code,
      number: String = this.number,
      unknownFields: ByteString = this.unknownFields,
    ): ShortCode = ShortCode(region_code, number, unknownFields)

    public companion object {
      @JvmField
      public val ADAPTER: ProtoAdapter<ShortCode> = object : ProtoAdapter<ShortCode>(
        FieldEncoding.LENGTH_DELIMITED, 
        ShortCode::class, 
        "type.googleapis.com/google.type.PhoneNumber.ShortCode", 
        PROTO_3, 
        null, 
        "google/type/phone_number.proto"
      ) {
        override fun encodedSize(`value`: ShortCode): Int {
          var size = value.unknownFields.size
          if (value.region_code != "") {
            size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.region_code)
          }
          if (value.number != "") {
            size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.number)
          }
          return size
        }

        override fun encode(writer: ProtoWriter, `value`: ShortCode) {
          if (value.region_code != "") {
            ProtoAdapter.STRING.encodeWithTag(writer, 1, value.region_code)
          }
          if (value.number != "") {
            ProtoAdapter.STRING.encodeWithTag(writer, 2, value.number)
          }
          writer.writeBytes(value.unknownFields)
        }

        override fun encode(writer: ReverseProtoWriter, `value`: ShortCode) {
          writer.writeBytes(value.unknownFields)
          if (value.number != "") {
            ProtoAdapter.STRING.encodeWithTag(writer, 2, value.number)
          }
          if (value.region_code != "") {
            ProtoAdapter.STRING.encodeWithTag(writer, 1, value.region_code)
          }
        }

        override fun decode(reader: ProtoReader): ShortCode {
          var region_code: String = ""
          var number: String = ""
          val unknownFields = reader.forEachTag { tag ->
            when (tag) {
              1 -> region_code = ProtoAdapter.STRING.decode(reader)
              2 -> number = ProtoAdapter.STRING.decode(reader)
              else -> reader.readUnknownField(tag)
            }
          }
          return ShortCode(
            region_code = region_code,
            number = number,
            unknownFields = unknownFields
          )
        }

        override fun redact(`value`: ShortCode): ShortCode = value.copy(
          unknownFields = ByteString.EMPTY
        )
      }

      private const val serialVersionUID: Long = 0L
    }
  }
}
