// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.PostalAddress in google/type/postal_address.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.immutableCopyOf
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import kotlin.collections.List
import okio.ByteString

/**
 * Represents a postal address, such as for postal delivery or payments
 * addresses. With a postal address, a postal service can deliver items to a
 * premise, P.O. box, or similar. A postal address is not intended to model
 * geographical locations like roads, towns, or mountains.
 *
 * In typical usage, an address would be created by user input or from importing
 * existing data, depending on the type of process.
 *
 * Advice on address input or editing:
 *
 *  - Use an internationalization-ready address widget such as
 *  https://github.com/google/libaddressinput.
 *  - Users should not be presented with UI elements for input or editing of
 *  fields outside countries where that field is used.
 *
 * For more guidance on how to use this schema, see:
 * https://support.google.com/business/answer/6397478.
 */
public class PostalAddress(
  /**
   * The schema revision of the `PostalAddress`. This must be set to 0, which is
   * the latest revision.
   *
   * All new revisions **must** be backward compatible with old revisions.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val revision: Int = 0,
  /**
   * Required. CLDR region code of the country/region of the address. This
   * is never inferred and it is up to the user to ensure the value is
   * correct. See https://cldr.unicode.org/ and
   * https://www.unicode.org/cldr/charts/30/supplemental/territory_information.html
   * for details. Example: "CH" for Switzerland.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "regionCode",
    schemaIndex = 1,
  )
  public val region_code: String = "",
  /**
   * Optional. BCP-47 language code of the contents of this address (if
   * known). This is often the UI language of the input form or is expected
   * to match one of the languages used in the address' country/region, or their
   * transliterated equivalents.
   * This can affect formatting in certain countries, but is not critical
   * to the correctness of the data and will never affect any validation or
   * other non-formatting related operations.
   *
   * If this value is not known, it should be omitted (rather than specifying a
   * possibly incorrect default).
   *
   * Examples: "zh-Hant", "ja", "ja-Latn", "en".
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "languageCode",
    schemaIndex = 2,
  )
  public val language_code: String = "",
  /**
   * Optional. Postal code of the address. Not all countries use or require
   * postal codes to be present, but where they are used, they may trigger
   * additional validation with other parts of the address (for example,
   * state or zip code validation in the United States).
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "postalCode",
    schemaIndex = 3,
  )
  public val postal_code: String = "",
  /**
   * Optional. Additional, country-specific, sorting code. This is not used
   * in most regions. Where it is used, the value is either a string like
   * "CEDEX", optionally followed by a number (for example, "CEDEX 7"), or just
   * a number alone, representing the "sector code" (Jamaica), "delivery area
   * indicator" (Malawi) or "post office indicator" (Côte d'Ivoire).
   */
  @field:WireField(
    tag = 5,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "sortingCode",
    schemaIndex = 4,
  )
  public val sorting_code: String = "",
  /**
   * Optional. Highest administrative subdivision which is used for postal
   * addresses of a country or region.
   * For example, this can be a state, a province, an oblast, or a prefecture.
   * For Spain, this is the province and not the autonomous
   * community (for example, "Barcelona" and not "Catalonia").
   * Many countries don't use an administrative area in postal addresses. For
   * example, in Switzerland, this should be left unpopulated.
   */
  @field:WireField(
    tag = 6,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    jsonName = "administrativeArea",
    schemaIndex = 5,
  )
  public val administrative_area: String = "",
  /**
   * Optional. Generally refers to the city or town portion of the address.
   * Examples: US city, IT comune, UK post town.
   * In regions of the world where localities are not well defined or do not fit
   * into this structure well, leave `locality` empty and use `address_lines`.
   */
  @field:WireField(
    tag = 7,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 6,
  )
  public val locality: String = "",
  /**
   * Optional. Sublocality of the address.
   * For example, this can be a neighborhood, borough, or district.
   */
  @field:WireField(
    tag = 8,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 7,
  )
  public val sublocality: String = "",
  address_lines: List<String> = emptyList(),
  recipients: List<String> = emptyList(),
  /**
   * Optional. The name of the organization at the address.
   */
  @field:WireField(
    tag = 11,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 10,
  )
  public val organization: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<PostalAddress, Nothing>(ADAPTER, unknownFields) {
  /**
   * Unstructured address lines describing the lower levels of an address.
   *
   * Because values in `address_lines` do not have type information and may
   * sometimes contain multiple values in a single field (for example,
   * "Austin, TX"), it is important that the line order is clear. The order of
   * address lines should be "envelope order" for the country or region of the
   * address. In places where this can vary (for example, Japan),
   * `address_language` is used to make it explicit (for example, "ja" for
   * large-to-small ordering and "ja-Latn" or "en" for small-to-large). In this
   * way, the most specific line of an address can be selected based on the
   * language.
   *
   * The minimum permitted structural representation of an address consists
   * of a `region_code` with all remaining information placed in the
   * `address_lines`. It would be possible to format such an address very
   * approximately without geocoding, but no semantic reasoning could be
   * made about any of the address components until it was at least
   * partially resolved.
   *
   * Creating an address only containing a `region_code` and `address_lines` and
   * then geocoding is the recommended way to handle completely unstructured
   * addresses (as opposed to guessing which parts of the address should be
   * localities or administrative areas).
   */
  @field:WireField(
    tag = 9,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    jsonName = "addressLines",
    schemaIndex = 8,
  )
  public val address_lines: List<String> = immutableCopyOf("address_lines", address_lines)

  /**
   * Optional. The recipient at the address.
   * This field may, under certain circumstances, contain multiline information.
   * For example, it might contain "care of" information.
   */
  @field:WireField(
    tag = 10,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.REPEATED,
    schemaIndex = 9,
  )
  public val recipients: List<String> = immutableCopyOf("recipients", recipients)

  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is PostalAddress) return false
    if (unknownFields != other.unknownFields) return false
    if (revision != other.revision) return false
    if (region_code != other.region_code) return false
    if (language_code != other.language_code) return false
    if (postal_code != other.postal_code) return false
    if (sorting_code != other.sorting_code) return false
    if (administrative_area != other.administrative_area) return false
    if (locality != other.locality) return false
    if (sublocality != other.sublocality) return false
    if (address_lines != other.address_lines) return false
    if (recipients != other.recipients) return false
    if (organization != other.organization) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + revision.hashCode()
      result = result * 37 + region_code.hashCode()
      result = result * 37 + language_code.hashCode()
      result = result * 37 + postal_code.hashCode()
      result = result * 37 + sorting_code.hashCode()
      result = result * 37 + administrative_area.hashCode()
      result = result * 37 + locality.hashCode()
      result = result * 37 + sublocality.hashCode()
      result = result * 37 + address_lines.hashCode()
      result = result * 37 + recipients.hashCode()
      result = result * 37 + organization.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """revision=$revision"""
    result += """region_code=${sanitize(region_code)}"""
    result += """language_code=${sanitize(language_code)}"""
    result += """postal_code=${sanitize(postal_code)}"""
    result += """sorting_code=${sanitize(sorting_code)}"""
    result += """administrative_area=${sanitize(administrative_area)}"""
    result += """locality=${sanitize(locality)}"""
    result += """sublocality=${sanitize(sublocality)}"""
    if (address_lines.isNotEmpty()) result += """address_lines=${sanitize(address_lines)}"""
    if (recipients.isNotEmpty()) result += """recipients=${sanitize(recipients)}"""
    result += """organization=${sanitize(organization)}"""
    return result.joinToString(prefix = "PostalAddress{", separator = ", ", postfix = "}")
  }

  public fun copy(
    revision: Int = this.revision,
    region_code: String = this.region_code,
    language_code: String = this.language_code,
    postal_code: String = this.postal_code,
    sorting_code: String = this.sorting_code,
    administrative_area: String = this.administrative_area,
    locality: String = this.locality,
    sublocality: String = this.sublocality,
    address_lines: List<String> = this.address_lines,
    recipients: List<String> = this.recipients,
    organization: String = this.organization,
    unknownFields: ByteString = this.unknownFields,
  ): PostalAddress = PostalAddress(revision, region_code, language_code, postal_code, sorting_code, administrative_area, locality, sublocality, address_lines, recipients, organization, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<PostalAddress> = object : ProtoAdapter<PostalAddress>(
      FieldEncoding.LENGTH_DELIMITED, 
      PostalAddress::class, 
      "type.googleapis.com/google.type.PostalAddress", 
      PROTO_3, 
      null, 
      "google/type/postal_address.proto"
    ) {
      override fun encodedSize(`value`: PostalAddress): Int {
        var size = value.unknownFields.size
        if (value.revision != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.revision)
        }
        if (value.region_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.region_code)
        }
        if (value.language_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(3, value.language_code)
        }
        if (value.postal_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(4, value.postal_code)
        }
        if (value.sorting_code != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(5, value.sorting_code)
        }
        if (value.administrative_area != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(6, value.administrative_area)
        }
        if (value.locality != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(7, value.locality)
        }
        if (value.sublocality != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(8, value.sublocality)
        }
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(9, value.address_lines)
        size += ProtoAdapter.STRING.asRepeated().encodedSizeWithTag(10, value.recipients)
        if (value.organization != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(11, value.organization)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: PostalAddress) {
        if (value.revision != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.revision)
        }
        if (value.region_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.region_code)
        }
        if (value.language_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.language_code)
        }
        if (value.postal_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.postal_code)
        }
        if (value.sorting_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.sorting_code)
        }
        if (value.administrative_area != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.administrative_area)
        }
        if (value.locality != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.locality)
        }
        if (value.sublocality != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.sublocality)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 9, value.address_lines)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 10, value.recipients)
        if (value.organization != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.organization)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: PostalAddress) {
        writer.writeBytes(value.unknownFields)
        if (value.organization != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 11, value.organization)
        }
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 10, value.recipients)
        ProtoAdapter.STRING.asRepeated().encodeWithTag(writer, 9, value.address_lines)
        if (value.sublocality != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 8, value.sublocality)
        }
        if (value.locality != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 7, value.locality)
        }
        if (value.administrative_area != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 6, value.administrative_area)
        }
        if (value.sorting_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 5, value.sorting_code)
        }
        if (value.postal_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 4, value.postal_code)
        }
        if (value.language_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 3, value.language_code)
        }
        if (value.region_code != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.region_code)
        }
        if (value.revision != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.revision)
        }
      }

      override fun decode(reader: ProtoReader): PostalAddress {
        var revision: Int = 0
        var region_code: String = ""
        var language_code: String = ""
        var postal_code: String = ""
        var sorting_code: String = ""
        var administrative_area: String = ""
        var locality: String = ""
        var sublocality: String = ""
        val address_lines = mutableListOf<String>()
        val recipients = mutableListOf<String>()
        var organization: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> revision = ProtoAdapter.INT32.decode(reader)
            2 -> region_code = ProtoAdapter.STRING.decode(reader)
            3 -> language_code = ProtoAdapter.STRING.decode(reader)
            4 -> postal_code = ProtoAdapter.STRING.decode(reader)
            5 -> sorting_code = ProtoAdapter.STRING.decode(reader)
            6 -> administrative_area = ProtoAdapter.STRING.decode(reader)
            7 -> locality = ProtoAdapter.STRING.decode(reader)
            8 -> sublocality = ProtoAdapter.STRING.decode(reader)
            9 -> address_lines.add(ProtoAdapter.STRING.decode(reader))
            10 -> recipients.add(ProtoAdapter.STRING.decode(reader))
            11 -> organization = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return PostalAddress(
          revision = revision,
          region_code = region_code,
          language_code = language_code,
          postal_code = postal_code,
          sorting_code = sorting_code,
          administrative_area = administrative_area,
          locality = locality,
          sublocality = sublocality,
          address_lines = address_lines,
          recipients = recipients,
          organization = organization,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: PostalAddress): PostalAddress = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
