// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.TimeOfDay in google/type/timeofday.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Represents a time of day. The date and time zone are either not significant
 * or are specified elsewhere. An API may choose to allow leap seconds. Related
 * types are \[google.type.Date\]\[google.type.Date\] and
 * `google.protobuf.Timestamp`.
 */
public class TimeOfDay(
  /**
   * Hours of a day in 24 hour format. Must be greater than or equal to 0 and
   * typically must be less than or equal to 23. An API may choose to allow the
   * value "24:00:00" for scenarios like business closing time.
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val hours: Int = 0,
  /**
   * Minutes of an hour. Must be greater than or equal to 0 and less than or
   * equal to 59.
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val minutes: Int = 0,
  /**
   * Seconds of a minute. Must be greater than or equal to 0 and typically must
   * be less than or equal to 59. An API may allow the value 60 if it allows
   * leap-seconds.
   */
  @field:WireField(
    tag = 3,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 2,
  )
  public val seconds: Int = 0,
  /**
   * Fractions of seconds, in nanoseconds. Must be greater than or equal to 0
   * and less than or equal to 999,999,999.
   */
  @field:WireField(
    tag = 4,
    adapter = "com.squareup.wire.ProtoAdapter#INT32",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 3,
  )
  public val nanos: Int = 0,
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TimeOfDay, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TimeOfDay) return false
    if (unknownFields != other.unknownFields) return false
    if (hours != other.hours) return false
    if (minutes != other.minutes) return false
    if (seconds != other.seconds) return false
    if (nanos != other.nanos) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + hours.hashCode()
      result = result * 37 + minutes.hashCode()
      result = result * 37 + seconds.hashCode()
      result = result * 37 + nanos.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """hours=$hours"""
    result += """minutes=$minutes"""
    result += """seconds=$seconds"""
    result += """nanos=$nanos"""
    return result.joinToString(prefix = "TimeOfDay{", separator = ", ", postfix = "}")
  }

  public fun copy(
    hours: Int = this.hours,
    minutes: Int = this.minutes,
    seconds: Int = this.seconds,
    nanos: Int = this.nanos,
    unknownFields: ByteString = this.unknownFields,
  ): TimeOfDay = TimeOfDay(hours, minutes, seconds, nanos, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TimeOfDay> = object : ProtoAdapter<TimeOfDay>(
      FieldEncoding.LENGTH_DELIMITED, 
      TimeOfDay::class, 
      "type.googleapis.com/google.type.TimeOfDay", 
      PROTO_3, 
      null, 
      "google/type/timeofday.proto"
    ) {
      override fun encodedSize(`value`: TimeOfDay): Int {
        var size = value.unknownFields.size
        if (value.hours != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(1, value.hours)
        }
        if (value.minutes != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(2, value.minutes)
        }
        if (value.seconds != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(3, value.seconds)
        }
        if (value.nanos != 0) {
          size += ProtoAdapter.INT32.encodedSizeWithTag(4, value.nanos)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TimeOfDay) {
        if (value.hours != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.hours)
        }
        if (value.minutes != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.minutes)
        }
        if (value.seconds != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.seconds)
        }
        if (value.nanos != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.nanos)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TimeOfDay) {
        writer.writeBytes(value.unknownFields)
        if (value.nanos != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 4, value.nanos)
        }
        if (value.seconds != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 3, value.seconds)
        }
        if (value.minutes != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 2, value.minutes)
        }
        if (value.hours != 0) {
          ProtoAdapter.INT32.encodeWithTag(writer, 1, value.hours)
        }
      }

      override fun decode(reader: ProtoReader): TimeOfDay {
        var hours: Int = 0
        var minutes: Int = 0
        var seconds: Int = 0
        var nanos: Int = 0
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> hours = ProtoAdapter.INT32.decode(reader)
            2 -> minutes = ProtoAdapter.INT32.decode(reader)
            3 -> seconds = ProtoAdapter.INT32.decode(reader)
            4 -> nanos = ProtoAdapter.INT32.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TimeOfDay(
          hours = hours,
          minutes = minutes,
          seconds = seconds,
          nanos = nanos,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TimeOfDay): TimeOfDay = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
