// Code generated by Wire protocol buffer compiler, do not edit.
// Source: google.type.TimeZone in google/type/datetime.proto
@file:Suppress(
  "DEPRECATION",
  "RUNTIME_ANNOTATION_NOT_SUPPORTED",
)

package com.google.type

import com.squareup.wire.FieldEncoding
import com.squareup.wire.Message
import com.squareup.wire.ProtoAdapter
import com.squareup.wire.ProtoReader
import com.squareup.wire.ProtoWriter
import com.squareup.wire.ReverseProtoWriter
import com.squareup.wire.Syntax.PROTO_3
import com.squareup.wire.WireField
import com.squareup.wire.`internal`.JvmField
import com.squareup.wire.`internal`.sanitize
import kotlin.Any
import kotlin.AssertionError
import kotlin.Boolean
import kotlin.Deprecated
import kotlin.DeprecationLevel
import kotlin.Int
import kotlin.Long
import kotlin.Nothing
import kotlin.String
import kotlin.Suppress
import okio.ByteString

/**
 * Represents a time zone from the
 * \[IANA Time Zone Database\](https://www.iana.org/time-zones).
 */
public class TimeZone(
  /**
   * IANA Time Zone Database time zone. For example "America/New_York".
   */
  @field:WireField(
    tag = 1,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 0,
  )
  public val id: String = "",
  /**
   * Optional. IANA Time Zone Database version number. For example "2019a".
   */
  @field:WireField(
    tag = 2,
    adapter = "com.squareup.wire.ProtoAdapter#STRING",
    label = WireField.Label.OMIT_IDENTITY,
    schemaIndex = 1,
  )
  public val version: String = "",
  unknownFields: ByteString = ByteString.EMPTY,
) : Message<TimeZone, Nothing>(ADAPTER, unknownFields) {
  @Deprecated(
    message = "Shouldn't be used in Kotlin",
    level = DeprecationLevel.HIDDEN,
  )
  override fun newBuilder(): Nothing = throw AssertionError("Builders are deprecated and only available in a javaInterop build; see https://square.github.io/wire/wire_compiler/#kotlin")

  override fun equals(other: Any?): Boolean {
    if (other === this) return true
    if (other !is TimeZone) return false
    if (unknownFields != other.unknownFields) return false
    if (id != other.id) return false
    if (version != other.version) return false
    return true
  }

  override fun hashCode(): Int {
    var result = super.hashCode
    if (result == 0) {
      result = unknownFields.hashCode()
      result = result * 37 + id.hashCode()
      result = result * 37 + version.hashCode()
      super.hashCode = result
    }
    return result
  }

  override fun toString(): String {
    val result = mutableListOf<String>()
    result += """id=${sanitize(id)}"""
    result += """version=${sanitize(version)}"""
    return result.joinToString(prefix = "TimeZone{", separator = ", ", postfix = "}")
  }

  public fun copy(
    id: String = this.id,
    version: String = this.version,
    unknownFields: ByteString = this.unknownFields,
  ): TimeZone = TimeZone(id, version, unknownFields)

  public companion object {
    @JvmField
    public val ADAPTER: ProtoAdapter<TimeZone> = object : ProtoAdapter<TimeZone>(
      FieldEncoding.LENGTH_DELIMITED, 
      TimeZone::class, 
      "type.googleapis.com/google.type.TimeZone", 
      PROTO_3, 
      null, 
      "google/type/datetime.proto"
    ) {
      override fun encodedSize(`value`: TimeZone): Int {
        var size = value.unknownFields.size
        if (value.id != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(1, value.id)
        }
        if (value.version != "") {
          size += ProtoAdapter.STRING.encodedSizeWithTag(2, value.version)
        }
        return size
      }

      override fun encode(writer: ProtoWriter, `value`: TimeZone) {
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version)
        }
        writer.writeBytes(value.unknownFields)
      }

      override fun encode(writer: ReverseProtoWriter, `value`: TimeZone) {
        writer.writeBytes(value.unknownFields)
        if (value.version != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 2, value.version)
        }
        if (value.id != "") {
          ProtoAdapter.STRING.encodeWithTag(writer, 1, value.id)
        }
      }

      override fun decode(reader: ProtoReader): TimeZone {
        var id: String = ""
        var version: String = ""
        val unknownFields = reader.forEachTag { tag ->
          when (tag) {
            1 -> id = ProtoAdapter.STRING.decode(reader)
            2 -> version = ProtoAdapter.STRING.decode(reader)
            else -> reader.readUnknownField(tag)
          }
        }
        return TimeZone(
          id = id,
          version = version,
          unknownFields = unknownFields
        )
      }

      override fun redact(`value`: TimeZone): TimeZone = value.copy(
        unknownFields = ByteString.EMPTY
      )
    }

    private const val serialVersionUID: Long = 0L
  }
}
