#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Detecting breaking changes"

TEST_PATHS=(
	anthropic-java-core/src/test/kotlin/com/anthropic/models
	anthropic-java-core/src/test/kotlin/com/anthropic/services
)

for PATHSPEC in "${TEST_PATHS[@]}"; do
    # Try to check out previous versions of the test files
    # with the current SDK.
    git checkout "$1" -- "${PATHSPEC}" 2>/dev/null || true
done

# Run the build so that the Kotlin compiler typechecks the restored
# old test files against the current SDK.
./scripts/build
