package com.anthropic.models.messages

import com.anthropic.core.BaseDeserializer
import com.anthropic.core.BaseSerializer
import com.anthropic.core.Enum
import com.anthropic.core.JsonField
import com.anthropic.core.JsonMissing
import com.anthropic.core.JsonValue
import com.anthropic.core.getOrThrow
import com.anthropic.core.getProperty
import com.anthropic.errors.AnthropicInvalidDataException
import com.fasterxml.jackson.annotation.JsonCreator
import com.fasterxml.jackson.core.JsonGenerator
import com.fasterxml.jackson.core.ObjectCodec
import com.fasterxml.jackson.databind.JsonNode
import com.fasterxml.jackson.databind.SerializerProvider
import com.fasterxml.jackson.databind.annotation.JsonDeserialize
import com.fasterxml.jackson.databind.annotation.JsonSerialize
import com.fasterxml.jackson.module.kotlin.jacksonTypeRef
import java.util.Objects
import java.util.Optional
import kotlin.jvm.optionals.getOrNull

/** Which party invoked the tool call: the model directly, or a server tool on its behalf. */
@JsonDeserialize(using = ToolUseCaller.Deserializer::class)
@JsonSerialize(using = ToolUseCaller.Serializer::class)
class ToolUseCaller
private constructor(
    private val direct: DirectCaller? = null,
    private val codeExecution20250825: ServerToolCaller? = null,
    private val codeExecution20260120: ServerToolCaller20260120? = null,
    private val _json: JsonValue? = null,
) {

    fun type(): Type =
        when {
            direct != null -> Type.DIRECT
            codeExecution20250825 != null -> Type.CODE_EXECUTION_20250825
            codeExecution20260120 != null -> Type.CODE_EXECUTION_20260120
            else -> Type.of(_json?.asObject()?.getOrNull()?.get("type") ?: JsonMissing.of())
        }

    fun toolId(): Optional<String> =
        when {
            direct != null -> Optional.empty()
            codeExecution20250825 != null -> Optional.of(codeExecution20250825.toolId())
            codeExecution20260120 != null -> Optional.of(codeExecution20260120.toolId())
            else -> _json.getProperty<String>("tool_id").asKnown()
        }

    /** Tool invocation directly from the model. */
    fun direct(): Optional<DirectCaller> = Optional.ofNullable(direct)

    /** Tool invocation generated by a server-side tool. */
    fun codeExecution20250825(): Optional<ServerToolCaller> =
        Optional.ofNullable(codeExecution20250825)

    fun codeExecution20260120(): Optional<ServerToolCaller20260120> =
        Optional.ofNullable(codeExecution20260120)

    fun isDirect(): Boolean = direct != null

    fun isCodeExecution20250825(): Boolean = codeExecution20250825 != null

    fun isCodeExecution20260120(): Boolean = codeExecution20260120 != null

    /** Tool invocation directly from the model. */
    fun asDirect(): DirectCaller = direct.getOrThrow("direct")

    /** Tool invocation generated by a server-side tool. */
    fun asCodeExecution20250825(): ServerToolCaller =
        codeExecution20250825.getOrThrow("codeExecution20250825")

    fun asCodeExecution20260120(): ServerToolCaller20260120 =
        codeExecution20260120.getOrThrow("codeExecution20260120")

    fun _json(): Optional<JsonValue> = Optional.ofNullable(_json)

    /**
     * Maps this instance's current variant to a value of type [T] using the given [visitor].
     *
     * Note that this method is _not_ forwards compatible with new variants from the API, unless
     * [visitor] overrides [Visitor.unknown]. To handle variants not known to this version of the
     * SDK gracefully, consider overriding [Visitor.unknown]:
     * ```java
     * import com.anthropic.core.JsonValue;
     * import java.util.Optional;
     *
     * Optional<String> result = toolUseCaller.accept(new ToolUseCaller.Visitor<Optional<String>>() {
     *     @Override
     *     public Optional<String> visitDirect(DirectCaller direct) {
     *         return Optional.of(direct.toString());
     *     }
     *
     *     // ...
     *
     *     @Override
     *     public Optional<String> unknown(JsonValue json) {
     *         // Or inspect the `json`.
     *         return Optional.empty();
     *     }
     * });
     * ```
     *
     * @throws AnthropicInvalidDataException if [Visitor.unknown] is not overridden in [visitor] and
     *   the current variant is unknown.
     */
    fun <T> accept(visitor: Visitor<T>): T =
        when {
            direct != null -> visitor.visitDirect(direct)
            codeExecution20250825 != null ->
                visitor.visitCodeExecution20250825(codeExecution20250825)
            codeExecution20260120 != null ->
                visitor.visitCodeExecution20260120(codeExecution20260120)
            else -> visitor.unknown(_json)
        }

    private var validated: Boolean = false

    /**
     * Validates that the types of all values in this object match their expected types recursively.
     *
     * This method is _not_ forwards compatible with new types from the API for existing fields.
     *
     * @throws AnthropicInvalidDataException if any value type in this object doesn't match its
     *   expected type.
     */
    fun validate(): ToolUseCaller = apply {
        if (validated) {
            return@apply
        }

        when {
            direct != null -> direct.validate()
            codeExecution20250825 != null -> codeExecution20250825.validate()
            codeExecution20260120 != null -> codeExecution20260120.validate()
            else -> throw AnthropicInvalidDataException("Unknown ToolUseCaller: $_json")
        }
        validated = true
    }

    fun isValid(): Boolean =
        try {
            validate()
            true
        } catch (e: AnthropicInvalidDataException) {
            false
        }

    /**
     * Returns a score indicating how many valid values are contained in this object recursively.
     *
     * Used for best match union deserialization.
     */
    @JvmSynthetic
    internal fun validity(): Int =
        when {
            direct != null -> direct.validity()
            codeExecution20250825 != null -> codeExecution20250825.validity()
            codeExecution20260120 != null -> codeExecution20260120.validity()
            else -> 0
        }

    override fun equals(other: Any?): Boolean {
        if (this === other) {
            return true
        }

        return other is ToolUseCaller &&
            direct == other.direct &&
            codeExecution20250825 == other.codeExecution20250825 &&
            codeExecution20260120 == other.codeExecution20260120
    }

    override fun hashCode(): Int =
        Objects.hash(direct, codeExecution20250825, codeExecution20260120)

    override fun toString(): String =
        when {
            direct != null -> "ToolUseCaller{direct=$direct}"
            codeExecution20250825 != null ->
                "ToolUseCaller{codeExecution20250825=$codeExecution20250825}"
            codeExecution20260120 != null ->
                "ToolUseCaller{codeExecution20260120=$codeExecution20260120}"
            _json != null -> "ToolUseCaller{_unknown=$_json}"
            else -> throw IllegalStateException("Invalid ToolUseCaller")
        }

    companion object {

        /** Tool invocation directly from the model. */
        @JvmStatic fun ofDirect(direct: DirectCaller) = ToolUseCaller(direct = direct)

        /** Tool invocation generated by a server-side tool. */
        @JvmStatic
        fun ofCodeExecution20250825(codeExecution20250825: ServerToolCaller) =
            ToolUseCaller(codeExecution20250825 = codeExecution20250825)

        /**
         * Returns an immutable instance of [ToolUseCaller] whose [ofCodeExecution20250825] variant
         * is built from the given required [toolId].
         */
        @JvmStatic
        fun ofCodeExecution20250825(toolId: String) =
            ofCodeExecution20250825(ServerToolCaller.of(toolId))

        @JvmStatic
        fun ofCodeExecution20260120(codeExecution20260120: ServerToolCaller20260120) =
            ToolUseCaller(codeExecution20260120 = codeExecution20260120)

        /**
         * Returns an immutable instance of [ToolUseCaller] whose [ofCodeExecution20260120] variant
         * is built from the given required [toolId].
         */
        @JvmStatic
        fun ofCodeExecution20260120(toolId: String) =
            ofCodeExecution20260120(ServerToolCaller20260120.of(toolId))
    }

    /**
     * An interface that defines how to map each variant of [ToolUseCaller] to a value of type [T].
     */
    interface Visitor<out T> {

        /** Tool invocation directly from the model. */
        fun visitDirect(direct: DirectCaller): T

        /** Tool invocation generated by a server-side tool. */
        fun visitCodeExecution20250825(codeExecution20250825: ServerToolCaller): T

        fun visitCodeExecution20260120(codeExecution20260120: ServerToolCaller20260120): T

        /**
         * Maps an unknown variant of [ToolUseCaller] to a value of type [T].
         *
         * An instance of [ToolUseCaller] can contain an unknown variant if it was deserialized from
         * data that doesn't match any known variant. For example, if the SDK is on an older version
         * than the API, then the API may respond with new variants that the SDK is unaware of.
         *
         * @throws AnthropicInvalidDataException in the default implementation.
         */
        fun unknown(json: JsonValue?): T {
            throw AnthropicInvalidDataException("Unknown ToolUseCaller: $json")
        }
    }

    internal class Deserializer : BaseDeserializer<ToolUseCaller>(ToolUseCaller::class) {

        override fun ObjectCodec.deserialize(node: JsonNode): ToolUseCaller {
            val json = JsonValue.fromJsonNode(node)
            val type = json.asObject().getOrNull()?.get("type")?.asString()?.getOrNull()

            when (type) {
                "direct" -> {
                    return tryDeserialize(node, jacksonTypeRef<DirectCaller>())?.let {
                        ToolUseCaller(direct = it, _json = json)
                    } ?: ToolUseCaller(_json = json)
                }
                "code_execution_20250825" -> {
                    return tryDeserialize(node, jacksonTypeRef<ServerToolCaller>())?.let {
                        ToolUseCaller(codeExecution20250825 = it, _json = json)
                    } ?: ToolUseCaller(_json = json)
                }
                "code_execution_20260120" -> {
                    return tryDeserialize(node, jacksonTypeRef<ServerToolCaller20260120>())?.let {
                        ToolUseCaller(codeExecution20260120 = it, _json = json)
                    } ?: ToolUseCaller(_json = json)
                }
            }

            return ToolUseCaller(_json = json)
        }
    }

    internal class Serializer : BaseSerializer<ToolUseCaller>(ToolUseCaller::class) {

        override fun serialize(
            value: ToolUseCaller,
            generator: JsonGenerator,
            provider: SerializerProvider,
        ) {
            when {
                value.direct != null -> generator.writeObject(value.direct)
                value.codeExecution20250825 != null ->
                    generator.writeObject(value.codeExecution20250825)
                value.codeExecution20260120 != null ->
                    generator.writeObject(value.codeExecution20260120)
                value._json != null -> generator.writeObject(value._json)
                else -> throw IllegalStateException("Invalid ToolUseCaller")
            }
        }
    }

    class Type private constructor(private val value: JsonField<String>) : Enum {

        /**
         * Returns this class instance's raw value.
         *
         * This is usually only useful if this instance was deserialized from data that doesn't
         * match any known member, and you want to know that value. For example, if the SDK is on an
         * older version than the API, then the API may respond with new members that the SDK is
         * unaware of.
         */
        @com.fasterxml.jackson.annotation.JsonValue fun _value(): JsonField<String> = value

        companion object {

            @JvmField val DIRECT = Type(JsonField.of("direct"))

            @JvmField val CODE_EXECUTION_20250825 = Type(JsonField.of("code_execution_20250825"))

            @JvmField val CODE_EXECUTION_20260120 = Type(JsonField.of("code_execution_20260120"))

            @JvmStatic
            fun of(value: String): Type =
                // Intern known values so `==` works
                when (value) {
                    "direct" -> DIRECT
                    "code_execution_20250825" -> CODE_EXECUTION_20250825
                    "code_execution_20260120" -> CODE_EXECUTION_20260120
                    else -> Type(JsonField.of(value))
                }

            @JsonCreator
            @JvmStatic
            fun of(value: JsonField<String>): Type =
                value.asString().getOrNull()?.let { of(it) } ?: Type(value)
        }

        /** An enum containing [Type]'s known values. */
        enum class Known {
            DIRECT,
            CODE_EXECUTION_20250825,
            CODE_EXECUTION_20260120,
        }

        /**
         * An enum containing [Type]'s known values, as well as an [_UNKNOWN] member.
         *
         * An instance of [Type] can contain an unknown value in a couple of cases:
         * - It was deserialized from data that doesn't match any known member. For example, if the
         *   SDK is on an older version than the API, then the API may respond with new members that
         *   the SDK is unaware of.
         * - It was constructed with an arbitrary value using the [of] method.
         */
        enum class Value {
            DIRECT,
            CODE_EXECUTION_20250825,
            CODE_EXECUTION_20260120,
            /** An enum member indicating that [Type] was instantiated with an unknown value. */
            _UNKNOWN,
        }

        /**
         * Returns an enum member corresponding to this class instance's value, or [Value._UNKNOWN]
         * if the class was instantiated with an unknown value.
         *
         * Use the [known] method instead if you're certain the value is always known or if you want
         * to throw for the unknown case.
         */
        fun value(): Value =
            when (this) {
                DIRECT -> Value.DIRECT
                CODE_EXECUTION_20250825 -> Value.CODE_EXECUTION_20250825
                CODE_EXECUTION_20260120 -> Value.CODE_EXECUTION_20260120
                else -> Value._UNKNOWN
            }

        /**
         * Returns an enum member corresponding to this class instance's value.
         *
         * Use the [value] method instead if you're uncertain the value is always known and don't
         * want to throw for the unknown case.
         *
         * @throws AnthropicInvalidDataException if this class instance's value is a not a known
         *   member.
         */
        fun known(): Known =
            when (this) {
                DIRECT -> Known.DIRECT
                CODE_EXECUTION_20250825 -> Known.CODE_EXECUTION_20250825
                CODE_EXECUTION_20260120 -> Known.CODE_EXECUTION_20260120
                else -> throw AnthropicInvalidDataException("Unknown Type: $value")
            }

        /**
         * Returns this class instance's primitive wire representation.
         *
         * This differs from the [toString] method because that method is primarily for debugging
         * and generally doesn't throw.
         *
         * @throws AnthropicInvalidDataException if this class instance's value does not have the
         *   expected primitive type.
         */
        fun asString(): String =
            _value().asString().orElseThrow {
                AnthropicInvalidDataException("Value is not a String")
            }

        private var validated: Boolean = false

        /**
         * Validates that the types of all values in this object match their expected types
         * recursively.
         *
         * This method is _not_ forwards compatible with new types from the API for existing fields.
         *
         * @throws AnthropicInvalidDataException if any value type in this object doesn't match its
         *   expected type.
         */
        fun validate(): Type = apply {
            if (validated) {
                return@apply
            }

            known()
            validated = true
        }

        fun isValid(): Boolean =
            try {
                validate()
                true
            } catch (e: AnthropicInvalidDataException) {
                false
            }

        /**
         * Returns a score indicating how many valid values are contained in this object
         * recursively.
         *
         * Used for best match union deserialization.
         */
        @JvmSynthetic internal fun validity(): Int = if (value() == Value._UNKNOWN) 0 else 1

        override fun equals(other: Any?): Boolean {
            if (this === other) {
                return true
            }

            return other is Type && value == other.value
        }

        override fun hashCode() = value.hashCode()

        override fun toString() = value.toString()
    }
}
